### ISSUE TITLE
Realsense integration

### ISSUE THREAD

**Issue by liangdu** [introlab/rtabmap#100]
Hi @matlabbe , Do you consider add Realsense driver as input device as well, like kinect ?

Thanks,

**Comment by ayumizll** [comment]
It will be awesome if realsense can work with rtab :)

**Comment by francescoli** [comment]
Yes, I also consider about it to check if Realsense is suitable for us because Kinect is a little big and heavy for mobile use.

**Comment by matlabbe** [comment]
Well, I will receive a r200 in the next week, the corresponding driver in the standalone may appear after that!

**Comment by francescoli** [comment]
@matlabbe In librealsense there is a synthetic stream named depth_aligned_to_rectified_color. I tried without the registration step, but the mapping result seems bad...

**Comment by matlabbe** [comment]
Realsense is integrated in 0.11.8!
