### ISSUE TITLE
Problem compiling with opencv 4.7.0

### ISSUE THREAD

**Issue by BryanBetancur** [introlab/rtabmap#1005]
Hello, I'm having problems compiling Rtabmap when I upgrade Opencv to 4.7.0. Previously I was working well with Opencv 4.5.0 but right now I need a new version of opencv to work other applications in the same system.

**This is the build configuration:**
![image](https://user-images.githubusercontent.com/31115065/228888624-51418048-d821-49a8-9a83-894a680a7ce6.png)
![image](https://user-images.githubusercontent.com/31115065/228888734-3d67701b-0e24-41d9-84c7-b10b16f67af1.png)

**This is the error:**
![image](https://user-images.githubusercontent.com/31115065/228887892-967a5c99-380a-452d-8ba8-87ad07cb23bb.png)

I appreciate if you could guide me to solve it. Thank you.

**Comment by matlabbe** [comment]
You need to update rtabmap, this has been fixed in this PR: https://github.com/introlab/rtabmap/pull/955

**Comment by BryanBetancur** [comment]
Got it, thanks.
