### ISSUE TITLE
Hi, please, what is your timeline for releasing a new apt package ros-rolling-rtabmap?

### ISSUE THREAD

**Issue by hodnajit** [introlab/rtabmap#1009]
I saw, that the package was removed in last ros:rolling release:

https://discourse.ros.org/t/new-packages-for-ros-2-rolling-ridley-2023-03-29/30609

Thanks

Best regards Jitka

**Comment by matlabbe** [comment]
It will come back next release: http://repo.ros2.org/status_page/rolling_default.html?q=ros-rolling-rtabmap
