### ISSUE TITLE
3D Keypoints and Coordinate System 

### ISSUE THREAD

**Issue by laitifranz** [introlab/rtabmap#1010]
Hi!

I am interested in extracting the 3D points of all the keypoints to reconstruct a sparse 3D points matrix.
I was looking at the function https://github.com/introlab/rtabmap/blob/6dca8ab0f366b2628cafc332ec5ef10869e120b3/corelib/src/util3d_features.cpp#L54-L59

I would like to know if the resulting 3D keypoints are computed with respect to the camera pose or the global coordinate system.

Also, I would like a confirmation on how to retrieve all the data from a node `id` in a database. I found that https://github.com/introlab/rtabmap/blob/6dca8ab0f366b2628cafc332ec5ef10869e120b3/corelib/src/DBDriver.cpp#L537 get all the info, but the `_sensorData` parameter https://github.com/introlab/rtabmap/blob/6dca8ab0f366b2628cafc332ec5ef10869e120b3/corelib/src/Signature.cpp#L73 is not filled with any info of the node. Is that correct? Because I saw that all the data of the node are returned by the `DBDriver::loadSignature`

Thank you in advance!

**Comment by matlabbe** [comment]
Hi,

* In `generateKeypoints3DDepth()`, the returned points are in base link frame (unless the `localTransform` in CameraModel is Identity, then points would be in camera frame)
https://github.com/introlab/rtabmap/blob/c4d127cae40e8f92db07c05c0dadcaef4cb97d14/corelib/src/util3d_features.cpp#L113

* You have to do `DBDriver::loadNodeData()` after `loadSignature` to load SensorData.
https://github.com/introlab/rtabmap/blob/6dca8ab0f366b2628cafc332ec5ef10869e120b3/corelib/src/DBDriver.cpp#L648

cheers,
Mathieu
