### ISSUE TITLE
Build fails when ZED SDK 4 is installed

### ISSUE THREAD

**Issue by leramleram** [introlab/rtabmap#1013]
The build fails when ZED SDK 4.0 is installed in Ubuntu.

Ubuntu 20.04
ZED SDK version 4.0.1
CUDA 11.8

Here´s a screenshot of the output of make -j6
![image](https://user-images.githubusercontent.com/4068474/231355033-76e80f7a-cd96-4ba8-ba65-1c53c7d5913b.png)

I´ve downgraded the SDK to 3.8 and now it built fine.

**Comment by rob-pointcloud** [comment]
Hi, I can verify that I am seeing the exact same build errors. 
Jetpack 5.1 (Nvidia Jetson Xavier)
Ubuntu 20.04
ZED SDK version 4.0.1
CUDA 11.8

**Comment by matlabbe** [comment]
Fixed in commit above.
