### ISSUE TITLE
Tracking with left image and compute pose with depth filtered by limited distance in stereo mode

### ISSUE THREAD

**Issue by fjlxb** [introlab/rtabmap#1016]
Hi, @matlabbe 

As the title says, I use RTAB-MAP standalone version in Stereo mode and want to track and compute pose with different feature points. I have read your [reply1](http://official-rtab-map-forum.206.s1.nabble.com/Different-cameras-for-depth-image-and-RGB-image-td6154.html#a6158) and [reply2](http://official-rtab-map-forum.206.s1.nabble.com/About-Dotmask-work-td8102.html#a8118), but still can't solve the problems. Here are two questions:

1. I set `Mem/DepthAsMask` to false so that it will use all the feature points while tracking and set `Kp/MaxDepth` or `Vis/MaxDepth` to 3 becauce my stereo camera will be correct within 3 meters. However, left image will has less feature points after this step and RTAB-MAP can't go ahead.

2. I want to change pixels which greater than 3 in depth to zero, however, I can't find where the stereo images generate depth image. 

3. `StereoBM.cpp` is used when generate pointcloud? Why don't use it to compute depth from stereo images?

Thanks for your reading.

**Comment by matlabbe** [comment]
In stereo mode, don't limit the range of the features. Local BA will refine 3D position of the far features. If you are stereo, `Mem/DepthAsMask` won't have any effect (as there is no depth).

If it is just for rendering, look for "Maximum depth" parameter in Preferences->3DRendering panel.

Depending of the stereo camera you are using, there could be a parameter in Preferences->Source to generate disparity from stereo and feed depth directly to rtabmap. StereoBM is used to generate disparity image, that can be then used to generate depth image, that can be then used to generate point cloud. For stereo, we don't do dense disparity computation by default (only for rendering) as it is more costly than sparse disparity computation.

cheers,
Mathieu
