### ISSUE TITLE
rtabmap database post-processing

### ISSUE THREAD

**Issue by alexk1976** [introlab/rtabmap#1040]
Hi Mathieu,
I see 5 possible options/functions for post-processing and map improvement:

1. global bundle adjustment (globalBundleAdjustment)
2. detect more loop-closures (databaseViewer)
3. refine all neighbor links  (databaseViewer)
4. refine all loop closure links  (databaseViewer)
5. update neighbor/loop/landmark covariances (databaseViewer)

Can you recommend proper order of these functions? all them can improve the map or some options are redundant?
what is the reason you separated them in different tools and actually you use different code to go through the map/graph?
thank you

**Comment by matlabbe** [comment]
See http://official-rtab-map-forum.206.s1.nabble.com/rtabmap-post-processing-order-tp9501p9507.html
