### ISSUE TITLE
bug in PreferencesDialog.cpp

### ISSUE THREAD

**Issue by robermorales** [introlab/rtabmap#107]
https://github.com/introlab/rtabmap/blob/master/guilib/src/PreferencesDialog.cpp#L102

```_calibrationDialog(new CalibrationDialog(false, ".", this)),```

```CalibrationDialog::CalibrationDialog(bool stereo, const QString & savingDirectory, bool switchImages, QWidget * parent) :```

Third parameter of `CalibrationDialog` is a `bool`, but that line missed it. It is a QWidget, which should be the fourth parameter. Code is compiling because pointers can be casted to `bool` using `!=0` semantic.

**Comment by matlabbe** [comment]
Thx for reporting! the commit above should fix it.

cheers

**Comment by robermorales** [comment]
Thanks!!
