### ISSUE TITLE
RGB and IMU and 2D lidar

### ISSUE THREAD

**Issue by marisancans** [introlab/rtabmap#1073]
Hello, couldnt find the answer, but would this work on RGB and IMU and 2D lidar. Would like some feedback before I invest time here. In this example [Four Kilometers Walk in Forest](https://www.youtube.com/watch?v=G-5jesjNfLc&list=LL) you are using stereo cameras and it gives really good results, I wonder would it work with a single camera.

The device I use is also handheld similar to the forest example

**Comment by matlabbe** [comment]
> I wonder would it work with a single camera.

No. Look for a VIO (visual inertial odometry) approach or a VSLAM doing VIO.

For the 2D lidar, I guess it would be used just for accumulating point clouds, not for trajectory estimation. If you feed a VIO odometry output to rtabmap, use a [rtabmap_utils/point_cloud_assembler](http://wiki.ros.org/rtabmap_util#rtabmap_util.2Fpoint_cloud_assembler) node to assemble the laser scans based on VIO, then feed the resulting point cloud to rtabmap node, you may be able to reconstruct the environment in 3D.
