### ISSUE TITLE
rtabmap build guilib error

### ISSUE THREAD

**Issue by seonjuno0709** [introlab/rtabmap#1130]
Env: Ubuntu 20.04

Hi i built rtabmap using rtabmap_ros page readme.

This is the instruction I did.
cd ~
git clone https://github.com/introlab/rtabmap.git rtabmap
cd rtabmap/build
cmake ..  [<---double dots included]
make -j6
sudo make install

But i get a error under the content.
[ 42%] Linking CXX shared library ../../bin/librtabmap_core.so
[ 42%] Built target rtabmap_core
[ 43%] Generating qrc_GuiLib.cpp
Scanning dependencies of target stereoEval
/bin/sh: 1: --name: not found
Scanning dependencies of target imagesJoiner
Scanning dependencies of target consoleApp
make[2]: *** [guilib/src/CMakeFiles/rtabmap_gui.dir/build.make:303: guilib/src/qrc_GuiLib.cpp] Error 127
Scanning dependencies of target extractObject
make[1]: *** [CMakeFiles/Makefile2:963: guilib/src/CMakeFiles/rtabmap_gui.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target camera
[ 43%] Building CXX object tools/ImagesJoiner/CMakeFiles/imagesJoiner.dir/main.cpp.o
[ 43%] Building CXX object tools/StereoEval/CMakeFiles/stereoEval.dir/main.cpp.o
[ 43%] Building CXX object tools/ConsoleApp/CMakeFiles/consoleApp.dir/main.cpp.o
[ 44%] Building CXX object tools/ExtractObject/CMakeFiles/extractObject.dir/main.cpp.o
[ 44%] Building CXX object tools/Camera/CMakeFiles/camera.dir/main.cpp.o
[ 44%] Linking CXX executable ../../bin/rtabmap-imagesJoiner
[ 44%] Built target imagesJoiner
[ 44%] Linking CXX executable ../../bin/rtabmap-camera
[ 44%] Built target camera
[ 45%] Linking CXX executable ../../bin/rtabmap-stereoEval
[ 45%] Built target stereoEval
[ 46%] Linking CXX executable ../../bin/rtabmap-console
[ 46%] Built target consoleApp
[ 46%] Linking CXX executable ../../bin/rtabmap-extractObject
[ 46%] Built target extractObject
make: *** [Makefile:152: all] Error 2

How can i solve this problem?
Thank you.

**Comment by matlabbe** [comment]
`/bin/sh: 1: --name: not found` not sure from what this coming from. Can you show output of the cmake log? Also can you show log of `make VERBOSE=1`?

Based on [CI](https://github.com/introlab/rtabmap/actions/runs/6126762436/job/16631413777), it should build on ubuntu 20.04 with default binaries of the dependencies.
