### ISSUE TITLE
window build and meet exe error

### ISSUE THREAD

**Issue by wangjinhoon** [introlab/rtabmap#1140]
I followed the installation process on Windows and executed the bin\RTABMap.exe file. However, I'm encountering this error. What could be wrong?

![image](https://github.com/introlab/rtabmap/assets/83506637/97355292-2e49-4565-9a67-e610f182f60d)

it's mean "The procedure entry point 'z_inflatelnit2_' could not be found in the DLL C:\Qt\6.2\msvc2019\bin\Qt6Svg.dll."

Is there any way to solve this?

help me, thank

**Comment by matlabbe** [comment]
> I followed the installation process on Windows

Which one? do you use the binaries? compiling from source? On windows, we now recommend to build with vcpkg.

**Comment by wangjinhoon** [comment]
Thank you for your response.
I was able to build the executable using vcpkg. 
However, I am having trouble configuring the parameters for the D435i. 
What could be the issue?
![image](https://github.com/introlab/rtabmap/assets/83506637/090efea3-a50d-4461-b403-5c8013be3156)
thank

**Comment by matlabbe** [comment]
You would have to add [realsense2](https://github.com/microsoft/vcpkg/blob/accd79817981f1ce00c6a4164aecf2b2ac699823/ports/rtabmap/vcpkg.json#L117) option when configuring vcpkg build.

**Comment by wangjinhoon** [comment]
Is this right?
```
vcpkg install rtabmap[realsense2] --triplet x64-windows --clean-after-build
```

i try it but i have same issue
thank

**Comment by matlabbe** [comment]
Humm, just tried:
```
cd vcpkg
git pull
vcpkg install rtabmap[realsense2] --clean-after-build --recurse
```
and it seems okay:

![image](https://github.com/introlab/rtabmap/assets/2319645/a3b0dafe-19ad-47c0-a81e-cac98221e33b)

**Comment by wangjinhoon** [comment]
I couldn't solve this problem, but when I tried on a different computer, it worked. 

Thank you for your response!!
