### ISSUE TITLE
How to receive real-time odometry in Windows(OS)

### ISSUE THREAD

**Issue by wangjinhoon** [introlab/rtabmap#1158]
Hello, thank you for your help.
I want to receive real-time odometry estimated by RTAB-Map in localization mode

first, i play slam mode and got rtabmap.db 

second, i played localization mode with rtabmap.db.

In localization mode, I initially thought that the origin of the point cloud map would be the starting position of the camera in slam mode. However, when I output the odometry in localization mode, the current camera position was displayed as the origin.

I've taken "return_pose *=t" from Odometry.cpp, which is around the 900th row.
![Untitled (1)](https://github.com/introlab/rtabmap/assets/83506637/e5eb593e-b2ae-4ed8-bc12-618e9d952133)

If i want to know the current position relative to the map, what part should I output?

Thank you. Have a great day."

**Comment by matlabbe** [comment]
Rtabmap will publish `localization_pose` topic once every localization update (default 1Hz). If you need higher framerate, like at the same frame rate than odometry, you may subscribe to odometry topic and TF, then transform the odometry topic into map frame and republish it. You may also just use TF and [lookupTransform](http://docs.ros.org/en/noetic/api/tf/html/c++/classtf_1_1Transformer.html#ac59f0533c82c2ab9b834039d4cf3180b) between `map` and `odom.child_frame_id` frames when you receive a new odometry topic.

**Comment by wangjinhoon** [comment]
Thank you for your response. I will revisit after examining the localization_pose once.

**Comment by wangjinhoon** [comment]
Thank you for your response. I will revisit after examining the localization_pose once.

**Comment by wangjinhoon** [comment]
If any issues arise, I will reopen it. Thank you.
