### ISSUE TITLE
Recommended Raspberry Pi for running this?

### ISSUE THREAD

**Issue by kenhuang1964** [introlab/rtabmap#1174]
Would a 2GB raspberry pi 4B be sufficient or perhaps 4GB? If not, what are some alternatives?

**Comment by matlabbe** [comment]
At least 4 GB, but don't expect high FPS when running the full rtabmap stack on it. If you use only rtabmap node (no VO) at 1 Hz, it can work correctly on RPI4.

**Comment by miku54** [comment]
> At least 4 GB, but don't expect high FPS when running the full rtabmap stack on it. If you use only rtabmap node (no VO) at 1 Hz, it can work correctly on RPI4.

How do I set rtabmap node (no VO) at 1 Hz?

**Comment by matlabbe** [comment]
Just launch `rtabmap` node, by default it is running at 1Hz already. The "no VO" part is not using `rgbd_odometry` or `stereo_odometry` nodes.
