### ISSUE TITLE
iOS - voxelize point cloud

### ISSUE THREAD

**Issue by jtabraham123** [introlab/rtabmap#1202]
Hello, I am trying to stream point cloud from ios device, and i want it to be low size data. I am currently sending the cloud from scene.cpp in the addMesh function. Is there a setting that i can do to voxelize the point cloud live or filter the close together points? What would be the best way/practice to stream the large point cloud?

**Comment by matlabbe** [comment]
You can increase the decimation factor for the live point cloud in the App's options. If you prefer voxel filter, you can do `rtabmap::util3d::voxelize(...)` of the `mesh.cloud` before sending it.
