### ISSUE TITLE
UserData in Link Table

### ISSUE THREAD

**Issue by 360wcui** [introlab/rtabmap#1206]
Hello,  I notice that there are some user_data in Link table of rtabmap.db.   What does the data in that column contain?   I am able to read the UserData from Data table, but why we have another user_data column in Link table?  Any insight would be greatly appreciated. 

<img width="647" alt="Screenshot 2024-01-25 at 5 27 04 PM" src="https://github.com/introlab/rtabmap/assets/12385457/4c9965bd-0b9e-42b3-887c-b069d7151918">

**Comment by 360wcui** [comment]
Another note.  The size of user_data in the two tables is different.  
<img width="659" alt="Screenshot 2024-01-25 at 5 30 45 PM" src="https://github.com/introlab/rtabmap/assets/12385457/0082d698-84f7-493d-afd7-e545cdb9ca25">

**Comment by matlabbe** [comment]
If you are using laser scans, the `Link`'s `user_data` would be updated on proximity detection by default following this parameter:
```
Param: RGBD/ScanMatchingIdsSavedInLinks = "true"           [Save scan matching IDs from one-to-many proximity detection in link's user data.]
```
That is mostly used for debugging proximity detection and visualize in `rtabmap-databaseViewer` the scans used for it. The usage of `user_data` in `Link` is not exposed, in contrast to one in `Data`.

Another parameter than can affect `user_data` in `Data` table, though not enabled by default:
```
Param: RGBD/GoalsSavedInUserData = "false"                 [When a goal is received and processed with success, it is saved in user data of the location with this format: "GOAL:#".]
```
Examples of using `user_data`:
 * Saving WiFi signal strength: http://wiki.ros.org/rtabmap_ros/Tutorials/WifiSignalStrengthMappingUserDataUsage
 * Saving objects detected and there relative position from the base frame: https://github.com/introlab/rtabmap_ros/blob/7845e530959e09cc4f6d10d69cca766c9d1ff775/rtabmap_demos/src/SaveObjectsExample.cpp#L80-L95
