### ISSUE TITLE
Generate obj,  mtl, and texture jpg incrementally

### ISSUE THREAD

**Issue by 360wcui** [introlab/rtabmap#1208]
Hello,  

Can we incrementally save the mesh model (obj, mtl, and jpg) of the 3D map instead of the point cloud from mapData or other sources?  I like the way how the iPhone version renders the mesh model in real time.  

Any suggestions would be greatly appreciated.    Thank you.

**Comment by matlabbe** [comment]
With standalone or rtabmap_viz in ros, it is possible to show meshes in real-time like the iPhone app does. Open Preferences and check this box:
![image](https://github.com/introlab/rtabmap/assets/2319645/960b3397-b985-422b-8bde-621a4062a5a9)

This only works for RGB-D data. You may increase the decimation to avoid adding too many polygons.

In ROS, outside rtabmap_viz, there is no way I am aware to do that with data from MapData topic.

**Comment by 360wcui** [comment]
Thank you!  Are the mesh models (e.g., obj, mtl) saved anywhere for rtabmap_viz to consume or which code snippet does online meshing?

**Comment by matlabbe** [comment]
The meshes are kept in renderer memory. To export the mesh, you would use File->Export Clouds... and check Meshing box.

The code creating the meshes online is here:
https://github.com/introlab/rtabmap/blob/master/guilib/src/MainWindow.cpp#L3796-L3866

**Comment by 360wcui** [comment]
Thank you!
