### ISSUE TITLE
Can RTABMAP load images obtained from kinect?

### ISSUE THREAD

**Issue by ss780217** [introlab/rtabmap#122]
The input is only the device or database recorded before.
Can I feed the color map and depth map series obtained from kinect to the program?

**Comment by matlabbe** [comment]
Do you mean a directory of color images (any image format) and a directory of depth registered images (PNG)? Yes, select "Images" driver after RGB-D source has been selected: 
![untitled](https://cloud.githubusercontent.com/assets/2319645/19196226/aef5e9ca-8c82-11e6-927a-45cff4b61a21.jpg)

cheers
