### ISSUE TITLE
Landmarks ignores will cause crashing in optimizer

### ISSUE THREAD

**Issue by hellovuong** [introlab/rtabmap#1227]
Hello, 
If I use `Optimizer/LandmarksIgnored ` to true in a map built with LandmarksIgnored false. I received this error in g2o:

![image](https://github.com/introlab/rtabmap/assets/25075078/0d40db90-7344-4b33-85c7-2c5a92218e76)

Can you help me debug it? I can make PR to fix it, but now I am struggling to proceed.
Additional question if we set `Optimizer/LandmarksIgnored ` to true does it mean that there landmarks will not be used at all for localization? 
Thank you!

**Comment by hellovuong** [comment]
If I use GTSAM then this is the error
`[ INFO] (2024-02-29 18:09:59.549) Rtabmap.cpp:2992::process() Landmark 400 observed again! Seen the first time by node 112.
[FATAL] (2024-02-29 18:09:59.549) OptimizerGTSAM.cpp:144::optimize() Condition (uContains(poses, rootId)) not met!
terminate called after throwing an instance of 'UException'
  what():  [FATAL] (2024-02-29 18:09:59.549) OptimizerGTSAM.cpp:144::optimize() Condition (uContains(poses, rootId)) not met!`

**Comment by matlabbe** [comment]
Humm, I may know what is going on. The out of bound error may happen here:
https://github.com/introlab/rtabmap/blob/33b875ecbf730ffbfabc4a4160b2ca19a3dbad9b/corelib/src/Rtabmap.cpp#L3542

Hypotheses:
 * The map has been created with landmarks and `Optimizer/LandmarksIgnored=false`, so the optimized graph will contain landmark poses.
 * In localization mode, after setting `Optimizer/LandmarksIgnored=true`, the landmark links are somewhat still used but internal graph optimization is ignoring them, so after local graph optimization the landmarks are ignored and `optPoses` won't contain landmark ids anymore. 

Possible solution could be to add `&& !_graphOptimizer->landmarksIgnored()` to this `if`:
https://github.com/introlab/rtabmap/blob/33b875ecbf730ffbfabc4a4160b2ca19a3dbad9b/corelib/src/Rtabmap.cpp#L3134

I'll try to reproduce in simulation and test if the above could fix it.
