### ISSUE TITLE
rtabmap parameter problem in 0.21.4

### ISSUE THREAD

**Issue by qetuo105487900** [introlab/rtabmap#1236]
i see rtabmap_ros/rtabmap_demos/demo_husky.launch

there are some parameter can not found in RTAB-Map:               0.21.4
but i found some similar parameter, are they same parameter ?

Icp/PMOutlierRatio vs Icp/OutlierRatio
Icp/PointToPlaneNormalK vs Icp/PointToPlaneK

thanks!

**Comment by matlabbe** [comment]
You can use the old names and they will work, but you will have a warning message to know to which new ones you should use.

The new name for `Icp/PMOutlierRatio` is `Icp/OutlierRatio`:
https://github.com/introlab/rtabmap/blob/57b4954cb355efe2dc8f5035896d82f7977868bc/corelib/src/Parameters.cpp#L257

For `Icp/PointToPlaneNormalK`, I think there is an error, it should indeed be `Icp/PointToPlaneK`. The default is 5 while the husky demo set it to 10, maybe why that bug passed unnoticed. I [fixed](https://github.com/introlab/rtabmap_ros/commit/665735663ef7bf029c11c599c06a1fd727299e0c) the typo.

**Comment by qetuo105487900** [comment]
@matlabbe , thanks!
