### ISSUE TITLE
Empty Gridmap and Octomap with recent integration of Gridmap

### ISSUE THREAD

**Issue by FlorianMehnert** [introlab/rtabmap#1238]
Hi there,

with the integration of `grid_map_integration` into the master #1180 neither Octomap or Gridmap generation work anymore for me anymore. Gridmap publishes Maps containing only Nan values and Octomap publishes empty maps.

Do you have any idea on why this could happen?

As a side effect RviZ is crashing with: `catkin_ws/src/grid_map/grid_map_core/src/GridMap.cpp:45: void grid_map::GridMap::setGeometry(const Length&, double, const Position&): Assertion `length(0) > 0.0' failed.`

**Comment by matlabbe** [comment]
Just tried the latest rtabmap noetic binary releases 0.21.4 with this [example](http://wiki.ros.org/rtabmap_ros#rtabmap_ros.2Fnoetic_and_newer.Stereo_mapping):
```
roslaunch rtabmap_demos demo_stereo_outdoor.launch rviz:=true
rosbag play --clock stereo_outdoorA.bag
```

and I can get the three topics at the same time:
![image](https://github.com/introlab/rtabmap/assets/2319645/1aeabd00-ac7d-49de-803d-90140d172e6c)

I see grid_map is built from source, are you also using rtabmap from source?

**Comment by FlorianMehnert** [comment]
Yes I was using rtabmap from source. After 2 days of doing nothing everything works :sweat_smile: 
Maybe there was an issue with the OAK camera I am using or something else :)
