### ISSUE TITLE
many nodes are not optimized (negative weight) after mapping

### ISSUE THREAD

**Issue by alexk1976** [introlab/rtabmap#1240]
I just noticed that many nodes are not in the optimized graph after mapping (have negative weight) when most of the nodes are ok. 
Since we didnt use LTM/WM (TimeThr=0 and MemortTh = 0) i wondering why it happens and how to fix it. 
I tried to re-optimize using databaseViewer but it doesnt help.

**Comment by matlabbe** [comment]
These nodes are those ignored by `RGBD/LinearUpdate` and `RGBD/AngularUpdate` parameters. For example, if the robot is not moving (i.e. linear motion < `RGBD/LinearUpdate`), the node will be set with a negative weight and ignored from the WM / optimized pose graph. It is still saved in the database by default with `Mem/NotLinkedNodesKept=true` for debugging purpose.

If you want them in the WM or graph, set `RGBD/LinearUpdate=0`, or if you don't want to see them in the database, set `Mem/NotLinkedNodesKept=false`.
