### ISSUE TITLE
what are these lines mean in graph view ?

### ISSUE THREAD

**Issue by qetuo105487900** [introlab/rtabmap#1243]
![Screenshot from 2024-03-15 16-41-32](https://github.com/introlab/rtabmap/assets/67533597/cde02ac8-d5f2-48c8-a916-c403f3b0d5b9)
i know blue line is my slam path 
but how about the yellow and the red lines mean?

**Comment by matlabbe** [comment]
Yellow is proximity detection (or local loop closure detection), red is global loop closure detection. If you right-click on the view, there is a menu option showing the different link colors (that can be changed). To know more about those links, see section 3.4 of this paper: [RTAB-Map as an Open-Source Lidar and Visual SLAM Library for Large-Scale and Long-Term Online Operation](https://introlab.3it.usherbrooke.ca/mediawiki-introlab/images/7/7a/Labbe18JFR_preprint.pdf).

**Comment by qetuo105487900** [comment]
@matlabbe , thanks!!!!
