### ISSUE TITLE
how to merge multiple times SLAM db file with rgbd camera, 3d lidar and odometry ?

### ISSUE THREAD

**Issue by qetuo105487900** [introlab/rtabmap#1244]
"Is it possible to merge multiple times SLAM db file with rgbd camera, 3d lidar and odometry ?

i see 
https://github.com/introlab/rtabmap/tree/master/archive/2022-IlluminationInvariant
can merge multiple times map together, but it only for camera.

But i SLAM with rgbd camera, 3d lidar and odometry , so how to modify the parameter in .sh file that provide from 
https://github.com/introlab/rtabmap/tree/master/archive/2022-IlluminationInvariant/scripts/reprocess_maps_all.sh
https://github.com/introlab/rtabmap/tree/master/archive/2022-IlluminationInvariant/scripts/reprocess_maps.sh
https://github.com/introlab/rtabmap/tree/master/archive/2022-IlluminationInvariant/scripts/run_merge.sh
and other relative file

**Comment by qetuo105487900** [comment]
i use rgbd-camera 3d lidar and odometry

**Comment by matlabbe** [comment]
You can do:
```
rtabmap-reprocess "map1.db;map2.db" combined_maps.db 
```

**Comment by qetuo105487900** [comment]
@matlabbe , thanks!!!!!!!!!!

**Comment by qetuo105487900** [comment]
@matlabbe , sorry. Should I need to start at the same start point ?

**Comment by matlabbe** [comment]
No, you don't need to, but the robot should traverse at some point same locations than in previous session, ideally with same point of view so that a loop closure can be detected. It is then easier to just start from the same position.

**Comment by qetuo105487900** [comment]
ok, i see. thank you so much
