### ISSUE TITLE
Wiki: Installation iOS - add App Store link

### ISSUE THREAD

**Issue by muescha** [introlab/rtabmap#1258]
where:

- Wiki - Installation - iOS ( https://github.com/introlab/rtabmap/wiki/Installation#ios )

Current:

- only local install is described

Expected:

- link to App Store ( which is only hidden on homepage at section Install https://introlab.github.io/rtabmap/#install as a link behind a icon  - but not available as textual information)

https://apps.apple.com/ca/app/rtab-map-3d-lidar-scanner/id1564774365

**Comment by matlabbe** [comment]
Indeed! I updated the wiki. Thanks to point out!
