### ISSUE TITLE
Coordinate Frame for iPad Pro

### ISSUE THREAD

**Issue by ary-dz** [introlab/rtabmap#1271]
If I am using RTAB on an iPad Pro 11 inch. What are the coordinates produced relative to (what is 0,0,0 x,y,z)? Is it relative to the:

1. Camera module
2. LIDAR sensor
3. Middle of the iPad

We have code that takes the coordinates produced from movement and have to map the location of an object attached to the iPad (small changes in distance matter).

**Comment by matlabbe** [comment]
The pose is the default one from ARKit, which is the pose of the RGB camera.
