### ISSUE TITLE
Crash when loading Depth Distortion model (Windows 10)

### ISSUE THREAD

**Issue by matlabbe** [introlab/rtabmap#128]
From post: http://official-rtab-map-forum.67519.x6.nabble.com/Unusual-curvature-in-Point-Cloud-td1949.html

This crash is not observed on Mac OS X or Linux. I tried different Eigen versions (3.2.7 and 3.2.8) on Windows and they both crash. The bug may come from [eigen_extensions.h](https://github.com/introlab/rtabmap/blob/master/corelib/src/clams/eigen_extensions/eigen_extensions.h).

**Comment by antoniodepth** [comment]
Thank you for the issue. I'm waiting for the solution.
