### ISSUE TITLE
Could not find .cpp files of src folder in docker image

### ISSUE THREAD

**Issue by SaiPuneeth666** [introlab/rtabmap#1291]
Hi,
I am using[ this image ](https://github.com/introlab/rtabmap_ros/blob/fd8b4f46500807d2421ed00ed422077544d83966/docker/noetic/superpoint/Dockerfile#L7) . I wanted to edit SuperPoint.cc files in rtabmap location https://github.com/introlab/rtabmap/blob/master/corelib/src/superpoint_torch/SuperPoint.cc. 
I went through the complete image in every folder. Could you help me pinpoint the location if I have missed it somewhere. 

Thanks

**Comment by matlabbe** [comment]
If you want to keep the source code in the image, remove this [line](https://github.com/introlab/rtabmap_ros/blob/fd8b4f46500807d2421ed00ed422077544d83966/docker/noetic/superpoint/Dockerfile#L123) and this [line](https://github.com/introlab/rtabmap_ros/blob/fd8b4f46500807d2421ed00ed422077544d83966/docker/noetic/superpoint/Dockerfile#L145).

cheers,
Mathieu
