### ISSUE TITLE
Sample Dataset not Found in Tutorial of Loop-closure-detection 

### ISSUE THREAD

**Issue by Tesla-SHT** [introlab/rtabmap#1317]
https://github.com/introlab/rtabmap/wiki/Loop-closure-detection
In the part of "Setup the source of the camera. ", the link of the sample dataset is invalid: https://raw.githubusercontent.com/introlab/rtabmap/master/bin/data/samples.zip

**Comment by matlabbe** [comment]
Thx for reporting, I fixed the broken link.
