### ISSUE TITLE
Outdoor Settings

### ISSUE THREAD

**Issue by th00tames1** [introlab/rtabmap#1345]
Hi, I found the demo video link of Outdoor stereo SLAM with RTAB-Map: https://youtu.be/qpTS7kg9J3A
like this video, I tried to do the same work outside with my iPad. 

But it couldn't scan the shrub and vegetation normally. It only scanned the ground.

![IMG_0003](https://github.com/user-attachments/assets/62bcfdae-c4cc-480b-8f97-9220d3b0955c)

Is there any suggested configuration for outdoor and plant scanning?
Thanks.

**Comment by matlabbe** [comment]
You may try decreasing Depth Confidence in the settings. Here two comparisons between high (left) and medium (center and right):

![Screenshot 2024-09-22 at 11 34 43 AM](https://github.com/user-attachments/assets/744f07fe-ba4a-4d5a-8cde-f4f343e1eb30)
![Screenshot 2024-09-22 at 11 34 05 AM](https://github.com/user-attachments/assets/1877ca55-5e5d-4827-9c09-16bb5a24aaa4)

**Comment by th00tames1** [comment]
Thanks. Closing the issue
