### ISSUE TITLE
[BUILD] SensorCaptureThread.cpp <pcl/io/io.h> deprecated on newer PCL versions

### ISSUE THREAD

**Issue by 4jakers18** [introlab/rtabmap#1388]
[io.h no longer is installed under pcl/io/](https://pointclouds.org/documentation/io_2include_2pcl_2io_2io_8h_source.html) in newer versions of PCL compiled from source. Proposed patch on corelib/src/SensorCaptureThread.cpp: 

Replacing `<pcl/io/io.h>` with `<pcl/common/io.h>`. I've successfully build and tested this change already on master and noetic-devel.

```
diff --git a/corelib/src/SensorCaptureThread.cpp b/corelib/src/SensorCaptureThread.cpp
index fb931bef..c4ad71e4 100644
--- a/corelib/src/SensorCaptureThread.cpp
+++ b/corelib/src/SensorCaptureThread.cpp
@@ -45,7 +45,7 @@ SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #include <rtabmap/utilite/ULogger.h>
 #include <rtabmap/utilite/UStl.h>
 
-#include <pcl/io/io.h>
+#include <pcl/common/io.h>
 
 namespace rtabmap
 {

```

Ubuntu 20.04, x86_64.

**Comment by matlabbe** [comment]
Great, thank you, I created a PR https://github.com/introlab/rtabmap/pull/1390
