### ISSUE TITLE
IOS: difficulty recognicing Apriltags/Aruco markers. 

### ISSUE THREAD

**Issue by APOS80** [introlab/rtabmap#1396]
Hello

The new version seems to have a hard time recognising markers.

It can detect them at first but then it cant.

**Comment by APOS80** [comment]
It seems to be the Apriltags thas has a problem being recognised.

**Comment by matlabbe** [comment]
Do you see a lot of "Rejected" messages? I just created this issue that may be related: https://github.com/introlab/rtabmap/issues/1401

**Comment by APOS80** [comment]
Yes, there’s a bunch of them.
