### ISSUE TITLE
IOS: extra optimisations doesn’t stack

### ISSUE THREAD

**Issue by APOS80** [introlab/rtabmap#1402]
Besides “standard optimisation” you can add “advanced” optimisations.

But the advanced optimisations doesn’t seems to be added, only one seems to be in affect at a time.

Choosing “Detect more loop closures” gives an improved result but when “Bundle adjustment” is chosen I get another result without the previous improvement. Choosing the previous setting takes me back to the first improvement.

Maybe I’m missing something. Is the advanced settings already applied in Standard optimisation?

**Comment by matlabbe** [comment]
The post processing options are defined here:
https://github.com/introlab/rtabmap/blob/a613998652d668cc36b9c4e34b1dbd7a305f0a79/app/android/jni/RTABMapApp.cpp#L3703-L3800

with `approach==-1` the "Standard Optimization" approach: it does "Detect more loop closures" -> "Graph optimization" -> "Polygon cleanup" -> "Fast gain compensation". Except for "Detect more loop closures", the post processing options are ephemeral, meaning if you reload the database, they won't be there. For example, "bundle adjustment" would be reverted to standard graph optimization after reloading the database or selecting another post-processing option affecting graph optimization. Same thing for gain compensation, it is not saved in database. 

The only way to save those optimizations is to "Assemble" the map and save it, then the optimized/exported map will contain all optimizations, even on reload.

**Comment by APOS80** [comment]
So bundle adjustment disregards standard graph optimisation?

**Comment by matlabbe** [comment]
It would use the current optimized poses to start the optimization from. Bundle adjustment is actually an improved version of the standard graph optimization (odometry links + loop closure links) by adding 2D-3D feature constraints in the optimization. Pure bundle adjustment would only care about the camera poses and the 2D-3D features, while in our version we also keep the odometry contraints and loop closure contraints between the camera poses.
