### ISSUE TITLE
Rejected loop closure : Not enough features in images (old=0, new=181, min=20)

### ISSUE THREAD

**Issue by thomas8329** [introlab/rtabmap#1414]
Hello, 

I keep getting this warning : 
Rtabmap.cpp:3036::process() Rejected loop closure 104 -> 1110: Not enough features in images (old=0, new=181, min=20).
Values are changing but the problem is still the same. Old is always 0 even if the mapping is working.
I tried adding or replacing some args in my launchfile, but nothing.

None of my loop closure aren't rejected.

Thanks for your help
(@matlabbe)

**Comment by matlabbe** [comment]
Maybe 104 doesn't have features. If you move and the old signature is always empty (even if you know that it shouldn't), there could be an issue.
