### ISSUE TITLE
Windows: RTab shuts down when klicking "stop".

### ISSUE THREAD

**Issue by APOS80** [introlab/rtabmap#1416]
I make a new DB and start scanning, when done i klick "stop" and after a while RTab shuts down and i need to restart.

The DB with the data is gone.

**Comment by APOS80** [comment]
Changed DB settings and it did work better.

But theres no file to be found and theres no SAVE function.

**Comment by matlabbe** [comment]
There should be a `tmp` database file at least in Your Documents/RTAB-Map folder, that could be recovered. Which camera driver are you using? Which windows version? There could be an issue when closing the driver making rtabmap crashes.

**Comment by APOS80** [comment]
Drivers for Realsense d400

after I changed db settings to file it has worked
