### ISSUE TITLE
No odometry sensor driver for Realsense?

### ISSUE THREAD

**Issue by APOS80** [introlab/rtabmap#1417]
Hello

I miss a driver for the built in IMU I my D455f,
Can it be added?

Windows

**Comment by matlabbe** [comment]
Does D455f provide visual odometry? The Odometry Sensor under Soruce panel would be only used for sensors/camera drivers that already provide visual odometry (e.g., ZED camera or T265 camera). If you search rtabmap's odometry settings, open Advanced settings, then click on Odometry. RTAB-Map's visual odometry will be used by default when the camera drivers don't provide any odometry.

The IMU from D455f would be already published when using Realsense2 driver, unless the API is different than with D435i or D455 series.

**Comment by APOS80** [comment]
Okay.
