### ISSUE TITLE
Tango cannot save or export.

### ISSUE THREAD

**Issue by jje8910** [introlab/rtabmap#146]
I try rtabmap in Tango.
I download the apk in google playstore.
But when I try to save or export, ""Failed to rename temporary database from \"%s\" to \"%s\"."" message occurs, and I cannot save or export the data.
Please give me a guide

**Comment by matlabbe** [comment]
Are you on the Google tablet or Phab2Pro? It seems that the app cannot write on the SD-CARD.

**Comment by jje8910** [comment]
I'm on Google Tango tablet. But the other app(like RoomScanner or ParaView Tango and so on) can write on the SD-CARD fine. 
Could you try it on Google Tango tablet?

**Comment by jje8910** [comment]
I test with Google Tango tablet. Now save or export is okay. Thank you
