### ISSUE TITLE
Tango: crash when activating "HD Mode" on Phab 2 Pro

### ISSUE THREAD

**Issue by matlabbe** [introlab/rtabmap#147]
from https://github.com/introlab/rtabmap/issues/143#issuecomment-261006044

**Comment by eric-schleicher** [comment]
For clarity what does HD mode enable?

**Comment by matlabbe** [comment]
HD mode uses the full resolution of the color camera for texture. In SD Mode (default), the resolution is divided by 2 to save memory. For example on Google Development Kit, max resolution is 1280x720, so by default 640x360 images are saved. For Phab2Pro, the native resolution of the color camera is 1920x1080, so by default 960x540 images are saved.

**Comment by matlabbe** [comment]
Fixed by 0.11.14.
