### ISSUE TITLE
rtabmap-databaseViewer 5MappingSessions_OnlineConstraint700ms.db thorws exception

### ISSUE THREAD

**Issue by K0stIa** [introlab/rtabmap#150]
Getting this exception while running rtabmap-databaseViewe from example.

> [ INFO] (2016-12-02 16:55:48.790) DBDriverSqlite3.cpp:344::connectDatabaseQuery() Using database "/home/kostia/data/5MappingSessions_OnlineConstraint700ms.db" from the hard drive.
[ INFO] (2016-12-02 16:55:48.790) DBDriverSqlite3.cpp:382::connectDatabaseQuery() Database version = 0.0.0
[ INFO] (2016-12-02 16:55:48.790) DatabaseViewer.cpp:1135::updateIds() Loading all IDs...
[ INFO] (2016-12-02 16:55:50.358) DatabaseViewer.cpp:1253::updateIds() Loaded 2256 ids, 2074 poses and 2515 links
[ INFO] (2016-12-02 16:55:50.358) DatabaseViewer.cpp:1255::updateIds() Update database info...
[FATAL] (2016-12-02 16:55:52.484) CameraModel.cpp:79::CameraModel() Condition (cx > 0.0 || imageSize.width>0) not met! [cx=0,000000 imageSize.width=0]
terminate called after throwing an instance of 'UException'
  what():  [FATAL] (2016-12-02 16:55:52.484) CameraModel.cpp:79::CameraModel() Condition (cx > 0.0 || imageSize.width>0) not met! [cx=0,000000 imageSize.width=0]
Aborted (core dumped)

**Comment by matlabbe** [comment]
Hi, thx for reporting. This is now fixed by https://github.com/introlab/rtabmap/commit/d2287ab9f4cb8044e8e2f6962d63128e70defadc

cheers,
Mathieu
