### ISSUE TITLE
Cannot run LoopClosure algorithm for set of images

### ISSUE THREAD

**Issue by K0stIa** [introlab/rtabmap#151]
Cannot run LoopClosure detection from the directory with images as it is stated in the tutorial.

https://github.com/introlab/rtabmap/wiki/Loop-closure-detection

**Comment by matlabbe** [comment]
The tutorial is updated. The steps should match now the latest versions.

cheers,
Mathieu

**Comment by K0stIa** [comment]
hey matlabbe,

thanks for updating tutorial, but there is still one more problem with it. 
After I selected Images and clicked "Start" button system wants me to do camera calibration
and camera calibration window pops up. If I refuse to use it, the system does not proceed further.

**Comment by matlabbe** [comment]
Normally when loading [settingsAppearanceDemo.ini](https://raw.githubusercontent.com/wiki/introlab/rtabmap/doc/Tutorials/ProcessADataSet/settingsAppearanceDemo.ini), RGB-D SLAM should be disabled. If not, uncheck RGB-D SLAM here:
![untitled](https://cloud.githubusercontent.com/assets/2319645/20927743/e9eac39c-bb90-11e6-9e8f-ae41350740f6.jpg)

cheers

**Comment by K0stIa** [comment]
Alright, RGB-D SLAM was not disabled. It works well now.

Thanks, Mathieu.
