### ISSUE TITLE
realloc(): invalid pointer

### ISSUE THREAD

**Issue by maohaihua** [introlab/rtabmap#156]
../rtabmap-master/bin/rtabmap
*** Error in `../rtabmap-master/bin/rtabmap': realloc(): invalid pointer: 0x0000007fa2b59800 ***
Aborted

**Comment by maohaihua** [comment]
seem no effect after reading listed below
https://github.com/introlab/rtabmap/issues/124

**Comment by maohaihua** [comment]
vtk7.1 pcl1.8 opencv3.1 on jetson tx1 ubuntu16.04

**Comment by maohaihua** [comment]
no zed ,

**Comment by maohaihua** [comment]
solved with rebuild with Qt5 for pcl,opencv

**Comment by QinZiwen** [comment]
@maohaihua How to solve the problems, can you share the tutorial?
