### ISSUE TITLE
How to export to Sketchfab ?

### ISSUE THREAD

**Issue by Kuranes** [introlab/rtabmap#164]
I see it's in the code but don't seem to be able to find it in the tango app, nor in the windows app ?

**Comment by matlabbe** [comment]
The Tango release with sketchfab (0.11.14) is currently on hold until I can test it on Phab2Pro (as it crashes for unknown reason).

**Comment by Kuranes** [comment]
thanks !
( btw, great piece of work, thanks for sharing)

**Comment by matlabbe** [comment]
Closing this issue as 0.11.14 is now online on google play store.
