### ISSUE TITLE
Postprocessing Error [ OptimizerCVSBA.cpp:156::rtabmap::OptimizerCVSBA::optimizeBA()]

### ISSUE THREAD

**Issue by eric-schleicher** [introlab/rtabmap#165]
A Capture with Phab2 Pro with RTAB-MAP 0.11.13

Choose Post process with the following options.
![image](https://cloud.githubusercontent.com/assets/8261783/22573017/b92af404-e95b-11e6-97fe-3c4d96c6f949.png)

It runs but at the very end of the run i see the following error in the console.

Afterware it does appear as if changes have been made in the cloud

```
SBA: sba_motstr_levmar_x() cannot solve a problem with fewer measurements [8732] than unknowns [12245]
[ERROR] (2017-02-02 15:16:05) OptimizerCVSBA.cpp:156::rtabmap::OptimizerCVSBA::optimizeBA() Running SBA... error! C:\workspace\cvsba-1.0.0\src\cvsba.cpp:233: error: (8888) Error occured during Sba optimization in function Sba::run
```

Is this a legitimate error?  this behavior is consistent with other phab 2 captures i've made.

**Comment by matlabbe** [comment]
cvsba requires that there are visual constraints (visual feature correspondences) between all images linked in the map. If not, there will be more unknowns than measurements. g2o's SBA is more robust to this, as it can use pure odometric links (without visual correspondences) of the map's graph in its optimization.

**Comment by eric-schleicher** [comment]
Thank you!  I will try this.
