### ISSUE TITLE
ZED camera SVO file input with standard sensing mode fatal error

### ISSUE THREAD

**Issue by mtee** [introlab/rtabmap#192]
Whenever I select a ZED SVO file as a source and leave the sensing mode as Standard the program crashes upon start. The error I see in the console is

> "CameraStereo.cpp:824::CameraStereoZed() Condition (sensingMode_ >= sl::SENSING_MODE_FILL && sensingMode_ <sl::SENSING_MODE_LAST) not met!"

Which makes me wondering if we only can use FILL mode with the SVO input, since the error does not occur when the sensing mode is set to FILL. ZED sdk version is 2.0, OS is linux mint 18.

**Comment by matlabbe** [comment]
I updated the code, there was a missing change for the SVO constructor interface (ZED SDK 2.0 has changed order of the sensing enum).

**Comment by matlabbe** [comment]
You may want this fix too for SVO input: https://github.com/introlab/rtabmap/commit/474011033b9742dcc797d5b39ace07ccd2812b18
otherwise the scale is wrong!
