### ISSUE TITLE
(ZED, standalone) Fatal error when starting mapping with odometry provided by ZED SDK 2.0

### ISSUE THREAD

**Issue by mtee** [introlab/rtabmap#197]
When I select ZED SDK as source and tick the "Use ZED visual odometry" checkbox, the "Test" mode in the settings as well as Test Odometry work fine, however rtabmap crashes with the fatal error, when I start the actual mapping:

[FATAL] (2017-05-18 12:15:58.013) OdometryEvent.h:70::OdometryEvent() Condition (uIsFinite(covariance.at<double>(0,0)) && covariance.at<double>(0,0)>0) not met! [Transitional variance should not be null! (set to 1 if unknown)]

Everything works fine when I don't use the ZED visual odometry though.

**Comment by matlabbe** [comment]
Thx for reporting, the commit above should fix the crash. However, you may see tracking lost after 30-40 sec as zed sdk starts to send pose_confidence == -1 (with no valid pose). Not sure what -1 means as in [documentation ](https://www.stereolabs.com/developers/documentation/API/classsl_1_1Pose.html#a1e5ec748db2e79ab28a08c83823e55d6) the value should be between 0 and 100.
