### ISSUE TITLE
change Sift to BRIEF or Orb

### ISSUE THREAD

**Issue by forthealllight** [introlab/rtabmap#200]
I am a Green hand in SLAM , thank you for your souce code , I have a idea that in order to speed up to form  dictionary ，may I use BRIEF or Orb descriptor (like DBW2 or  ORB-SLAM)? if so , recall will be influenced or not  ?  thank you~

**Comment by matlabbe** [comment]
Yes you can choose any other detector (vocabulary or odometry). Loop closure recall performance could be indeed affected. However, I'm using often GFTT/BRIEF (or ORB) and all loop closures (seen from same point of view) are detected most of the time. I didn't compare with datasets of this [paper](https://introlab.3it.usherbrooke.ca/mediawiki-introlab/images/b/bc/TRO2013.pdf) (using SURF).

cheers

**Comment by forthealllight** [comment]
thank you very much

**Comment by forthealllight** [comment]
as you know
