### ISSUE TITLE
rtabmap compilation error

### ISSUE THREAD

**Issue by ziqB** [introlab/rtabmap#209]
Hi im new to compiling source codes in general. I got the following error while trying to compile rtabmap. Thanks in advance

RTAB-Map GUI lib is not built, the RGBDMapping and WifiMapping examples will not be built...

--------------------------------------------
Info :
  Version : 0.12.5
  CMAKE_INSTALL_PREFIX = C:/Program Files (x86)/RTABMap
  CMAKE_BUILD_TYPE =     
  CMAKE_INSTALL_LIBDIR = lib
  BUILD_APP =            ON
  BUILD_TOOLS =          ON
  BUILD_EXAMPLES =       ON
  CMAKE_CXX_FLAGS = /DWIN32 /D_WINDOWS /W3 /GR /EHsc  -openmp
  With OpenCV 2 nonfree module (SIFT/SURF) = YES (License: Non commercial)
  With Freenect             = NO (libfreenect not found)
  With OpenNI2              = YES (License: Apache v2)
  With Freenect2            = NO (libfreenect2 not found)
  With dc1394               = NO (dc1394 not found)
  With FlyCapture2/Triclops = NO (Point Grey SDK not found)
  With TORO                 = YES (License: Creative Commons [Attribution-NonCommercial-ShareAlike])
  With g2o                  = NO (g2o not found)
  With GTSAM                = NO (GTSAM not found)
  With VERTIGO              = YES (License: GPLv3)
  With cvsba                = NO (cvsba not found)
  With ZED                  = NO (ZED sdk not found)
  With RealSense            = NO (librealsense not found)
  With OCTOMAP              = NO (octomap not found)
  With CPUTSDF              = NO (CPUTSDF not found)
  With Qt                   = NO (Qt not found)
--------------------------------------------
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PSAPI_LIBRARIES
    linked by target "rtabmap_utilite" in directory C:/Users/qlin/Downloads/rtabmap-0.12.5/utilite/src

**Comment by hdsumerkan** [comment]
set(PSAPI_LIBRARIES path_to_lib)
path_to_lib was C:/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0/um/sx64 in my case
