### ISSUE TITLE
ZED sdk is not available

### ISSUE THREAD

**Issue by smallfly** [introlab/rtabmap#235]
Hello,

I'm trying to use the ZED camera with RTAB-Map. The latest version of ZED sdk (v2.1) is installed on my machine. The ZED applications are working fine, but when I run RTAB-Map the ZED sdk is disabled ( in sources - both in the tools bar and the preferences). 

What am I missing?

Thanks!

**Comment by matlabbe** [comment]
What is your cmake status?
```bash
$ cd rtabmap/build
$ cmake ..
```

**Comment by smallfly** [comment]
I'm using the latest windows 64 binary release - v0.13.0
I did not compile the application myself.

**Comment by matlabbe** [comment]
Make sure you download the Windows binaries with CUDA/ZED support: https://github.com/introlab/rtabmap/releases

I tried with ZED sdk 2.1 installed on Windows 10 and it works.

**Comment by smallfly** [comment]
So sorry. I did not see this version (I don't know how). Downloading it right now. Thanks a lot!
