### ISSUE TITLE
Rtabmap with Multiple RealSense ZR300 cameras

### ISSUE THREAD

**Issue by ColeKOP** [introlab/rtabmap#236]
Hi all,

I am wondering how can I run Rtabmap for mapping using two RealSense ZR300 cameras on ROS platform. It can run with the standalone Rtabmap using single camera, but when it comes to two cameras, I do not know how to write the launch file. Can anyone provide with some hints? Thanks a lot.

**Comment by matlabbe** [comment]
Refer to https://answers.ros.org/question/271347/rtabmap-with-multiple-realsense-zr300-cameras/
