### ISSUE TITLE
rtabmap gui not showing up

### ISSUE THREAD

**Issue by ruchikoff** [introlab/rtabmap#251]
I followed the rtabmap_ros hand-held mapping instrctions for Kinect XBOX 360 and ran the following:
 roslaunch openni_launch openni.launch depth_registration:=true
and then:
roslaunch rtabmap_ros rtabmap.launch rtabmap_args:="--delete_db_on_start"
But still the GUI did not show up. I tried using the rviz too by running the following:
roslaunch rtabmap_ros rtabmap.launch rtabmap_args:="--delete_db_on_start" rviz:=true rtabmapviz:=false , it just creates the first thing it sees on and then does not add up anything further. Please help me with this.

**Comment by matlabbe** [comment]
Hi, are there errors in the terminal when launching with rtabmapviz?

**Comment by ruchikoff** [comment]
Yes, 
I am getting an error message that says this:
""
[ERROR] [1513677513.240606866]: Skipping XML Document "/opt/ros/indigo/share/gmapping/nodelet_plugins.xml" which had no Root Element.  This likely means the XML is malformed or missing.

""

**Comment by matlabbe** [comment]
Can you show rqt_graph after starting the launch?

**Comment by ruchikoff** [comment]
This is the rqt_graph that is showing up:

![rqt_graph](https://user-images.githubusercontent.com/29055585/34169482-90f9fa58-e50d-11e7-9a31-e5130c23571e.png)

Also, I tried to just start the GUI by writing rtabmap in the terminal. It showed the following error message:
Segmentation fault (core dumped)

**Comment by matlabbe** [comment]
Is it a rtabmap built from source? It seems to be a wrong version of a third party library opened on start-up, causing a crash on start. What kind of machine do you have? 

Not sure what means n_rtabmap_rtabmap and n_rtabmap_rtabmapviz, is rtabmap node also crashed?

**Comment by ruchikoff** [comment]
I tried formatting my laptop and installing ROS again. Now it works.
