### ISSUE TITLE
How to build DumpMemory.txt for Matlab to use?

### ISSUE THREAD

**Issue by Gatsby23** [introlab/rtabmap#253]
Hi, When I run the RecursiveBayesRTABMAP.m, I saw the DumpMemory.txt file to use and I found it is built from memory.cpp, but I don't know how to build it according to my own dataset. I really appreciate for your help.

**Comment by matlabbe** [comment]
See http://official-rtab-map-forum.67519.x6.nabble.com/How-to-built-the-dumpmemory-txt-for-Matlab-Simluation-td4015.html
