### ISSUE TITLE
Parameter Asking

### ISSUE THREAD

**Issue by Gatsby23** [introlab/rtabmap#260]
I'm sorry I'm a beginner to this programmer, If I wan't to put more SIFT feature to the Image Signature, what should I do?

**Comment by matlabbe** [comment]
For standalone app:
![maxfeatures](https://user-images.githubusercontent.com/2319645/35521765-94745aa2-04e8-11e8-9aef-89b159e4c35d.jpg)

For rtabmap_ros, use "Kp/MaxFeatures" parameter. 

cheers,
Mathieu

**Comment by Gatsby23** [comment]
Ok， Thanks！






发自网易邮箱大师


On 01/30/2018 00:37，matlabbe<notifications@github.com> wrote：

For standalone app:


For rtabmap_ros, use "Kp/MaxFeatures" parameter.

cheers,
Mathieu
