### ISSUE TITLE
Compile error with EurocDataset main.cpp

### ISSUE THREAD

**Issue by zlacelle** [introlab/rtabmap#277]
Problem is with 57a62dbbfd3ca07a28d54ce782f4111093fb7468, as of April 10.

GCC version 5.4.1-2ubuntu1

Adding a `#include <fstream>` to main.cpp fixes the issue.

[86%] Building CXX object tools/EurocDataset/CMakeFiles/euroc_dataset.dir/main.cpp.o
/opt/rtabmap/tools/EurocDataset/main.cpp: In function ‘int main(int, char**)’:
/opt/rtabmap/tools/EurocDataset/main.cpp:306:16: error: aggregate ‘std::ifstream imu_file’ has incomplete type and cannot be defined
  std::ifstream imu_file;
                ^
tools/EurocDataset/CMakeFiles/euroc_dataset.dir/build.make:62: recipe for target 'tools/EurocDataset/CMakeFiles/euroc_dataset.dir/main.cpp.o' failed
make[2]: *** [tools/EurocDataset/CMakeFiles/euroc_dataset.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:987: recipe for target 'tools/EurocDataset/CMakeFiles/euroc_dataset.dir/all' failed
make[1]: *** [tools/EurocDataset/CMakeFiles/euroc_dataset.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by matlabbe** [comment]
thx! added the fix in the above commit

cheers
