### ISSUE TITLE
How to set the Loop closure detection windows locate horizontally in GUI model ?

### ISSUE THREAD

**Issue by Gatsby23** [introlab/rtabmap#280]
In my Rtabmap, the window of Loop closure detection is always locate vertical, so how to locate it horizontally ?

**Comment by matlabbe** [comment]
Go in Preferences->General Settings (GUI), uncheck "Vertical layout." under loop closure detection group.

**Comment by Gatsby23** [comment]
Oh, I have found that, Thank you very much !




pet_wolf23@163.com
 
From: matlabbe
Date: 2018-05-08 23:50
To: introlab/rtabmap
CC: Gatsby23; Author
Subject: Re: [introlab/rtabmap] How to set the Loop closure detection windows locate horizontally in GUI model ? (#280)
Go in Preferences->General Settings (GUI), uncheck "Vertical layout." under loop closure detection group.
