### ISSUE TITLE
Cannot open db created in Ubuntu rtabmap v17 into windows rtabmap v 16

### ISSUE THREAD

**Issue by aaravrav142** [introlab/rtabmap#283]
Hi, 
 I made a db with rtabmap v17 (latest ) and tried to open the db with windows rtabmap application v16. However, the program send me error  about the version compatibility. Is there a plan to release the 17 version for windows. Its not a compulsion. Its just that I had to access the db and I had windows pc handy at the time so downloaded the app to check the data. 

Thanks
Alex

**Comment by matlabbe** [comment]
We can always download the latest windows binaries on AppVeyor: https://ci.appveyor.com/project/matlabbe/rtabmap/branch/master/artifacts

They won't include all camera drivers from the official releases, but at least you will be able to open databases.

cheers,
Mathieu
