### ISSUE TITLE
0.17.5 build no turbojpeg.dll crash on start

### ISSUE THREAD

**Issue by TheBricktop** [introlab/rtabmap#310]
Just to let You know
Cheers

**Comment by matlabbe** [comment]
I re-uploaded the binaries with the missing turbojpeg.dll. Give them a try!

**Comment by TheBricktop** [comment]
Thanks mate,
d415 not only works but gives pretty good results, combined with blender and meshlab its a pretty good scanning device.

Thanks for help!
