### ISSUE TITLE
how to increase pcl resollution in 3d map

### ISSUE THREAD

**Issue by WuYingzheng** [introlab/rtabmap#338]
![screenshot from 2018-11-14 07-02-07](https://user-images.githubusercontent.com/32995778/48478782-a82a5200-e7db-11e8-8135-67593a35bdf8.png)
just as the screen shot show. how to increase pcl resollution in 3d map?

**Comment by matlabbe** [comment]
Go in Preferences->3D Rendering panel. By default images are decimated by 4, you can decrease it.

**Comment by WuYingzheng** [comment]
thank you, matlabbe! 
that's work.
