### ISSUE TITLE
How to increase the frequency of robot_localization with RTABmap？

### ISSUE THREAD

**Issue by TsaiYC73** [introlab/rtabmap#372]
Hi,
I would like using robot_localization to localize with RTAB-map on Px4.
But the frequency of this topic is lower than 1hz. (As)

![Robot_localization](https://user-images.githubusercontent.com/48577835/54472594-9f876e00-4805-11e9-8421-df22bc5f7980.png)

That will lead to a bad result of EKF.
How could I increase the frequency ?

Thanks!

**Comment by matlabbe** [comment]
Which topics are you sending to robot_localization? Odometry lower than 10 Hz is quite bad.

**Comment by TsaiYC73** [comment]
Thank you for the reply at https://github.com/introlab/rtabmap_ros/issues/300.
