### ISSUE TITLE
PCL error when running the demo

### ISSUE THREAD

**Issue by ElderWanng** [introlab/rtabmap#389]
Hey! thank you for your great project!
I am trying run the demo ` Robot mapping ` , with building from source.
And at first RTAB seems to work fine, But I notice that this program can't set up the whole map. After the robot runs through a specific door, the rviz dosen't show the following map after this time.  
![error](https://user-images.githubusercontent.com/23718571/56812245-13894d00-686d-11e9-9131-262a76f9e712.png)
and here is the error message from the shell ( also in the screenshot ):

> [pcl::IterativeClosestPoint::computeTransformation] Not enough correspondences found. Relax your threshold parameters.
[ INFO] [1556284617.909866882, 1368730040.072104887]: rtabmap (33): Rate=1.00s, Limit=0.000s, RTAB-Map=0.1132s, Maps update=0.0074s pub=0.0004s (local map=31, WM=31)
[pcl::IterativeClosestPoint::computeTransformation] Not enough correspondences found. Relax your threshold parameters.

However, when I use the binary version from apt-get, the system works well, the new point cloud show on the screen constantly . But I switch to the latest version for the better VIO , I want to use the newest version.

How can I get over it?
Thanks!

**Comment by matlabbe** [comment]
See http://official-rtab-map-forum.67519.x6.nabble.com/Key-frame-can-t-be-added-constantly-td5778.html
