### ISSUE TITLE
exported point clouds equality is poor

### ISSUE THREAD

**Issue by MattixLee** [introlab/rtabmap#392]
Hello,

thank you very much for your works , I found the exported point cloud quality is worse than the point cloud displayed in the 3d map window. In export 3d clouds window, I just change voxel size to 0.

I want to know how to export the point clouds are shown in 3D map window.

Thank you!

**Comment by matlabbe** [comment]
![Screenshot_2019-05-07_16-25-55](https://user-images.githubusercontent.com/2319645/57330739-ecd8db00-70e4-11e9-93f6-e474e8fe58db.png)
With those settings (with `Regenerate clouds` to false), the generated cloud should be exactly the same than in the 3D Map, as all clouds are copied and assembled directly.

**Comment by MattixLee** [comment]
Hi， matlabbe 

Thank you very much for your reply. According to the settings you provide， there are still some differences between the derived point cloud and the display point cloud. As shown in first image, it is point clouds shown in 3D map window; As shown in second image, it  is point clouds expoerted according to your setting; As shown in third image,it  is point cloud exported accoring to setting of fourth image.

![0](https://user-images.githubusercontent.com/49889155/57342659-84d0d600-7172-11e9-97e8-96d37f375ae2.PNG)
![1](https://user-images.githubusercontent.com/49889155/57342681-9ca85a00-7172-11e9-939d-04bf29195798.PNG)
![2](https://user-images.githubusercontent.com/49889155/57342686-a29e3b00-7172-11e9-9c9e-1e703301ea61.PNG)
![3](https://user-images.githubusercontent.com/49889155/57342695-a8941c00-7172-11e9-9174-6376b9cbcee7.PNG)


Thank you !

**Comment by matlabbe** [comment]
I think the difference between RTAB-Map and MeshLab rendering is that in MeshLab, by default shading is enabled using the normals of the point cloud, as in RTAB-Map there is no shading. Here is an example with shading:
![Screenshot_2019-05-15_15-07-53](https://user-images.githubusercontent.com/2319645/57802263-92163380-7723-11e9-89ba-d2e974a55d15.png)

then disabling shading in Meshlab (clouds look identical):
![Screenshot_2019-05-15_15-08-20](https://user-images.githubusercontent.com/2319645/57802274-96425100-7723-11e9-97e8-00906ca9882a.png)

The shading helps to see the geometry of the cloud. With your parameters, you are smoothing the surfaces, which then appears smoother with shading on.

cheers,
Mathieu

**Comment by MattixLee** [comment]
@matlabbe 
hello,
Thank you very much ! I've got it.
