### ISSUE TITLE
RGBD-Mapping without inheriting QWidget

### ISSUE THREAD

**Issue by ahmadhasan2k8** [introlab/rtabmap#396]
Is there a way to get the point cloud and pose out during running RGBD-Mapping (example) without inheriting QWidget. I do not need the visualization but would like to get point cloud and pose out based on a queries. Is there any location where the updated point cloud/ map is stored?

For example--
In the Euroc-dataset example, is it possible to get the updated point cloud/map out every 5 seconds?

**Comment by ahmadhasan2k8** [comment]
It was some work but done. Closing.

**Comment by DormouseLi** [comment]
@ahmadhasan2k8 Hello！I have the same problem too. Is there any suggestion?

**Comment by matlabbe** [comment]
Just don't inherit QWidget and remove all related QWidget stuff, but keep UEventsHandler if you are using the events based [example](https://github.com/introlab/rtabmap/tree/master/examples/RGBDMapping). Without events, look at this [example](https://github.com/introlab/rtabmap/tree/master/examples/NoEventsExample) instead.

**Comment by fjlxb** [comment]
> Just don't inherit QWidget and remove all related QWidget stuff, but keep UEventsHandler if you are using the events based [example](https://github.com/introlab/rtabmap/tree/master/examples/RGBDMapping). Without events, look at this [example](https://github.com/introlab/rtabmap/tree/master/examples/NoEventsExample) instead.

Did all change in MapBuilder.h file?

**Comment by matlabbe** [comment]
You would have to remove Qt stuff in main.cpp too. You would also need to do your own "waiting loop" here: 
https://github.com/introlab/rtabmap/blob/a4761ad397ce195c254f65be10f7e8e2810facd0/examples/RGBDMapping/main.cpp#L227

**Comment by fjlxb** [comment]
> You would have to remove Qt stuff in main.cpp too. You would also need to do your own "waiting loop" here:
> 
> https://github.com/introlab/rtabmap/blob/a4761ad397ce195c254f65be10f7e8e2810facd0/examples/RGBDMapping/main.cpp#L227

Oh, thx, it works!
