### ISSUE TITLE
Invalid Velocity when Filtering Images while Exporting a Bundler

### ISSUE THREAD

**Issue by Sc0rpe** [introlab/rtabmap#401]
When exporting Bundler with RTABMap 0.18.0 under windows i got the following error message for each camera:

> [ WARN] (2019-05-27 00:10:13) ExportBundlerDialog.cpp:268::rtabmap::ExportBundlerDialog::exportBundler() Camera motion filtering is set, but velocity of camera 329 is not available.

This happens for different dataset is tried. 
When i try the same under Ubuntu 18.04 i get a similiar error but the warning is

> [ WARN] (2019-05-27 00:14:32) main.cpp:155::exportBundler() Fast motion detected for camera 1244 (speed=9541792.00000 m/s > thr=0.300000 m/s), camera is ignored for texturing.

This happens for each camera with the same speed. 
When trying again i get the same warning but with a different speed.
It does not matter if i set filtering by angular or linear velocity

The datasets are recorded with an Asus ZenFone-AR-ZS571KL

**Comment by matlabbe** [comment]
This following line fixed the problem:
https://github.com/introlab/rtabmap/blob/cd6e51a9683b293cdcf431f5fd33846dee43e3ce/corelib/src/Memory.cpp#L3770
by explicitly copying the vector. To get this fix, build rtabmap from source on ubuntu, or get the latest binaries for windows [here](https://ci.appveyor.com/project/matlabbe/rtabmap/branch/master/artifacts) (wait for the artifacts to be built)
