### ISSUE TITLE
Stall at startup

### ISSUE THREAD

**Issue by atnTeosit** [introlab/rtabmap#403]
RTabMap get stuck in cloudViewer constructor.

Here the stack:
	vtkRenderingOpenGL2-8.0.dll!vtkWin32OpenGLRenderWindow::Frame() Ligne 378	C++
 	vtkRenderingCore-8.0.dll!vtkRenderWindow::Render() Ligne 477	C++
 	rtabmap_gui.dll!rtabmap::CloudViewer::CloudViewer(QWidget * parent, rtabmap::CloudViewerInteractorStyle * style) Ligne 181	C++
 	rtabmap_gui.dll!rtabmap::MainWindow::MainWindow(rtabmap::PreferencesDialog * prefDialog, QWidget * parent, bool showSplashScreen) Ligne 218	C++
 	RTABMap.exe!main(int argc, char * * argv) Ligne 53	C++

Freeze on "::SwapBuffers(this->DeviceContext);"

I'm using Visual Studio 2019, VTK 8.0.0 or 8.2.0, PCL 1.8.1 or 1.9.1

It's appending using "RelWithDebInfo" config.

When using "Debug" config, I have a qt assert in CloudViewer constructor : qFatal("QWidget: Must construct a QApplication before a QWidget");
I put a break point in QWidget constructor and found that all UI class constructor are ok until CloudViewer.

It seems that Q_UNLIKELY(!qApp) failed while calling CloudViewer constructor but not on previous UI constructors.

see:
QWidgetPrivate::QWidgetPrivate(int version)
...
    if (Q_UNLIKELY(!qApp)) {
        qFatal("QWidget: Must construct a QApplication before a QWidget");
        return;
    }
..

Does someone have a clue ?
Thanks

**Comment by matlabbe** [comment]
Those configurations have not been tested on Windows. See the appveyor build here: https://github.com/introlab/rtabmap/blob/master/.appveyor.yml
For convenience, all dependencies that we know are working are pre-built. PCL 1.8 or 1.9 should work. You may try VTK 6.3 first as it seems to be a VTK related error, which has been more tested for all rtabmap functionalities.

Regards,
Mathieu

**Comment by atnTeosit** [comment]
It was a graphic driver issue, nothing related to rtabmap.
Thanks
