### ISSUE TITLE
T265 relocalization conflicts with RTAB-Map relocalization

### ISSUE THREAD

**Issue by matlabbe** [introlab/rtabmap#409]
There is currently [no way to disable](https://github.com/IntelRealSense/librealsense/issues/3516#issuecomment-474828004) relocalization feature from T265. The problem is that when realsense relocalizes, we cannot know how much the old poses have moved (assuming they optimize their map), so the map cannot be optimized on RTAB-Map side.

A workaround is to integrate linear and angular velocities like in this post: https://github.com/IntelRealSense/realsense-ros/issues/779.  <s> Modifications would need to be done [here](https://github.com/introlab/rtabmap/blob/e09a872fa2149482e0e4ae3827176c8390da8517/corelib/src/camera/CameraRealSense2.cpp#L210-L230 ). Linear and angular velocites can be fetched like [this](https://github.com/IntelRealSense/realsense-ros/blob/2b3365f5c96fcafa53412881e8e4484a6648bc23/realsense2_camera/src/base_realsense_node.cpp#L1304-L1320).</s> EDIT: The problem is that there is always some velocity even when not moving, the resulting pose drifts and is not as accurate than the pose itself (their odometry approach seems to be a frame-to-map approach, not a frame-to-frame approach). An update to realsense API to disable relocalization is the best option.

Note that on ROS, one may use [robot_localization](http://docs.ros.org/melodic/api/robot_localization/html/index.html) package to integrate the twist coming from realsense odometry.

**Comment by macmason** [comment]
Upvoting here (and at #779) as it's not clear which issue is the "right" one.

**Comment by matlabbe** [comment]
Realsense relocalization is now disabled, see the commit above.
