### ISSUE TITLE
Question: What does the alignFrame do in Camrealsense2.cpp?

### ISSUE THREAD

**Issue by srinath-iko** [introlab/rtabmap#415]
`void alignFrame(const rs2_intrinsics& from_intrin,
                                   const rs2_intrinsics& other_intrin,
                                   rs2::frame from_image,
                                   uint32_t output_image_bytes_per_pixel,
                                   const rs2_extrinsics& from_to_other,
								   cv::Mat & registeredDepth,
								   float depth_scale_meters)`

I notice that a frame(p_out_frame) is set into memory which maps the depth values from the depth stream to a blank frame that has the same intrinsics as the color frame. What is the purpose of the align frame function? It would really help me understand the code a bit more. :)

**Comment by matlabbe** [comment]
This function is used to have a direct correspondence between pixels in the RGB image and the depth image. So for each pixel in the RGB, we know directly the depth of that pixel just by looking at the corresponding pixel in the depth image.

What the function does is projecting all depth pixels in 3D (creating a 3D point cloud), then reprojecting back into RGB camera frame. This depth image is commonly called the "Registered Depth Image".

cheers,
Mathieu
