### ISSUE TITLE
Fix: To make Rtabmap work with Realsense SR300

### ISSUE THREAD

**Issue by srinath-iko** [introlab/rtabmap#421]
Hey @matlabbe ,

The realsense sr300 uses a coded light depth sensor and a rgb camera, which is not set to a sensor in CameraRealSense2.cpp

Replacing
`else if ("Coded-Light Depth Sensor" == module_name)
		{
			UINFO("Found \"%s\"", module_name.c_str());
		}`

with
`else if ("Coded-Light Depth Sensor" == module_name)
		{   
                        sensors[1] = elem;
			UINFO("Found \"%s\"", module_name.c_str());
		}`

does the trick.

**Comment by matlabbe** [comment]
Great! I added it in the commit above. I also added the SR300 in "Select sensor driver" menu for convenience.

Mathieu

**Comment by srinath-iko** [comment]
Thanks! 

Srinath
