### ISSUE TITLE
[Feature request] Add support for new Azure Kinect camera (k4a)

### ISSUE THREAD

**Issue by brookman** [introlab/rtabmap#436]

**Comment by brookman** [comment]
Thank you for the reply! I have tried ROS and the K4A ros package. Unfortunately I wasn't able to compile/run rtabmap_ros on Windows. Is that even possible?

**Comment by matlabbe** [comment]
I've never tried to build rtabmap_ros on Windows. I would suggest to try with an Ubuntu computer first.

**Comment by scimad** [comment]
Any update on this?

**Comment by spbwilson** [comment]
Also interested in any development on this!

**Comment by matlabbe** [comment]
The kit cannot be bought from Canada, unfortunately.

**Comment by tkircher** [comment]
> The kit cannot be bought from Canada, unfortunately.

I'll send you one if you're willing to put some time into supporting it.

**Comment by matlabbe** [comment]
Yes sure! Many camera drivers have been integrated in rtabmap with someone/company sending me a development kit of their product. Sensors can be posted at this [address](https://www.usherbrooke.ca/3it/en/contact/) with my name "Mathieu Labbe".

Regards,
Mathieu

**Comment by tkircher** [comment]
I'm sending one out this week.

**Comment by matlabbe** [comment]
@tkircher Great thx, can you send me the tracking number if you have one (my github username @ gmail.com), the university closed since 2 weeks ago because of covid situation. The package may be held at Fedex/Ups/Post office...

**Comment by tenneck** [comment]
Is the Azure Kinect camera now supported in rtabmap?

**Comment by matlabbe** [comment]
Yes, even in latest windows binaries: https://ci.appveyor.com/project/matlabbe/rtabmap/branch/master/artifacts
