### ISSUE TITLE
Make error with libharfbuzz.so

### ISSUE THREAD

**Issue by dadung** [introlab/rtabmap#446]
Hello, I have a problem with libharfbuzz.so.0
Can you please help me? Thank you

[  4%] Built target rtabmap_utilite
[  5%] Built target res_tool
[ 43%] Built target rtabmap_core
[ 81%] Built target rtabmap_gui
[ 82%] Linking CXX executable ../../../bin/rtabmap
/home/dzungdoan/anaconda3/lib/libharfbuzz.so.0: undefined reference to `FT_Get_Var_Blend_Coordinates'
collect2: error: ld returned 1 exit status
app/src/CMakeFiles/rtabmap.dir/build.make:521: recipe for target '../bin/rtabmap' failed
make[2]: *** [../bin/rtabmap] Error 1
CMakeFiles/Makefile2:416: recipe for target 'app/src/CMakeFiles/rtabmap.dir/all' failed
make[1]: *** [app/src/CMakeFiles/rtabmap.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

HERE IS CMake after doing "Configure" (I used cmake-gui)

Checking for module 'libopenni2'
  No package 'libopenni2' found
Could NOT find OpenNI2 (missing:  OPENNI2_LIBRARY OPENNI2_INCLUDE_DIRS) 
The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

LIBUSB_1_LIBRARY (missing:  LIBUSB_1_INCLUDE_DIR) 
Checking for module 'libopenni2'
  No package 'libopenni2' found
Could NOT find OpenNI2 (missing:  OPENNI2_LIBRARY OPENNI2_INCLUDE_DIRS) 
PCL definitions don't contain "-march=native", make sure all libraries using Eigen are also compiled without that flag to avoid some segmentation faults (with gdb referring to some Eigen functions).
Found Sqlite3: /usr/include /usr/lib/x86_64-linux-gnu/libsqlite3.so
Found OpenMP
Found OpenCV: /usr/local/include;/usr/local/include/opencv
Found PCL: /usr/include/pcl-1.7;/usr/include/eigen3;/usr/include;/usr/include/ni;/usr/include/vtk-6.2;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include;/usr/lib/openmpi/include;/usr/lib/openmpi/include/openmpi;/usr/include/freetype2;/usr/include/x86_64-linux-gnu/freetype2;/usr/include/jsoncpp;/usr/include/x86_64-linux-gnu;/usr/include/python2.7;/usr/include/tcl;/usr/include/hdf5/serial;/usr/include/libxml2;/usr/local/include
Found ZLIB: /home/dzungdoan/anaconda3/include
VTK_RENDERING_BACKEND=OpenGL
Found DC1394: /usr/include/dc1394
CMake Warning at cmake_modules/FindG2O.cmake:122 (MESSAGE):
  Latest g2o version detected with c++11 interface (config file:
  /usr/local/include/g2o/config.h).  Make sure g2o is built with
  "-DBUILD_WITH_MARCH_NATIVE=OFF" to avoid segmentation faults caused by
  Eigen.
Call Stack (most recent call first):
  CMakeLists.txt:367 (FIND_PACKAGE)

Found g2o: /usr/local/include;/usr/include/suitesparse;/usr/include/suitesparse
GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include;/usr/include;/usr/include/eigen3
FlyCapture2_INCLUDE_DIR=FlyCapture2_INCLUDE_DIR-NOTFOUND
FlyCapture2_LIBRARY=FlyCapture2_LIBRARY-NOTFOUND
Triclops_INCLUDE_DIR=Triclops_INCLUDE_DIR-NOTFOUND
Triclops_LIBRARY=Triclops_LIBRARY-NOTFOUND
FlyCaptureBridge_LIBRARY=FlyCaptureBridge_LIBRARY-NOTFOUND
Found cvsba: /usr/local/include
Found installed version of Eigen: /usr/lib/cmake/eigen3
Found required Ceres dependency: Eigen version 3.2.92 in /usr/include/eigen3
Found required Ceres dependency: glog
Found required Ceres dependency: gflags
Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
Architecture: x86_64
Found Pthreads
yaml-cpp not found, euroc_dataset tool won't be built...
--------------------------------------------
Info :
  Version : 0.19.5
  CMAKE_INSTALL_PREFIX = /usr/local
  CMAKE_BUILD_TYPE =     Release
  CMAKE_INSTALL_LIBDIR = lib
  BUILD_APP =            ON
  BUILD_TOOLS =          ON
  BUILD_EXAMPLES =       ON
  BUILD_SHARED_LIBS =    ON
  CMAKE_CXX_FLAGS =  -fmessage-length=0  -fopenmp -std=c++11
  FLANN_KDTREE_MEM_OPT = OFF
  PCL_DEFINITIONS = -DEIGEN_USE_NEW_STDVECTOR;-DEIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET;-DFLANN_STATIC;-Dqh_QHpointer
  PCL_VERSION = 1.7.2

Optional dependencies ('*' affects some default parameters) :
 *With OpenCV 3 xfeatures2d module (SIFT/SURF/BRIEF/FREAK) = YES (License: Non commercial)
  With Qt5                  = YES (License: Open Source or Commercial)
  With VTK 6.2              = YES (License: BSD)
  With external SQLite3     = YES (License: Public Domain)
  With ORB OcTree           = YES (License: GPLv3)
  With Madgwick             = YES (License: GPL)
  With FastCV               = NO (FastCV not found)

 Solvers:
  With TORO                 = YES (License: Creative Commons [Attribution-NonCommercial-ShareAlike])
 *With g2o                  = YES (License: BSD)
 *With GTSAM                = YES (License: BSD)
 *With Ceres                = YES (License: BSD)
  With VERTIGO              = YES (License: GPLv3)
  With cvsba                = YES (License: GPLv2)
 *With libpointmatcher      = NO (libpointmatcher not found)

 Reconstruction Approaches:
  With OCTOMAP              = NO (octomap not found)
  With CPUTSDF              = NO (CPUTSDF not found)
  With OpenChisel           = NO (open_chisel not found)

 Camera Drivers:
  With Freenect             = NO (libfreenect not found)
  With OpenNI2              = NO (OpenNI2 not found)
  With Freenect2            = NO (libfreenect2 not found)
  With Kinect for Windows 2 = NO (Kinect for Windows 2 SDK not found)
  With Kinect for Azure     = NO (Kinect for Azure SDK not found)
  With dc1394               = YES (License: LGPL)
  With FlyCapture2/Triclops = NO (Point Grey SDK not found)
  With ZED                  = NO (ZED sdk not found)
  With RealSense            = NO (librealsense not found)
  With RealSense2           = NO (librealsense2 not found)

 Odometry Approaches:
  With loam_velodyne        = NO (loam_velodyne not found)
  With libfovis             = NO (libfovis not found)
  With libviso2             = NO (libviso2 not found)
  With dvo_core             = NO (dvo_core not found)
  With okvis                = NO (okvis not found)
  With msckf_vio            = NO (WITH_MSCKF_VIO=OFF)
  With VINS-Fusion          = NO (VINS-Fusion not found)
  With ORB_SLAM2            = NO (WITH_G2O should be OFF as ORB_SLAM2 uses its own g2o version)
--------------------------------------------
Configuring done

**Comment by matlabbe** [comment]
On my system, zlib is found in `/usr/include`, not  `/home/dzungdoan/anaconda3/include`. zlib would be installed by default from other dependencies (or explicitly `sudo apt install zlib1g-dev`). Clear the cmake cache if you try changing the PATH for example so that cmake find zlib in '/usr/include' before the one in  `/home/dzungdoan/anaconda3/include`.

**Comment by dadung** [comment]
Thank you, I made it. This is how I did:
1. Change PATH environment (exclude /home/dzungdoan/anaconda3/include): 
export PATH=/usr/lib/x86_64-linux-gnu:/home/dzungdoan/bin:/home/dzungdoan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
You should modify your PATH according to your computer, above is my computer
2. Open cmake-gui
3. File ==> Delete cache
4. Configure & Generate
