### ISSUE TITLE
libg2o.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 2017qiuju** [introlab/rtabmap#459]
Projects/catkin_ws_vins-fusion/devel/lib/rtabmap_ros/stereo_odometry: error while loading shared libraries: libg2o.so: cannot open shared object file: No such file or directory
[ INFO] [1572328227.789534528]: Initializing nodelet with 8 worker threads.
process[rtabmap/rtabmap-7]: started with pid [5616]
Projects/catkin_ws_vins-fusion/devel/lib/rtabmap_ros/rtabmap: error while loading shared libraries: libg2o.so: cannot open shared object file: No such file or directory

need help ！

**Comment by matlabbe** [comment]
Please use a short title for issues. For your error, where libg2o.so is installed?

**Comment by 2017qiuju** [comment]
thinks i try it !

**Comment by HaowenLai** [comment]
I have the same problem. However, for me, the error is 
"./rtabmap: error while loading shared libraries: libgtsam.so.4: cannot open shared object file: No such file or directory".
I build gtsam from source and install it in "/usr/local/lib". I see file libgtsam.so.4 at that path.

**Comment by 2017qiuju** [comment]
对不起 我没有看到 没能帮到你 深表歉意 这是我的联系方式 qq：2904862402 希望进一步交流
