### ISSUE TITLE
GUI Support Error

### ISSUE THREAD

**Issue by Zumbalamambo** [introlab/rtabmap#495]
I'm getting the following error while installing,

> [ 28%] Linking CXX shared library ../../../bin/librtabmap_core.so
> /usr/bin/ld: cannot find -lvtkGUISupportQt
> 

why is that so?

**Comment by matlabbe** [comment]
This dependency is coming from PCL, or has been added from here:
https://github.com/introlab/rtabmap/blob/f9e818c900104e4f10c6a2c55494acce000161ee/CMakeLists.txt#L291-L293

Can you show the output of cmake?

**Comment by matlabbe** [comment]
Which Ubuntu version are you using? I see VTK 8.2, normally on Ubuntu 18.04 it is 6.3.
