### ISSUE TITLE
ZED SDK 3.0 breaks the compilation

### ISSUE THREAD

**Issue by lazydroid** [introlab/rtabmap#499]
Recently (last week) released SDK for ZED cameras from Stereolabs breaks the compilation because of newly introduced types and changes in the namespace. SDK 2.8.* works fine, but does not support the new ZED2 camera.

**Comment by lazydroid** [comment]
I have made the changes to ZED related file that allow RTABMap to get compiled with SDK 3.0 and it works with ZED 2. Attaching the file if anyone is interested.

[CameraStereoZed.cpp.zip](https://github.com/introlab/rtabmap/files/4137758/CameraStereoZed.cpp.zip)

**Comment by matlabbe** [comment]
See pull request #501 and test it. I'll close this issue in the meantime, feel free to comment if the pull request is not working for you.

**Comment by lazydroid** [comment]
Your code fails to compile because the arguments of `RuntimeParameters` have changed :

```
rtabmap/corelib/src/camera/CameraStereoZed.cpp:545:121: error: no matching function for call to ‘sl::RuntimeParameters::RuntimeParameters(sl::SENSING_MODE, bool, bool, sl::REFERENCE_FRAME)’
```

**Comment by matlabbe** [comment]
The commit above should fix the problem, thx for testing it!

**Comment by lazydroid** [comment]
It compiles and works now, thank you very much for your support!!
