### ISSUE TITLE
g2o fatal error

### ISSUE THREAD

**Issue by mikuia09** [introlab/rtabmap#507]
Hi!
I built rtabmap (standalone version)  from source as what wiki writes, with g2o and GTSAM built from source too.
When trying to play dataset from ICL-NUIM, the program crashed and the description is :
<div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%">OptimizerG2O<span style="color: #333333">.</span>cpp:<span style="color: #0000DD; font-weight: bold">1615</span>::optimizaeBA()Condition
(optimizer<span style="color: #333333">.</span>verifyinformationMatrices())<span style="color: #000000; font-weight: bold">not</span> met<span style="color: #FF0000; background-color: #FFAAAA">!</span>
</pre></div>
I setted the source as RGB-D and data from images. I'm not sure whtether it is caused by the camera calibration matrix of the dataset. In ICL-NUIM dataset, the fy is negative. However, in rtabmap, when I try to create calibration file, the fy must be positive. If I change the number to negative in the file, it seems the program can't recognize the calibration file and reported that I must calibrate the camera before using RGB-D SLAM. So I have to set fy as a positive number to run rtabmap.
My system is ubuntu 16.04.
Hope for help.
Thanks

Update:
I used Tum dataset(freiburg1 xyz) to test as the tutorial in the forum, the link is:
http://official-rtab-map-forum.67519.x6.nabble.com/How-to-process-RGBD-SLAM-datasets-with-RTAB-Map-td939.html
I created calibration file, setted the input rate to 5Hz and checked the box that use filename as timestamp, but the same error occurred. Then I editted the function OptimizeBA in OptimizerG2O.cpp. I replaced each information matrix with an identity matrix  and editted the function isCovarianceIgnored as 
<div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%"><span style="color: #007020">bool</span> isCovarianceIgnore() const
{
   <span style="color: #008800; font-weight: bold">return</span> true;
}
</pre></div>
But it still can't work and reported the same error.

**Comment by matlabbe** [comment]
Which g2o version are you using? is it the latest from [master branch](https://github.com/RainerKuemmerle/g2o)? Is PCL also built from source?

**Comment by mikuia09** [comment]
> Which g2o version are you using? is it the latest from [master branch](https://github.com/RainerKuemmerle/g2o)? Is PCL also built from source?

Thanks for your replay.
I gitted clone the g2o souce code recently, and built it. PCL is not built from source, I used apt-get to install pcl lib about 2 years ago.

**Comment by matlabbe** [comment]
Can you try with this release? https://github.com/RainerKuemmerle/g2o/releases/tag/20170730_git
just to see if it is g2o the problem (that version should work).

**Comment by mikuia09** [comment]
> Can you try with this release? https://github.com/RainerKuemmerle/g2o/releases/tag/20170730_git
> just to see if it is g2o the problem (that version should work).

It works!
Thanks for your answer! I'll close the issue.
