### ISSUE TITLE
_transactionMutex isnt getting locked in DBDriver::commit() 

### ISSUE THREAD

**Issue by katrinbschmid** [introlab/rtabmap#509]
hi, My sub classed driver fails here (corrupted linked list) in a multi threading run and i noticed the mutex isnt getting locked in this function. I checked the history and its been like that for a while. Is that intentional? Thanks for your help

https://github.com/introlab/rtabmap/blob/ab9f05fb0ffe70062b1d2becaa587eb3f131a210/corelib/src/DBDriver.cpp#L297

As far as i can see it is called from  void DBDriver::emptyTrashes(bool async) only where it calls 
https://github.com/introlab/rtabmap/blob/ab9f05fb0ffe70062b1d2becaa587eb3f131a210/utilite/src/UThread.cpp#L122
but doesnt lock _transactionMutex?

void DBDriver::commit() const
{
	ULOGGER_DEBUG("");
	this->executeNoResultQuery("COMMIT;");
	_transactionMutex.unlock();
}

**Comment by katrinbschmid** [comment]
Ah its looked in this->beginTransaction(); i wonder why it would corrupt  data there anyways

**Comment by matlabbe** [comment]
`beginTransaction()` and `commit()` should be used together like here:
https://github.com/introlab/rtabmap/blob/5fef44ec2bd394330f7aa7322837bd20788d8695/corelib/src/DBDriver.cpp#L339-L373

Set this to false to avoid the threading stuff, which could make it easier to debug:
https://github.com/introlab/rtabmap/blob/5fef44ec2bd394330f7aa7322837bd20788d8695/corelib/src/Memory.cpp#L2096
