### ISSUE TITLE
Ability to set RealSense2 presets

### ISSUE THREAD

**Issue by eMrazSVK** [introlab/rtabmap#513]
Hello,

I would like to know, if there is an ability to use visual presets for RealSense D435 camera inside rtabmap. These presets are just [JSON files provided by RealsSense developers.](https://github.com/IntelRealSense/librealsense/wiki/D400-Series-Visual-Presets). It would be helpful, since quality of depth map sometimes really depends on those settings. If it is not present or planned for the future, I could take a look and maybe create a PR to implement it. 

Thank you for your response.

**Comment by matlabbe** [comment]
Hi,
Thanks for the suggestion. It has been added in the [commit](https://github.com/introlab/rtabmap/commit/b95195d8bbf5e0fbdab09f16c985e5300538d9d3) above. I cannot test it right now though, I don't have my D435. The code is there if something is not working:
https://github.com/introlab/rtabmap/blob/b95195d8bbf5e0fbdab09f16c985e5300538d9d3/corelib/src/camera/CameraRealSense2.cpp#L487-L511

In GUI, the json path can be added under RealSense2 camera driver:
![json_preset_gui](https://user-images.githubusercontent.com/2319645/78162135-6e7bda80-7414-11ea-8050-3fb2caaf110a.jpg)
