### ISSUE TITLE
Why is that the installation has to be painful in ubuntu?

### ISSUE THREAD

**Issue by Zumbalamambo** [introlab/rtabmap#520]
I'm trying to install it in Ubuntu 18. It always fires up the same error message `/usr/bin/ld: cannot find -lvtkGUISupportQt`

**Comment by malerv** [comment]
Your vtk was compiled with Qt?

Le lun. 23 mars 2020, à 12 h 55, Zumbalamambo <notifications@github.com> a
écrit :

**Comment by Zumbalamambo** [comment]
@malerv yes it is compiled with qt

**Comment by matlabbe** [comment]
Which PCL version are you using? Is it PCL from source or the binaries? Is it Ubuntu 18.04 or newer one? The easiest way to build rtabmap is to use **all** system binaries of the dependencies. That vtkGUISupportQt link is added here:
https://github.com/introlab/rtabmap/blob/034adb9f1f2de9fa8ff3ee6661e22bbfed15fbe2/CMakeLists.txt#L293

similar post: https://github.com/introlab/rtabmap/issues/495
