### ISSUE TITLE
rtabmap1.9.3 compiling errors with microsoft visual stuido 2017 on windows 10

### ISSUE THREAD

**Issue by zengletian1491** [introlab/rtabmap#522]
Hello, I compile rtabmap1.9.3 source code with microsoft visual stuido 2017 on Windows 10 system. All the dependencies, such as GTSAM, PCL1.10.0,  are compiled with source code. However, when I build solution, errors occur in the “errors.docx” or as follows. I don't know how to solve this problem. Could you please give me some suggestions? 
[errors.docx](https://github.com/introlab/rtabmap/files/4372884/errors.docx)
Build：Succeed 25， fail 1， newest 0，skipped 3

  | Code | Interpetations | Project | File | Line
-- | -- | -- | -- | -- | --
error | LNK2019 | unresolved extern symbols "__declspec(dllimport) public: virtual   __cdecl rtabmap::Pose3GravityFactor::~Pose3GravityFactor(void)" (__imp_??1Pose3GravityFactor@rtabmap@@UEAA@XZ)，The symbol in the function "public: virtual class   std::map<int,class rtabmap::Transform,struct std::less<int>,class   std::allocator<struct std::pair<int const ,class rtabmap::Transform>   > > __cdecl rtabmap::OptimizerGTSAM::optimize(int,class   std::map<int,class rtabmap::Transform,struct std::less<int>,class   std::allocator<struct std::pair<int const ,class rtabmap::Transform>   > > const &,class std::multimap<int,class rtabmap::Link,struct   std::less<int>,class std::allocator<struct std::pair<int const   ,class rtabmap::Link> > > const &,class cv::Mat &,class   std::list<class std::map<int,class rtabmap::Transform,struct   std::less<int>,class std::allocator<struct std::pair<int const   ,class rtabmap::Transform> > >,class std::allocator<class   std::map<int,class rtabmap::Transform,struct std::less<int>,class   std::allocator<struct std::pair<int const ,class rtabmap::Transform>   > > > > *,double *,int *)"   (?optimize@OptimizerGTSAM@rtabmap@@UEAA?AV?$map@HVTransform@rtabmap@@U?$less@H@std@@V?$allocator@U?$pair@$$CBHVTransform@rtabmap@@@std@@@4@@std@@HAEBV34@AEBV?$multimap@HVLink@rtabmap@@U?$less@H@std@@V?$allocator@U?$pair@$$CBHVLink@rtabmap@@@std@@@4@@4@AEAVMat@cv@@PEAV?$list@V?$map@HVTransform@rtabmap@@U?$less@H@std@@V?$allocator@U?$pair@$$CBHVTransform@rtabmap@@@std@@@4@@std@@V?$allocator@V?$map@HVTransform@rtabmap@@U?$less@H@std@@V?$allocator@U?$pair@$$CBHVTransform@rtabmap@@@std@@@4@@std@@@2@@4@PEANPEAH@Z)   is referenced | rtabmap_core | F:\rtabmap_source\rtabmap1.9.3_source_code\build\corelib\src\OptimizerGTSAM.obj | 1
error | LNK2019 | unresolved extern symbols "__declspec(dllimport) public: __cdecl   rtabmap::Pose3GravityFactor::Pose3GravityFactor(unsigned __int64,class   gtsam::Unit3 const &,class boost::shared_ptr<class gtsam::noiseModel::Base>   const &,class gtsam::Unit3 const &)"   (__imp_??0Pose3GravityFactor@rtabmap@@QEAA@_KAEBVUnit3@gtsam@@AEBV?$shared_ptr@VBase@noiseModel@gtsam@@@boost@@1@Z)，The symbol in the function "public: virtual class   std::map<int,class rtabmap::Transform,struct std::less<int>,class   std::allocator<struct std::pair<int const ,class rtabmap::Transform>   > > __cdecl rtabmap::OptimizerGTSAM::optimize(int,class   std::map<int,class rtabmap::Transform,struct std::less<int>,class   std::allocator<struct std::pair<int const ,class rtabmap::Transform>   > > const &,class std::multimap<int,class rtabmap::Link,struct   std::less<int>,class std::allocator<struct std::pair<int const   ,class rtabmap::Link> > > const &,class cv::Mat &,class std::list<class   std::map<int,class rtabmap::Transform,struct std::less<int>,class   std::allocator<struct std::pair<int const ,class rtabmap::Transform>   > >,class std::allocator<class std::map<int,class   rtabmap::Transform,struct std::less<int>,class std::allocator<struct   std::pair<int const ,class rtabmap::Transform> > > > >   *,double *,int *)"   (?optimize@OptimizerGTSAM@rtabmap@@UEAA?AV?$map@HVTransform@rtabmap@@U?$less@H@std@@V?$allocator@U?$pair@$$CBHVTransform@rtabmap@@@std@@@4@@std@@HAEBV34@AEBV?$multimap@HVLink@rtabmap@@U?$less@H@std@@V?$allocator@U?$pair@$$CBHVLink@rtabmap@@@std@@@4@@4@AEAVMat@cv@@PEAV?$list@V?$map@HVTransform@rtabmap@@U?$less@H@std@@V?$allocator@U?$pair@$$CBHVTransform@rtabmap@@@std@@@4@@std@@V?$allocator@V?$map@HVTransform@rtabmap@@U?$less@H@std@@V?$allocator@U?$pair@$$CBHVTransform@rtabmap@@@std@@@4@@std@@@2@@4@PEANPEAH@Z)   is referenced | rtabmap_core | F:\rtabmap_source\rtabmap1.9.3_source_code\build\corelib\src\OptimizerGTSAM.obj | 1
error | LNK2019 | unresolved extern symbols "__declspec(dllimport) public: static   void __cdecl rtabmap::Pose3GravityFactor::operator delete(void *)"   (__imp_??3Pose3GravityFactor@rtabmap@@SAXPEAX@Z)，The symbol in the function "public: virtual void *   __cdecl rtabmap::Pose3GravityFactor::`scalar deleting destructor'(unsigned   int)" (??_GPose3GravityFactor@rtabmap@@UEAAPEAXI@Z) is referenced | rtabmap_core | F:\rtabmap_source\rtabmap1.9.3_source_code\build\corelib\src\OptimizerGTSAM.obj | 1
error | LNK2019 | unresolved extern symbols "__declspec(dllimport) public: __cdecl   rtabmap::Pose3GravityFactor::Pose3GravityFactor(class   rtabmap::Pose3GravityFactor const &)"   (__imp_??0Pose3GravityFactor@rtabmap@@QEAA@AEBV01@@Z)，The symbol in the function "public: void __cdecl   std::allocator<class rtabmap::Pose3GravityFactor>::construct<class   rtabmap::Pose3GravityFactor,class rtabmap::Pose3GravityFactor const   &>(class rtabmap::Pose3GravityFactor * const,class   rtabmap::Pose3GravityFactor const &)"   (??$construct@VPose3GravityFactor@rtabmap@@AEBV12@@?$allocator@VPose3GravityFactor@rtabmap@@@std@@QEAAXQEAVPose3GravityFactor@rtabmap@@AEBV23@@Z)   is referenced | rtabmap_core | F:\rtabmap_source\rtabmap1.9.3_source_code\build\corelib\src\OptimizerGTSAM.obj | 1
error | LNK2001 | unresolved extern symbols "public: virtual class   boost::shared_ptr<class gtsam::NonlinearFactor> __cdecl rtabmap::Pose3GravityFactor::clone(void)const   "   (?clone@Pose3GravityFactor@rtabmap@@UEBA?AV?$shared_ptr@VNonlinearFactor@gtsam@@@boost@@XZ) | rtabmap_core | F:\rtabmap_source\rtabmap1.9.3_source_code\build\corelib\src\OptimizerGTSAM.obj | 1
error | LNK2001 | unresolved extern symbols "public: virtual class   Eigen::Matrix<double,-1,1,0,-1,1> __cdecl   rtabmap::Pose3GravityFactor::evaluateError(class gtsam::Pose3 const   &,class boost::optional<class   Eigen::Matrix<double,-1,-1,0,-1,-1> &>)const " (?evaluateError@Pose3GravityFactor@rtabmap@@UEBA?AV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@AEBVPose3@gtsam@@V?$optional@AEAV?$Matrix@N$0?0$0?0$0A@$0?0$0?0@Eigen@@@boost@@@Z) | rtabmap_core | F:\rtabmap_source\rtabmap1.9.3_source_code\build\corelib\src\OptimizerGTSAM.obj | 1
error | LNK1120 | 6 unresolved extern commands | rtabmap_core | F:\rtabmap_source\rtabmap1.9.3_source_code\bin\rtabmap_cored.dll | 1

**Comment by zengletian1491** [comment]
I find the solution：
1）open RTABMap.sln with visual studio 2017
2) add the include directory, the lib directory of GTSAM to the property of the project "rtabmap core"
3) add the additional dependency library of GTSAM
Build (Ctrl + Shift + B)

**Comment by matlabbe** [comment]
CMake should have added GTSAM libraries to linker in visual studio solution. Hopefully you've found a solution. I'll close it.

**Comment by jmxntg** [comment]
Did you manage to build rtabmap windows version? I'm desperately trying to build a version that supports orbbec astra sensor without success. Can you help me please?

**Comment by matlabbe** [comment]
Is orbbec astra sensor using a specific driver or is it using OpenNI2? If OpenNI2 is used, this build would support it: https://ci.appveyor.com/project/matlabbe/rtabmap/branch/master/artifacts
