### ISSUE TITLE
undefined reference to vtkSmartVolumeMapper::SetRequestedRenderModeToRayCast() with OpenGL2

### ISSUE THREAD

**Issue by Lotharyx** [introlab/rtabmap#525]
Hello,
I have found that the exact same issue addressed by [commit 85e7c9cf0481d2802af2708f184dfa34944930b6](https://github.com/introlab/rtabmap/commit/85e7c9cf0481d2802af2708f184dfa34944930b6) also exists when using OpenGL2 and pcl 1.10.0.

The resolution is also exactly the same.  I fixed it with the attached patch to CMakeLists.txt.

[cmakelists.patch.txt](https://github.com/introlab/rtabmap/files/4397809/cmakelists.patch.txt)

Cheers.

**Comment by matlabbe** [comment]
Thx! I pushed to diff. 

cheers,
Mathieu
