### ISSUE TITLE
Is there any plans to support orbbec cameras?

### ISSUE THREAD

**Issue by vangogh-ken** [introlab/rtabmap#528]
Orbbec cameras becomes to be popular. Is there any plans to support orbbec cameras?

**Comment by matlabbe** [comment]
I think you can use OpenNI2 driver to use them in rtabmap. Not sure the [openni download](https://orbbec3d.com/develop/) on their page is compatible with rtabmap, someone could give a try. For the Astra SDK, as I don't own that kind of camera, it would be difficult for me to add support. If someone want to try implementing a new `CameraAstra` class, there are many examples here for other drivers: https://github.com/introlab/rtabmap/tree/master/corelib/src/camera

**Comment by vangogh-ken** [comment]
@matlabbe Got it. Thx.

**Comment by henriquenunez** [comment]
Hello! I have an orbbec camera and I want to create support to it.

**Comment by matlabbe** [comment]
As mentioned in comment above, OpenNI2 driver would work with orbbec camera, unless they have new cameras with a new API to access their cameras.

**Comment by henriquenunez** [comment]
Yes, but one camera specifically requires the Astra SDk, which is the Orbbec Astra S U3 camera. If you plug in more than 1 camera it fails.

**Comment by matlabbe** [comment]
Unfortunately, I cannot test Astra SDK, my Astra camera seems only compatible with OpenNI2.
