### ISSUE TITLE
Not Enough Correspondences

### ISSUE THREAD

**Issue by omair18** [introlab/rtabmap#53]
Hey. Thanks for this great package. I have tried it using rosbags and it worked great.
But when i tested my own data-set using rectified images it gave me warnings of "not enough correspondences found. I tried to find correspondence using MATLAB and it showed more than 40-50 per image ( 1 from left camera and 2nd from right camera. Both cameras are calibrated using ROS).  I have attached snapshots. Can you please suggest a solution regarding this matter? 
![selection_006](https://cloud.githubusercontent.com/assets/1974232/13420041/985f1104-dfa4-11e5-81c6-ea3a138e8744.png)
![selection_007](https://cloud.githubusercontent.com/assets/1974232/13420040/985eb48e-dfa4-11e5-8c96-5340494b1f3d.png)

**Comment by matlabbe** [comment]
Because the visual features are far (>3-4 meters), try 3D -> 2D motion estimation like in the screenshot below. If this doesn't help, set the Logger level to debug (Preferences->Logging) and copy/paste the output here.

![untitled](https://cloud.githubusercontent.com/assets/2319645/13430382/d1a5af98-df92-11e5-9596-eb34fca31eb1.jpg)

**Comment by omair18** [comment]
Thank you for the help. I have made the above mentioned changes but i'm still stuck with the same issue. I have tried changing odometry strategy and visual word type to see what changes it does with output. [Log file](https://drive.google.com/file/d/0BwVVozr6udESMDczQU9McUhFTmM/view?usp=sharing) for Rtabmap with SURF features and Optical flow is [here](https://drive.google.com/file/d/0BwVVozr6udESMDczQU9McUhFTmM/view?usp=sharing). [Log file ](https://drive.google.com/file/d/0BwVVozr6udESRUhxZEtRYUpVdGs/view?usp=sharing)with SIFT & BOW is [here.](https://drive.google.com/file/d/0BwVVozr6udESRUhxZEtRYUpVdGs/view?usp=sharing) 
![selection_009](https://cloud.githubusercontent.com/assets/1974232/13455716/e289e4ac-e080-11e5-8776-7691196029c6.png)
![selection_010](https://cloud.githubusercontent.com/assets/1974232/13455717/e2926636-e080-11e5-9e91-f38ce096cfd1.png)

**Comment by matlabbe** [comment]
It looks like there is a problem with the calibration. Around 1200 features are extracted by the odometry but only ~100 can be triangulated in 3D. In these 100, maybe only 10 would be inliers so not enough to correctly find a transformation between the frames.

Can you do a small recording? Click Tools->"Data recorder...", start a new session, then on next "Stop", the recorded database will be saved. 

cheers

**Comment by omair18** [comment]
I have done a small recording for 50-55 images. You can see the file here. 
[output.db.zip](https://github.com/introlab/rtabmap/files/156177/output.db.zip)

**Comment by matlabbe** [comment]
Did you follow this [tutorial](http://wiki.ros.org/camera_calibration/Tutorials/StereoCalibration) to calibrate the cameras?

The stereo rectification is wrong, see this image (I opened the database with rtabmap-databaseViewer):
![picture3](https://cloud.githubusercontent.com/assets/2319645/13499059/a349ddb0-e12a-11e5-9afb-51bb168b7dec.png)
These are the left and right images superposed. Normally it should only have a disparity on x-axis, not both axes. 

Example of good stereo rectification:
![picture](https://cloud.githubusercontent.com/assets/2319645/13499187/3a074e2c-e12b-11e5-8df9-43d73d7d6034.png)


Note that you can also use the Calibrate tool in RTAB-Map (Preferences->Source->Calibrate) to calibrate the cameras (it is mostly the same interface as the ROS tutorial). There is an example [here](https://github.com/introlab/rtabmap/wiki/Stereo-mapping#calibration-only-need-to-do-this-once-by-camera-setup) (you can do it with the live images of the camera, no need to use a video file).

cheers
