### ISSUE TITLE
Is the odom frame optional?

### ISSUE THREAD

**Issue by tianshiz** [introlab/rtabmap#535]
I know it's against REP-105, but I see that there is the option to just subscribe to an odom topic instead of having an odom frame. What are the pro/cons of either setup?

**Comment by matlabbe** [comment]
rtabmap publishes both TF and the topic like this [official ROS tutorial](http://library.isr.ist.utl.pt/docs/roswiki/navigation(2f)Tutorials(2f)RobotSetup(2f)Odom.html).

The advantage to use the topic is to get the covariance of the pose. You can also get the twist directly. The disadvantage is when you need to synchronize with other sensors, you may not get the correct transform if the odometry topic cannot be exactly synchronized with the other sensors.

When using odom from TF, you can invert the advantages and disadvantages of the topic above. If you don't care about the covariance, use TF to get accurate transforms for a sensor's timestamp.
