### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Zumbalamambo** [introlab/rtabmap#545]
I'm trying to install rtabmap in Ubuntu 18.+

I'm getting the following error,
```

corelib/src/Features2d.cpp:916:19: error: incomplete type ‘CV_SIFT {aka cv::xfeatures2d::SIFT}’ used in nested name specifier
  _sift = CV_SIFT::create(this->getMaxFeatures(), nOctaveLayers_, contrastThreshold_, edgeThreshold_, sigma_);
```

**Comment by Zumbalamambo** [comment]
I have installed opencv 4.3 with contrib module by the way. and I'm trying to install the latest release of rtabmap

**Comment by matlabbe** [comment]
Duplicate of https://github.com/introlab/rtabmap/issues/538
