### ISSUE TITLE
Is android application database compatible with any other platform?

### ISSUE THREAD

**Issue by kaatrasa** [introlab/rtabmap#549]
Hey, I recorded database using the android application (Huawei P30 Pro) and tried to use it with ros melodic rtabmap. I should have the latest version:
![image](https://user-images.githubusercontent.com/46484036/81812748-3bf2f080-952f-11ea-9729-66330dcb43a6.png)

But when importing database collected by the android application:
![Screenshot from 2020-05-13 15-22-30](https://user-images.githubusercontent.com/46484036/81811975-203b1a80-952e-11ea-9ec4-f2e7c6207307.png)

Similarly the android application crashes when importing database recorded using ros melodic rtabmap. Is there some version of rtabmap that is compatible with the android application? Thanks!

**Comment by matlabbe** [comment]
The android version is cutting edge version, which is now 0.20. To open it in rtabmap on desktop, rtabmap 0.20 is also required. You have to [build rtabmap from source](https://github.com/introlab/rtabmap_ros#build-from-source), which won't be complicated if you have already installed `ros-melodic rtabmap-ros`.

Bringing a database created from a robot on the phone has not being tested. The rendering in the android app assumes data taken from the phone.

**Comment by kaatrasa** [comment]
Thanks again, databases work both ways now: I can import database from ros-melodic-rtabmap-ros to the application and vice versa.
