### ISSUE TITLE
an error occurs when compiling

### ISSUE THREAD

**Issue by somebodyus** [introlab/rtabmap#55]
OptimizerCVSBA.cpp: In member function ‘virtual std::map<int, rtabmap::Transform> rtabmap::OptimizerCVSBA::optimizeBA(int, const std::map<int, rtabmap::Transform>&, const std::multimap<int, rtabmap::Link>&, const std::map<int, rtabmap::Signature>&)’:

OptimizerCVSBA.cpp:90:138: error: ‘const value_type’ has no member named ‘isValid’

OptimizerCVSBA.cpp:94:72: error: ‘const class rtabmap::StereoCameraModel’ has no member named ‘isValid’
    else if(signatures.at(iter->first).sensorData().stereoCameraModel().isValid())

OptimizerCVSBA.cpp:108:12: error: ‘class rtabmap::CameraModel’ has no member named ‘isValid’
   if(model.isValid())

I use OpenCV 2.4.12.

**Comment by somebodyus** [comment]
have tried OpenCV 2.4.11
the error still occurs

**Comment by matlabbe** [comment]
This is not an OpenCV issue, the bug is fixed in the commit above. Just update the code and build again:
```bash
$ cd rtabmap
$ git pull
$ cd  build
$ make
```

**Comment by somebodyus** [comment]
problem solved,
thank you
