### ISSUE TITLE
RGB Mapping

### ISSUE THREAD

**Issue by Zumbalamambo** [introlab/rtabmap#558]
I'm following [this](https://github.com/introlab/rtabmap/wiki/Loop-closure-detection)  for generating the Pointcloud. Unfortunately when I try to export the poses, it just tells me that the poses are null. Is there any other solutions for the same?

**Comment by tkircher** [comment]
Like it was pointed out in the other thread, that is only for testing loop closure - matching images to previous images. Not building point clouds.

I think what you're trying to do is better suited for photogrammetry. Maybe try meshroom:

https://alicevision.org/#meshroom

**Comment by Zumbalamambo** [comment]
@tkircher thank you!
