### ISSUE TITLE
RTABmap compilation error

### ISSUE THREAD

**Issue by vnsiot** [introlab/rtabmap#562]
Hi,

While building the RTABmap with g2o and gtsam I'm facing the below errors. can you please tell me what is the reason and solution for this.
![ErrorRTABmap](https://user-images.githubusercontent.com/20367524/84020156-01e70400-a9a0-11ea-98a3-f6c75cf39c23.png)

Thanks,
Satish.

**Comment by matlabbe** [comment]
Do you know which ros package created `libcholmod.a` in your catkin devel space? It seems g2o library is wrongly using this one.

**Comment by vnsiot** [comment]
Hi @matlabbe 
Solved by uninstalling the catkin workspace.
