### ISSUE TITLE
Mapping Pose to the corresponding rgb image

### ISSUE THREAD

**Issue by Zumbalamambo** [introlab/rtabmap#567]
I have exported the rgb images which have random numbers as file names with jpg extensions. I have also exported poses.txt. How do I map each row of the pose information in poses.txt to its corresponding rgb image?... How it is structured?

**Comment by matlabbe** [comment]
If you export in g2o or TORO format, the vertex ids should match the image ids:
![Screenshot from 2020-07-06 14-38-03](https://user-images.githubusercontent.com/2319645/86627472-647af200-bf96-11ea-8c19-4f6b68d8b77d.jpg)

For the other formats, the number of poses and images may differ. If not, the first line corresponds to first image and so on. If you really need a pose for every frame, set `RGBD/LinearUpdate` and `RGBD/AngularUpdate` to 0, so all frames will be added to graph even when the camera is not moving.
