### ISSUE TITLE
DatabaseViewer cannot load graph view when database contain NaN GPS data

### ISSUE THREAD

**Issue by borongyuan** [introlab/rtabmap#570]
Hi,
I'm testing a robot which could run indoor and outdoor. So a GPS receiver is used to help loop closure when running outdoor. The NavSatFix message is published by nmea_serial_driver and sometimes contains NaN data when GPS localization is not available.
The DatabaseViewer load the db file with no problem but it chash when I tried to load graph view.
I got the following error
`[FATAL] (2020-07-15 14:46:59.723) OccupancyGrid.cpp:911::update() Condition (!iter->second.isNull()) not met!`
I tried to disable Rtabmap/LoopGPS but it doesn't work, because the database still contain GPS record. I also tried to remap GPS to an empty topic so no GPS data is recorded, then the graph view could be loaded by DatabaseViewer.
Now I'm considering to add a GPS message filter to block NaN data.

**Comment by matlabbe** [comment]
In the commit above, I added a check for NaN values, ignoring GPS if so. Filtering non valid GPS values before rtabmap is also another solution.
