### ISSUE TITLE
Get real time camera trajectory while Localization

### ISSUE THREAD

**Issue by sumitsarkar1** [introlab/rtabmap#571]
I am able to run T265 as a stereo camera and create a map and localize in it with RTabmap. Is it possible to get the camera trajectory in real time while the camera is localizing in a pre-built map which right now I am able to save with the help of the gui (not real time). Will the same (real time trajectory) be possible in the ROS environment.

**Comment by matlabbe** [comment]
It is possible to relaunch with an already built map in localization mode, then see in real time the odometry trajectory as well the localizations. See section 3.1 on this page: http://wiki.ros.org/rtabmap_ros/Tutorials/HandHeldMapping
