### ISSUE TITLE
Problem building after Ceres update

### ISSUE THREAD

**Issue by aaravrav142** [introlab/rtabmap#589]
Hi, 

I have recently updated the ceres-solver and eigen to 3.3 built from source. After that I git pull the rtabmap library to rebuild from scratch. 
I did `sudo ldconfig `after installing the libraries using `sudo make install`. 
Its giving the following error. I do not know why there is a problem with the ceres solver here. Can you suggest something. 

Thanks 

`[  5%] Built target res_tool
[  5%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/optimizer/OptimizerCeres.cpp.o
In file included from /usr/local/include/ceres/internal/autodiff.h:153:0,
                 from /usr/local/include/ceres/autodiff_cost_function.h:130,
                 from /usr/local/include/ceres/ceres.h:37,
                 from /home/arav/extra_lib/rtabmap/corelib/src/optimizer/OptimizerCeres.cpp:39:
/usr/local/include/ceres/jet.h:981:8: error: ‘ScalarBinaryOpTraits’ is not a class template
 struct ScalarBinaryOpTraits<ceres::Jet<T, N>, T, BinaryOp> {
        ^
/usr/local/include/ceres/jet.h:985:58: error: type/value mismatch at argument 3 in template parameter list for ‘template<class BinaryOp, class T, int N> struct Eigen::ScalarBinaryOpTraits’
 struct ScalarBinaryOpTraits<T, ceres::Jet<T, N>, BinaryOp> {
                                                          ^
/usr/local/include/ceres/jet.h:985:58: note:   expected a constant of type ‘int’, got ‘BinaryOp’
corelib/src/CMakeFiles/rtabmap_core.dir/build.make:854: recipe for target 'corelib/src/CMakeFiles/rtabmap_core.dir/optimizer/OptimizerCeres.cpp.o' failed
make[2]: *** [corelib/src/CMakeFiles/rtabmap_core.dir/optimizer/OptimizerCeres.cpp.o] Error 1
CMakeFiles/Makefile2:913: recipe for target 'corelib/src/CMakeFiles/rtabmap_core.dir/all' failed
make[1]: *** [corelib/src/CMakeFiles/rtabmap_core.dir/all] Error 2
Makefile:171: recipe for target 'all' failed
make: *** [all] Error 2
`

On the catkin_ws ros side as well I am having problems compiling after doing git pull to rtabmap_ros. I am getting the following errors. 

`CMakeFiles/rtabmap_external_loop_detectionexample.dir/src/ExternalLoopDetectionExample.cpp.o: In function `main':
ExternalLoopDetectionExample.cpp:(.text+0x14d3): undefined reference to `rtabmap::Rtabmap::init(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
collect2: error: ld returned 1 exit status
rtabmap_ros/CMakeFiles/rtabmap_external_loop_detectionexample.dir/build.make:1265: recipe for target '/home/arav/catkin_ws/devel/lib/rtabmap_ros/external_loop_detection_example' failed
make[2]: *** [/home/arav/catkin_ws/devel/lib/rtabmap_ros/external_loop_detection_example] Error 1
CMakeFiles/Makefile2:36162: recipe for target 'rtabmap_ros/CMakeFiles/rtabmap_external_loop_detectionexample.dir/all' failed
make[1]: *** [rtabmap_ros/CMakeFiles/rtabmap_external_loop_detectionexample.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`

**Comment by matlabbe** [comment]
I am using system ceres and eigen on ubuntu 18.04. Did you try with system versions? What is your os version?

**Comment by aaravrav142** [comment]
OS version is Ubuntu 16.04. Haven't tried with system eigen and ceres. 

Can you tell me the cmake command for that.
-DCMAKE_WITH_SYSTEM_EIGEN=TRUE 
_DCMAKE_WITH_SYSTEM_CERES=TRUE 

is that correct? 

Thanks

**Comment by matlabbe** [comment]
There is no explicit cmake option for that. When I say "I use ystem version", it is because I didn't rebuild/install anually those libraries. When you rebuild manually, cmake may find those ones before the system ones. Uninstall ceres/eigen from your /usr/local install path so that system ones are found by cmake.

**Comment by aaravrav142** [comment]
Ok uninstalling followed by rebuilding rtabmap solved the problem. But some of my libraries still require the custom ceres and eigen 3.3. After catkin make on the ros side, I re-build the libraries for my use. Hope this will not conflict with the rtabmap in future or do I need to follow this process of uninstalling every time I update the rtabmap library? 
Thanks

**Comment by matlabbe** [comment]
If you don't clean rtabmap's build directory, it may re-use the previous config. If there are indeed compilation issues when using latest ceres version with rtabmap, we can disable `-DWITH_CERES=OFF` to not use it.

**Comment by aaravrav142** [comment]
Thanks. I will close this for now.
