### ISSUE TITLE
What is the model of the bumblebee stereo camera in your demonstration?

### ISSUE THREAD

**Issue by somebodyus** [introlab/rtabmap#59]
What is the model of the bumblebee stereo camera in your demonstration?
What is the resolution of the depth image? What is the base line?

**Comment by matlabbe** [comment]
[Bumblebee2 BB2-03S2C-38](https://www.ptgrey.com/bumblebee2-stereo-vison-03-mp-color-firewire-1394a-38mm-sony-icx424-camera)
 - Resolution in RTAB-Map: 640x480
 - baseline: 12 cm

**Comment by somebodyus** [comment]
Thank you so much.
