### ISSUE TITLE
ORB-SLAM2 with ROS issue

### ISSUE THREAD

**Issue by ihamieh** [introlab/rtabmap#591]
Hello 

After running ORB-SLAM2 with ROS, i get the following error message:

ThinkPad-T440s:~/ORB_SLAM2$ rosrun ORB_SLAM2 MonoAR Vocabulary/ORBvoc.txt /media/ish/New\ Volume/dataset/rgbd_dataset_freiburg1_rpy
ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular
OpenCV Error: Unknown error code -49 (Input file is empty) in cvOpenFileStorage, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/persistence.cpp, line 4484
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/persistence.cpp:4484: error: (-49) Input file is empty in function cvOpenFileStorage

Aborted (core dumped)

**Comment by matlabbe** [comment]
For ORB-SLAM2 alone, you may ask on https://github.com/raulmur/ORB_SLAM2 repo instead. We can only support questions about ORBSLAM2 integration in RTAB-Map.
