### ISSUE TITLE
Orientations of three axes when using realsense cameras

### ISSUE THREAD

**Issue by popDuorz** [introlab/rtabmap#597]
Hi,

May I know the world coordinate of the exported pose (.g2o format, robot), eg what is the x axis, y axis, and z axis point to. For example in computer vision system, the X axis points to the right, the Y axis to the bottom, and the Z axis to the front as seen from the image. How about in rtabmap. Thnaks

**Comment by matlabbe** [comment]
If you want to export the pose in camera frame (x->right, y->down, z->forward), choose camera frame in the dropdown box when exporting. The "robot" frame means the base frame of the robot, and it follows ROS REP105: https://www.ros.org/reps/rep-0105.html (x->forward, y->left, z->up).

**Comment by popDuorz** [comment]
Thanks. Very helpful information :)
