### ISSUE TITLE
Creating Pointcloud

### ISSUE THREAD

**Issue by Zumbalamambo** [introlab/rtabmap#604]
I have got RGB images, depth images, pose information of every image in JSON format, and also the camera intrinsic. How can I input this information to create a point cloud with rtabmap?

**Comment by matlabbe** [comment]
You would have to convert your JSON to a format compatible with RTAB-Map, for example the KITTI dataset or RGB-D dataset formats. If you have the same number of poses than images, you can use raw format (see below). Then select RGB-D input source, Images driver, fill RGB and depth folders. For poses, fill odometry path. 
![Screenshot from 2020-09-27 13-12-37](https://user-images.githubusercontent.com/2319645/94371273-3acbf580-00c3-11eb-9ae0-e5615fb08181.jpg)

cheers,
Mathieu

**Comment by Zumbalamambo** [comment]
thank you!
