### ISSUE TITLE
Intermediate Nodes [question]

### ISSUE THREAD

**Issue by NicoNorena** [introlab/rtabmap#622]
What is the purpose of the Intermediate nodes?
 In what scenario would it be needed?

**Comment by matlabbe** [comment]
This option has been added to evaluate the SLAM approach on KITTI dataset. Their evaluation tool required to have exactly the same number of poses than the images processed. By default, RTAB-Map won't save all odometry frames, as it should run at lower rate. Enabling that option makes RTAB-Map adding those intermediate poses in the graph, while not saving their data. When exporting the final graph, we have all odometry poses.

**Comment by NicoNorena** [comment]
okay, got it thanks.
