### ISSUE TITLE
AppVeyor build breaking due to sourceforge download page redirect

### ISSUE THREAD

**Issue by jamesratzlaff** [introlab/rtabmap#624]
https://github.com/introlab/rtabmap/blob/72e1649cdde0533250108a8c52b3d4f66eb10d6a/.appveyor.yml#L38

The url in the appveyor file ends up downloading the download **page** instead of the binary file

Changing the URL parameter to
 `"https://downloads.sourceforge.net/project/opencvlibrary/opencv-win/2.4.13/opencv-2.4.13.6-vc14.exe?r=&ts="+([int64](([datetime]::UtcNow)-(get-date "1/1/1970")).TotalSeconds)` 
should fix this

**Comment by matlabbe** [comment]
A big thank you, I didn't have time to fix that problem earlier. The only thing I added is to set an `url` variable to concatenate the url before calling wget to avoid this error:
```ps
Invoke-WebRequest : A positional parameter cannot be found that accepts argument '+'.
At line:1 char:1
+ wget "https://downloads.sourceforge.net/project/opencvlibrary/opencv- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
