### ISSUE TITLE
RGBD/SavedLocalizationIgnored not working

### ISSUE THREAD

**Issue by rahulmoorthy19** [introlab/rtabmap#625]
Hello, 

Thank you for the this great mapping technique. Really helping me a lot.

I was working on a project. when the robot is in completely different room in localization mode. Even then the localization is happening at the last localized position. I had also set the RGBD/SavedLocalizationIgnored parameter as true but even after that the error persisted. Help on this would be much appreciated. I have added the rtabmap and rgbdodom parameters below for your reference. 

[map_config.txt](https://github.com/introlab/rtabmap/files/5457638/map_config.txt)

Thank You!!

**Comment by rahulmoorthy19** [comment]
It always starts by saying Rtabmap.cpp:1076::process() Update map correction based on last localization saved in database! correction = xyz=0.000000,0.000000,0.000000 rpy=0.000000,-0.000000,0.000000, nearest id = 1 of last pose = xyz=0.000000,0.000000,0.000000 rpy=0.000000,-0.000000,0.000000, odom = xyz=0.000000,0.000000,0.000000 rpy=0.000000,-0.000000,0.000000

**Comment by matlabbe** [comment]
I am not sure I understand the question. What is the version of rtabmap you are using? In latest code, when we set `RGBD/SavedLocalizationIgnored` to true, it is assumed that the robot starts from origin of the map.

**Comment by rahulmoorthy19** [comment]
Yea...Is solved that error. Closing the issue

**Comment by Delbina** [comment]
> Yea...I solved that error. Closing the issue

Hi,
I have the same issue. in which file you add this parameter? how did you solve this issue?
thanks
