### ISSUE TITLE
Visual Studio Compile - missing ZLIB 

### ISSUE THREAD

**Issue by shuixing85** [introlab/rtabmap#635]
Hi All,

I'm trying to compile the code using VS 2019,
saw the install tutorial and kind of stuck at this step:
![image](https://user-images.githubusercontent.com/9822795/98657565-e21c9780-23a6-11eb-82ff-cc73b6fa8390.png)

the CMake output like this:
1> [CMake] CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
1> [CMake]   Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)

have put the zlib under the program folder, 

my understanding about the next step is to update the dir in CMakeLists.txt?
![image](https://user-images.githubusercontent.com/9822795/98657867-3a539980-23a7-11eb-935b-76f4e218b5b5.png)

can anyone give me a hint about the syntax, 

or any keywords I can pursue? 

Thanks a lot

**Comment by matlabbe** [comment]
If zlib's bin directory is in he PATH, cmake should be able to find zlib: https://github.com/introlab/rtabmap/blob/ad44b65a28c0bb16add80a3d0afb9c721f84ba68/.appveyor.yml#L77

To rebuild [zlib](http://www.zlib.net/) with Visual Studio 2019, this can be done following instructions from source [here](https://github.com/introlab/rtabmap/wiki/Installation#source-1).
```bash
$ cd zlib-1.2.8
$ mkdir build
$ cd build

$ cmake -G "Visual Studio 16 2019" -A x64 ..
$ cmake --build . --config Release --target install
```
