### ISSUE TITLE
Executing make to fix 3d map (3d map is not loading)

### ISSUE THREAD

**Issue by s3668134** [introlab/rtabmap#636]
Hello,

I was having some issues with using 3d map on rviz and rtabmap in which it will not load at all. After executing some of the steps mentioned in #427 [https://github.com/introlab/rtabmap/issues/427#issuecomment-516914817](url) I am faced with this error message. 

`
/usr/bin/ld: cannot find -lvtkGUISupportQtWebkit
collect2: error: ld returned 1 exit status
corelib/src/CMakeFiles/rtabmap_core.dir/build.make:3289: recipe for target '../bin/librtabmap_core.so.0.20.6' failed
make[2]: *** [../bin/librtabmap_core.so.0.20.6] Error 1
`

From my understanding, we are meant to remove this reference and file before rtabmap is compiled. So, why is this error occurring and how could I solve this?

**Comment by matlabbe** [comment]
To use MapCloud plugin in RVIZ, you don't have to follow the instructions in this [post](https://github.com/introlab/rtabmap/issues/427#issuecomment-516914817 ), it should work out of the box. That issue is refering to 3D Map view in rtabmapviz.

If you are going to use rviz, use rtabmap as is.
