### ISSUE TITLE
Noise model

### ISSUE THREAD

**Issue by eliabntt** [introlab/rtabmap#638]
Hi,
are you using any noise model for the LRF/Camera/Depth data that you receive? Do you assume anything wrt that? 
For example the Realsense D435 has, as many other cameras, a noise that increase wrt the distance to the sensor (higher the distance higher the noise of the depths readings). 

Do you use any gaussian noise for example when you create the occupancy grid to account for that?

**Comment by matlabbe** [comment]
No
