### ISSUE TITLE
Interesting issue with recent PCL

### ISSUE THREAD

**Issue by tkircher** [introlab/rtabmap#641]
First, there have been some include optimizations, so:

#include <pcl/conversions.h> needs to be added to core/impl/util3d_surface.hpp
#include <pcl/octree/octree.h> needs to be added to pcl18/surface/texture_mapping.h

In util3d_surface.cpp,
```
std::vector<std::vector<unsigned int> > convertPolygonsFromPCL(const std::vector<pcl::Vertices> & polygons)
{
	std::vector<std::vector<unsigned int> > polygonsOut(polygons.size());
	for(unsigned int p=0; p<polygons.size(); ++p)
	{
		polygonsOut[p] = polygons[p].vertices;
	}
	return polygonsOut;
}
```

Indices used to be a std::uint32_t, but are now of type index_t, which is by default a signed int. So, the compiler claims there is no operator= because they're not compatible types. PCL has a mechanism for specifying the type of index_t, but it won't compile for any value but the default at the moment.

See:
 https://github.com/PointCloudLibrary/pcl/commit/ad00c7bee2fad0391649479d90eee4461a2e74e7#diff-43793afc5b23e08b5e2f7706e4bf562c9af0a0f939a08ecd59f038571314501f

**Comment by matlabbe** [comment]
Thx for reporting, I updated the code!
