### ISSUE TITLE
Functions removed from recent version of GTSAM

### ISSUE THREAD

**Issue by tkircher** [introlab/rtabmap#643]
In optimizer/vertigo/gtsam/switchVariableSigmoid.h, switchVariableLinear.h, and betweenFactorMaxMix.h gtsam::inverse(), distance(), ane eye() are used but have been deprecated. See:

https://github.com/borglab/gtsam/commit/30703ccb6a79bba1dbb2dbc7af744a40a81dbff3

It appears that eye(1) just returned eye(1,1) which returned Matrix::Identity(1,1), so -gtsam::eye(1) can just be replaced with -Matrix::Identity(1,1)

inverse() just applied the method inverse() to the passed object, so for instance we can replace gtsam::inverse(info1).determinant() with (info1.inverse()).determinant()

For distance(), the following commit:

https://github.com/borglab/gtsam/commit/7db7455c12fb9b1c06e9ffc3bc47e27ed489eff1

deprecated error() which is called by distance(). The commit note explains that it has been replaced by loss(), which uses the mahalanobisDistance(). It appears that this is what we should replace distance() with.

Making these changes results in OptimizerGTSAM building but I have not tested it yet. Seems like the version-conditional build logic is getting longer and longer. ;)

**Comment by matlabbe** [comment]
Thx for reporting!
