### ISSUE TITLE
Some doubts about OccupancyGrid::segmentCloud() in OccupancyGrid.hpp

### ISSUE THREAD

**Issue by liuzhenboo** [introlab/rtabmap#646]
I have some question about OccupancyGrid::segmentCloud() at line 38 in the file OccupancyGrid.hpp.
I don't understand the following sentence at line 85 and 90: 

![Screenshot 2020-11-26 17:24:04](https://user-images.githubusercontent.com/57830284/100332375-462c9600-300c-11eb-857e-8f1b720db9e1.png)

`	// add pose rotation without yaw
`
and 
`	cloud = util3d::transformPointCloud(cloud, Transform(0,0, projMapFrame_?pose.z():0, roll, pitch, 0));
`
why add pose rotation without yaw??

Why is this code not like this:

`	cloud = util3d::transformPointCloud(cloud, Transform(pose.x(),pose.y(), pose.z(), roll, pitch, yaw));
`
I hope to get your help, thank you very much！！

As you can see from your code, when you segment the road and obstacles, you publish the two point cloud directly in rtabmap_ros package. So, are the global coordinates of the segmented point cloud you published correct?

![Screenshot 2020-11-26 17:27:33](https://user-images.githubusercontent.com/57830284/100332734-b5a28580-300c-11eb-9ad7-72db28e05035.png)

**Comment by matlabbe** [comment]
Please use links like these by clicking on the line numbers in Github:
https://github.com/introlab/rtabmap/blob/0022b6b993ba68a3cfef5e63aef5daee0ba38fef/corelib/include/rtabmap/core/impl/OccupancyGrid.hpp#L85-L90

https://github.com/introlab/rtabmap_ros/blob/b19a82ef34c24da8ccf28d184f84e95a81ea6d9a/src/nodelets/obstacles_detection.cpp#L322-L332

The published segmented cloud would be in the same frame than the input cloud, the transformed cloud as above is transformed back here:
https://github.com/introlab/rtabmap_ros/blob/b19a82ef34c24da8ccf28d184f84e95a81ea6d9a/src/nodelets/obstacles_detection.cpp#L374-L393

We could use x,y and yaw, but they are not used by the segmentation approach (only z for height if we want to segment in map frame, and roll and pitch for alignment with horizon).

**Comment by liuzhenboo** [comment]
> Please use links like these by clicking on the line numbers in Github:
> https://github.com/introlab/rtabmap/blob/0022b6b993ba68a3cfef5e63aef5daee0ba38fef/corelib/include/rtabmap/core/impl/OccupancyGrid.hpp#L85-L90
> 
> https://github.com/introlab/rtabmap_ros/blob/b19a82ef34c24da8ccf28d184f84e95a81ea6d9a/src/nodelets/obstacles_detection.cpp#L322-L332
> 
> The published segmented cloud would be in the same frame than the input cloud, the transformed cloud as above is transformed back here:
> https://github.com/introlab/rtabmap_ros/blob/b19a82ef34c24da8ccf28d184f84e95a81ea6d9a/src/nodelets/obstacles_detection.cpp#L374-L393
> 
> We could use x,y and yaw, but they are not used by the segmentation approach (only z for height if we want to segment in map frame, and roll and pitch for alignment with horizon).


thank you very much！ I get it.
