### ISSUE TITLE
Error while  find loopclosure on own image data

### ISSUE THREAD

**Issue by shabhu18** [introlab/rtabmap#65]
My images are data collected from camera. I want to detect loop closure in it . I am getting following error.  I followed same step as given in tutorial. 
![screenshot from 2016-03-27 05_47_52](https://cloud.githubusercontent.com/assets/8255663/14065367/47cc2312-f444-11e5-869d-3c53501ee8fc.png)

**Comment by matlabbe** [comment]
It is a link error on runtime. It seems to be a mismatch between the OpenCV version to which rtabmap is built and the one found on runtime. Do you have more than one OpenCV installed?
