### ISSUE TITLE
ZED 2 camera not recognized in v0.20.3 and 0.20.7

### ISSUE THREAD

**Issue by ManChrys** [introlab/rtabmap#657]
Hello,

i've tried to use new version (v0.20.3)  with my ZED2 camera but the zed sdk option in camera detection is gray. I tried the previous version (v0.20.2) and worked fine. 
I'm using ZED SDK 3.3.2 cuda 11 and windows 10.

Thanks in advance.

**Comment by ManChrys** [comment]
hmmm ok i think i understand whats going on here. Is the problem cuda version ?

It works on windows 10 with ZED_SDK_v3.3.3_cuda10.2 but it doesnt work with ZED SDK 3.3.2 cuda 11. So the only difference here is cuda version. Correct me if im wrong.

Thanks in advance.

**Comment by Myzhar** [comment]
@ManChrys when you download the ZED SDK you must choose the file that matches the version of CUDA installed on your machine.
If ZED_SDK_v3.3.3_cuda10.2 works that means that you installed CUDA 10.2, not CUDA11

**Comment by ManChrys** [comment]
Hi @Myzhar,
first of all you did great job guys here!!
I have one pc with windows 10 and cuda version 10.2 and RTABMAP works fine.
On my another pc i have windows 10 and cuda version 11.0 and RTABMAP doesnt work.
So the question is RTABMAP is compatible with  cuda 11 or i have to work only on cuda 10.2?

Thanks in advance.

**Comment by matlabbe** [comment]
We have to rebuild the binaries for cuda 11. I'll try to do this soon.

**Comment by ManChrys** [comment]
@matlabbe thank you guys. I love your project :D

**Comment by ManChrys** [comment]
Hello guys,

i've installed rtabmap 0.20.7 on windows 10 with cuda 11.0,
i've installed  ZED_SDK_Windows10_cuda11.0_v3.3.2

but zed sdk option still not available.

Zed tools (Zedfu, ..)  are working properly so my ZED2 is recognized.

Thanks in advance.

**Comment by matlabbe** [comment]
I update the release notes, RTAB-Map has been built with CUDA 11.1 and ZED 3.3.3. Normally even if you didn't install those, the menu option should be enabled:
![Capture2](https://user-images.githubusercontent.com/2319645/102097158-902abf80-3df3-11eb-8d0c-66408e89c1c1.JPG)

Make sure in About dialog it says "Yes" for "With stereo Zed":
![Capture](https://user-images.githubusercontent.com/2319645/102097209-9d47ae80-3df3-11eb-82dc-e0faaf532ce4.JPG)

I tested with Zed1 and Zed-mini on a different computer than my build machine. I don't have a Zed2 so I cannot say if there is a difference, but the menu option should still be enabled. If there is an incompatibility with zed2, it could be more an error when starting the camera.

**Comment by ManChrys** [comment]
Thnx for the reply. 
In About dialog it says with stereo Zed : No

how can i change this ?

**Comment by matlabbe** [comment]
You may not be starting the right rtabmap, what is the version shown? is it 0.20.7? Make sure you are using the cuda11 build, which is the only one with zed sdk support.

**Comment by ManChrys** [comment]
Hi
First of all thank you guys for the quick responses!! 
The problem was that after your update i accidentally dowloaded RTABMap-0.20.7-win64.exe instead of RTABMap-0.20.7-win64-cuda11_1.exe.

Now it worked fine!! ty guys!!

![1](https://user-images.githubusercontent.com/67521662/102364289-f283eb80-3fbe-11eb-818d-d5a3fec9a3d3.png)
![1](https://user-images.githubusercontent.com/67521662/102364312-f7e13600-3fbe-11eb-91ae-1eab09c8306c.png)
