### ISSUE TITLE
Error while compiling 

### ISSUE THREAD

**Issue by shabhu18** [introlab/rtabmap#67]
In file included from /home/shashank/rtabmap/corelib/src/Features2d.cpp:54:0:
/usr/include/opencv2/nonfree/gpu.hpp:54:18: error: redefinition of ‘class cv::gpu::SURF_GPU’
 class CV_EXPORTS SURF_GPU
                  ^
In file included from /home/shashank/rtabmap/corelib/src/Features2d.cpp:46:0:
/usr/local/include/opencv2/gpu/gpu.hpp:1542:18: error: previous definition of ‘class cv::gpu::SURF_GPU’
 class CV_EXPORTS SURF_GPU
                  ^

Can anyone help??

**Comment by matlabbe** [comment]
It seems you have two OpenCV installed on your computer. One in /usr and the other in /usr/local. Make sure to clean the build directory of rtabmap if a new OpenCV is installed after the first build, to make sure that headers/libraries are not mixed.
