### ISSUE TITLE
rtabmap make error

### ISSUE THREAD

**Issue by jenn-yu** [introlab/rtabmap#688]
I'm following the instructions to build rtabmap from source here: https://github.com/introlab/rtabmap_ros 

However in step 2. `make` fails: 

![image](https://user-images.githubusercontent.com/39226391/108438464-4f00c280-721d-11eb-9138-3c2749280a25.png)

`cmake ..` gave: 

![image](https://user-images.githubusercontent.com/39226391/108438660-bf0f4880-721d-11eb-9312-b13fc58abe8d.png)
![image](https://user-images.githubusercontent.com/39226391/108438707-d5b59f80-721d-11eb-8360-8a934e5698f9.png)

**Comment by matlabbe** [comment]
Thx, the commit above would fix the build without c++11 in the commit above. On a side note, I recommend to install g2o or gtsam for better graph optimizations.
