### ISSUE TITLE
No APK file in recent android26 and android24 docker image

### ISSUE THREAD

**Issue by borongyuan** [introlab/rtabmap#689]
docker cp rtabmap-tango:/root/rtabmap-tango/build/arm64-v8a/app/android/bin/RTABMap-debug.apk .
Error: No such container:path: rtabmap-tango:/root/rtabmap-tango/build/arm64-v8a/app/android/bin/RTABMap-debug.apk

The bin folder is missing.
Thanks

**Comment by matlabbe** [comment]
There was a build issue. I will check why automated docker didn't flag that build error. This commit https://github.com/introlab/rtabmap/commit/e59aad03ed66908dac776d08266c74f4e6503ab0 should fix the problem.

Just noticed something strange on Huawei P30 Pro and AREngine that the depth looks not coming form the TOF camera. I'll check again when the phone is full of charge (tof may be disabled with low battery...).
