### ISSUE TITLE
memory management problem

### ISSUE THREAD

**Issue by lynnsky** [introlab/rtabmap#69]
I use the commands on the[ Benchmark](https://github.com/introlab/rtabmap/wiki/Benchmark#udes-1hz) page.But the time used at each iteration is high,I think memory management is enabled.
![1](https://cloud.githubusercontent.com/assets/9796108/14130767/e9c00e16-f667-11e5-8654-167c444c585c.png)
![3](https://cloud.githubusercontent.com/assets/9796108/14130773/f06ce022-f667-11e5-8f03-001ba1f3d0d5.png)

**Comment by lynnsky** [comment]
In addition to the time is too long, the result is not good.
![3covg _p0 sbq1h imdyu](https://cloud.githubusercontent.com/assets/9796108/14140018/3ed12926-f6a9-11e5-9ae7-74d980661e7a.png)
and matlab` ShowLogs `output:
-- getPrecisionRecall ---
Loading GroundTruth 'E:\vswork\rtabmap\build\tools\ConsoleApp\UdeS_1Hz.png' ...

GT_total_positives =

        2628

False positive! id=2978 with old=2831 (p=0.10797)
False positive! id=5375 with old=5201 (p=0.097505)
False positive! id=507 with old=399 (p=0.097035)
False positive! id=5376 with old=5201 (p=0.097008)
False positive! id=3851 with old=415 (p=0.0962)
False positive! id=3850 with old=415 (p=0.096099)
False positive! id=5377 with old=5201 (p=0.095318)
False positive! id=3501 with old=3378 (p=0.094431)
False positive! id=3849 with old=415 (p=0.09439)
False positive! id=4157 with old=507 (p=0.093311)
False positive! id=65 with old=4 (p=0.092973)
False positive! id=3852 with old=415 (p=0.092477)
False positive! id=3848 with old=415 (p=0.092203)
False positive! id=5374 with old=5201 (p=0.092158)
False positive! id=5283 with old=5175 (p=0.091495)
False positive! id=5373 with old=5192 (p=0.091009)
False positive! id=3500 with old=3378 (p=0.090536)
False positive! id=2976 with old=2829 (p=0.089209)
False positive! id=2703 with old=2590 (p=0.089098)
False positive! id=2704 with old=2590 (p=0.089098)
False positive! id=2702 with old=2590 (p=0.089096)
False positive! id=2701 with old=2590 (p=0.089094)
False positive! id=2700 with old=2590 (p=0.08909)
False positive! id=2699 with old=2590 (p=0.089081)
False positive! id=2698 with old=2590 (p=0.089065)
False positive! id=2697 with old=2590 (p=0.089034)
False positive! id=755 with old=590 (p=0.088978)
False positive! id=2696 with old=2590 (p=0.088971)
False positive! id=2695 with old=2590 (p=0.088844)
False positive! id=2678 with old=2590 (p=0.088723)
False positive! id=2694 with old=2590 (p=0.088577)
False positive! id=2982 with old=2840 (p=0.088211)
False positive! id=506 with old=399 (p=0.088136)
False positive! id=505 with old=399 (p=0.088073)
False positive! id=2693 with old=2590 (p=0.088005)
False positive! id=64 with old=4 (p=0.08766)
False positive! id=2677 with old=2590 (p=0.087298)
False positive! id=2691 with old=2590 (p=0.087079)
False positive! id=2690 with old=2590 (p=0.086798)
False positive! id=2692 with old=2590 (p=0.086747)
False positive! id=3499 with old=3378 (p=0.086701)
False positive! id=756 with old=590 (p=0.086687)
False positive! id=5372 with old=5192 (p=0.086635)
False positive! id=602 with old=527 (p=0.086583)
False positive! id=1192 with old=986 (p=0.086438)
False positive! id=252 with old=179 (p=0.0856)
False positive! id=3498 with old=3378 (p=0.085588)
False positive! id=2389 with old=1906 (p=0.08553)
False positive! id=2689 with old=2590 (p=0.085482)
False positive! id=2679 with old=2590 (p=0.085294)
False positive! id=3846 with old=3720 (p=0.084956)
False positive! id=2688 with old=2590 (p=0.084733)
False positive! id=3497 with old=3378 (p=0.084646)
False positive! id=3845 with old=3720 (p=0.084575)
False positive! id=2676 with old=2590 (p=0.08443)
False positive! id=3637 with old=3347 (p=0.084387)
False positive! id=754 with old=558 (p=0.084361)
False positive! id=3950 with old=387 (p=0.084354)
False positive! id=5201 with old=5162 (p=0.084115)
False positive! id=1894 with old=1597 (p=0.083921)
False positive! id=3844 with old=3720 (p=0.083761)
False positive! id=2687 with old=2590 (p=0.083589)
False positive! id=85 with old=33 (p=0.083521)
False positive! id=3847 with old=418 (p=0.083422)
False positive! id=4155 with old=506 (p=0.083265)
False positive! id=5284 with old=5174 (p=0.082985)
False positive! id=3075 with old=404 (p=0.082851)
False positive! id=757 with old=590 (p=0.082714)
False positive! id=334 with old=190 (p=0.082687)
False positive! id=4446 with old=455 (p=0.082592)
False positive! id=5391 with old=464 (p=0.082577)
False positive! id=5224 with old=5025 (p=0.082421)
False positive! id=5387 with old=464 (p=0.082178)
False positive! id=886 with old=751 (p=0.082008)
False positive! id=3843 with old=3720 (p=0.081999)
False positive! id=913 with old=716 (p=0.081717)
False positive! id=181 with old=139 (p=0.081528)
False positive! id=4750 with old=4192 (p=0.081473)
False positive! id=601 with old=527 (p=0.081354)
False positive! id=2046 with old=1916 (p=0.080915)
False positive! id=2680 with old=2590 (p=0.080877)
False positive! id=3882 with old=450 (p=0.080843)
False positive! id=2686 with old=2590 (p=0.080753)
False positive! id=4156 with old=503 (p=0.080698)
False positive! id=4065 with old=428 (p=0.08063)
False positive! id=2388 with old=1906 (p=0.080628)
False positive! id=4067 with old=428 (p=0.080615)
False positive! id=4064 with old=428 (p=0.080226)
False positive! id=4154 with old=508 (p=0.080186)
False positive! id=333 with old=190 (p=0.080174)
False positive! id=3883 with old=450 (p=0.080082)
False positive! id=72 with old=21 (p=0.079816)
False positive! id=4068 with old=428 (p=0.079811)
False positive! id=2675 with old=2590 (p=0.07973)
False positive! id=3016 with old=2978 (p=0.079705)
False positive! id=2595 with old=2286 (p=0.079647)
False positive! id=1815 with old=1670 (p=0.079636)
False positive! id=1487 with old=854 (p=0.079583)
False positive! id=504 with old=407 (p=0.079551)
False positive! id=813 with old=596 (p=0.079368)
False positive! id=4066 with old=428 (p=0.079326)
False positive! id=5388 with old=5187 (p=0.079254)
False positive! id=814 with old=592 (p=0.079168)
False positive! id=1488 with old=854 (p=0.079128)
False positive! id=3881 with old=450 (p=0.079123)
False positive! id=1893 with old=1597 (p=0.079118)
False positive! id=2202 with old=1908 (p=0.079103)
False positive! id=2684 with old=2590 (p=0.079044)
False positive! id=3949 with old=387 (p=0.079009)
False positive! id=2685 with old=2590 (p=0.078994)
False positive! id=3861 with old=463 (p=0.078916)
False positive! id=819 with old=564 (p=0.078778)
False positive! id=4069 with old=428 (p=0.078767)
False positive! id=251 with old=179 (p=0.078691)
False positive! id=3853 with old=422 (p=0.078673)
False positive! id=2682 with old=2590 (p=0.078598)
False positive! id=1486 with old=854 (p=0.078523)
False positive! id=4070 with old=428 (p=0.078499)
False positive! id=2683 with old=2590 (p=0.078471)
False positive! id=4158 with old=511 (p=0.078365)
False positive! id=758 with old=590 (p=0.078356)
False positive! id=2092 with old=1863 (p=0.078287)
False positive! id=3842 with old=3720 (p=0.078145)
False positive! id=511 with old=398 (p=0.078129)
False positive! id=2613 with old=2575 (p=0.078125)
False positive! id=2681 with old=2590 (p=0.078103)
False positive! id=5371 with old=5192 (p=0.078103)
False positive! id=4071 with old=428 (p=0.078089)
False positive! id=4063 with old=428 (p=0.078033)
False positive! id=3401 with old=3322 (p=0.077952)
False positive! id=2876 with old=2730 (p=0.077883)
False positive! id=3863 with old=467 (p=0.077859)
False positive! id=1092 with old=420 (p=0.077856)
False positive! id=5384 with old=5235 (p=0.077684)
False positive! id=3594 with old=3376 (p=0.077603)
False positive! id=815 with old=592 (p=0.077393)
False positive! id=1177 with old=1048 (p=0.077389)
False positive! id=3862 with old=467 (p=0.077365)
False positive! id=3653 with old=3362 (p=0.077355)
False positive! id=1623 with old=1503 (p=0.077353)
False positive! id=508 with old=394 (p=0.077346)
False positive! id=5056 with old=4945 (p=0.077334)
False positive! id=5064 with old=4425 (p=0.077275)
False positive! id=344 with old=200 (p=0.077255)
False positive! id=1178 with old=1048 (p=0.07718)
False positive! id=5153 with old=4374 (p=0.077167)
False positive! id=3636 with old=3347 (p=0.077162)
False positive! id=4073 with old=428 (p=0.077126)
False positive! id=2552 with old=464 (p=0.077114)
False positive! id=1765 with old=1644 (p=0.077101)
False positive! id=5386 with old=5194 (p=0.07704)
False positive! id=3533 with old=3378 (p=0.076854)
False positive! id=3534 with old=3378 (p=0.076854)
False positive! id=3535 with old=3378 (p=0.076854)
False positive! id=3536 with old=3378 (p=0.076854)
False positive! id=3537 with old=3378 (p=0.076854)
False positive! id=3538 with old=3378 (p=0.076854)
False positive! id=3539 with old=3378 (p=0.076854)
False positive! id=3540 with old=3378 (p=0.076854)
False positive! id=3541 with old=3378 (p=0.076854)
False positive! id=3542 with old=3378 (p=0.076854)
False positive! id=3543 with old=3378 (p=0.076854)
False positive! id=3544 with old=3378 (p=0.076854)
False positive! id=3545 with old=3378 (p=0.076854)
False positive! id=3546 with old=3378 (p=0.076854)
False positive! id=3547 with old=3378 (p=0.076854)
False positive! id=3548 with old=3378 (p=0.076854)
False positive! id=3549 with old=3378 (p=0.076854)
False positive! id=3550 with old=3378 (p=0.076854)
False positive! id=3551 with old=3378 (p=0.076854)
False positive! id=3552 with old=3378 (p=0.076854)
False positive! id=3553 with old=3378 (p=0.076854)
False positive! id=3554 with old=3378 (p=0.076854)
False positive! id=3555 with old=3378 (p=0.076854)
False positive! id=3556 with old=3378 (p=0.076854)
False positive! id=3557 with old=3378 (p=0.076854)
False positive! id=3558 with old=3378 (p=0.076854)
False positive! id=3559 with old=3378 (p=0.076854)
False positive! id=3560 with old=3378 (p=0.076854)
False positive! id=3561 with old=3378 (p=0.076854)
False positive! id=3562 with old=3378 (p=0.076854)
False positive! id=3563 with old=3378 (p=0.076854)
False positive! id=3564 with old=3378 (p=0.076854)
False positive! id=3565 with old=3378 (p=0.076854)
False positive! id=3566 with old=3378 (p=0.076854)
False positive! id=3567 with old=3378 (p=0.076854)
False positive! id=3568 with old=3378 (p=0.076854)
False positive! id=3569 with old=3378 (p=0.076854)
False positive! id=3570 with old=3378 (p=0.076854)
False positive! id=3571 with old=3378 (p=0.076854)
False positive! id=3572 with old=3378 (p=0.076854)
False positive! id=3573 with old=3378 (p=0.076854)
False positive! id=3574 with old=3378 (p=0.076854)
False positive! id=3575 with old=3378 (p=0.076854)
False positive! id=3576 with old=3378 (p=0.076854)
False positive! id=3577 with old=3378 (p=0.076854)
False positive! id=3532 with old=3378 (p=0.076853)
False positive! id=3531 with old=3378 (p=0.076852)
False positive! id=3530 with old=3378 (p=0.07685)
False positive! id=3529 with old=3378 (p=0.076845)
False positive! id=2088 with old=1867 (p=0.076844)
False positive! id=753 with old=558 (p=0.076835)
False positive! id=3528 with old=3378 (p=0.076833)
False positive! id=1768 with old=1616 (p=0.076828)
False positive! id=1191 with old=986 (p=0.076816)
False positive! id=3527 with old=3378 (p=0.076806)
False positive! id=5390 with old=464 (p=0.076779)
False positive! id=812 with old=596 (p=0.07677)
False positive! id=3593 with old=3376 (p=0.07677)
False positive! id=816 with old=592 (p=0.076767)
False positive! id=3880 with old=450 (p=0.076755)
False positive! id=3526 with old=3378 (p=0.076741)
False positive! id=5378 with old=5199 (p=0.076721)
False positive! id=4749 with old=4192 (p=0.076682)
False positive! id=4072 with old=428 (p=0.076608)
False positive! id=3525 with old=3378 (p=0.076588)
False positive! id=4445 with old=486 (p=0.076551)
False positive! id=2800 with old=2613 (p=0.076512)
False positive! id=63 with old=4 (p=0.076487)
False positive! id=2089 with old=1867 (p=0.076457)
False positive! id=5370 with old=5192 (p=0.076439)
False positive! id=3502 with old=3378 (p=0.076421)
False positive! id=1279 with old=897 (p=0.076375)
False positive! id=4244 with old=378 (p=0.076303)
False positive! id=1485 with old=854 (p=0.076289)
False positive! id=2140 with old=1977 (p=0.076225)
False positive! id=3524 with old=3378 (p=0.076219)
False positive! id=915 with old=717 (p=0.076192)
False positive! id=2091 with old=1863 (p=0.076171)
False positive! id=1200 with old=1018 (p=0.076151)
False positive! id=997 with old=558 (p=0.076066)
False positive! id=818 with old=564 (p=0.076062)
False positive! id=3884 with old=450 (p=0.076029)
False positive! id=558 with old=506 (p=0.075961)
False positive! id=2387 with old=1906 (p=0.075937)
False positive! id=2141 with old=1977 (p=0.075895)
False positive! id=5063 with old=4438 (p=0.075863)
False positive! id=600 with old=528 (p=0.075852)
False positive! id=3402 with old=3322 (p=0.07575)
False positive! id=3951 with old=384 (p=0.075743)
False positive! id=5065 with old=4425 (p=0.075678)
False positive! id=2551 with old=2410 (p=0.075645)
False positive! id=2547 with old=418 (p=0.075608)
False positive! id=759 with old=590 (p=0.075593)
False positive! id=311 with old=197 (p=0.07553)
False positive! id=557 with old=506 (p=0.075446)
False positive! id=4062 with old=428 (p=0.075436)
False positive! id=3523 with old=3378 (p=0.075328)
False positive! id=2927 with old=2840 (p=0.075197)
False positive! id=5062 with old=4438 (p=0.075131)
False positive! id=3185 with old=418 (p=0.075093)
False positive! id=1766 with old=1616 (p=0.074994)
False positive! id=3080 with old=406 (p=0.074984)
False positive! id=4151 with old=507 (p=0.07497)
False positive! id=157 with old=42 (p=0.074963)
False positive! id=4075 with old=428 (p=0.074963)
False positive! id=3592 with old=3376 (p=0.074947)
False positive! id=3398 with old=3303 (p=0.074902)
False positive! id=3926 with old=387 (p=0.074896)
False positive! id=158 with old=38 (p=0.074884)
False positive! id=1484 with old=854 (p=0.074845)
False positive! id=4424 with old=511 (p=0.07483)
False positive! id=73 with old=24 (p=0.07481)
False positive! id=2757 with old=2613 (p=0.074805)
False positive! id=2992 with old=2853 (p=0.0748)
False positive! id=3788 with old=3612 (p=0.074794)
False positive! id=4506 with old=4314 (p=0.074782)
False positive! id=2139 with old=1977 (p=0.074732)
False positive! id=2047 with old=1916 (p=0.074728)
False positive! id=2090 with old=1863 (p=0.074721)
False positive! id=3885 with old=450 (p=0.074644)
False positive! id=5385 with old=5284 (p=0.074608)
False positive! id=2087 with old=1881 (p=0.074598)
False positive! id=1892 with old=1597 (p=0.07459)
False positive! id=5055 with old=4530 (p=0.074584)
False positive! id=2726 with old=2589 (p=0.074519)
False positive! id=4915 with old=4282 (p=0.074507)
False positive! id=4427 with old=511 (p=0.074454)
False positive! id=817 with old=564 (p=0.074425)
False positive! id=5057 with old=4945 (p=0.074399)
False positive! id=761 with old=590 (p=0.074388)
False positive! id=762 with old=590 (p=0.074355)
False positive! id=2741 with old=2602 (p=0.074327)
False positive! id=763 with old=590 (p=0.074313)
False positive! id=760 with old=590 (p=0.074308)
False positive! id=2440 with old=1924 (p=0.07429)
False positive! id=764 with old=590 (p=0.074283)
False positive! id=765 with old=590 (p=0.074265)
False positive! id=766 with old=590 (p=0.074257)
False positive! id=767 with old=590 (p=0.074251)
False positive! id=768 with old=590 (p=0.074249)
False positive! id=769 with old=590 (p=0.074248)
False positive! id=770 with old=590 (p=0.074247)
False positive! id=771 with old=590 (p=0.074247)
False positive! id=772 with old=590 (p=0.074247)
False positive! id=773 with old=590 (p=0.074247)
False positive! id=774 with old=590 (p=0.074247)
False positive! id=775 with old=590 (p=0.074247)
False positive! id=776 with old=590 (p=0.074247)
False positive! id=777 with old=590 (p=0.074247)
False positive! id=778 with old=590 (p=0.074247)
False positive! id=779 with old=590 (p=0.074247)
False positive! id=780 with old=590 (p=0.074247)
False positive! id=781 with old=590 (p=0.074247)
False positive! id=782 with old=590 (p=0.074247)
False positive! id=783 with old=590 (p=0.074247)
False positive! id=784 with old=590 (p=0.074247)
False positive! id=785 with old=590 (p=0.074247)
False positive! id=786 with old=590 (p=0.074247)
False positive! id=787 with old=590 (p=0.074247)
False positive! id=788 with old=590 (p=0.074247)
False positive! id=789 with old=590 (p=0.074247)
False positive! id=790 with old=590 (p=0.074247)
False positive! id=791 with old=590 (p=0.074247)
False positive! id=792 with old=590 (p=0.074247)
False positive! id=793 with old=590 (p=0.074247)
False positive! id=3187 with old=422 (p=0.074245)
False positive! id=5032 with old=4415 (p=0.074205)
False positive! id=4074 with old=428 (p=0.07418)
False positive! id=2045 with old=1916 (p=0.074122)
False positive! id=4077 with old=428 (p=0.074111)
False positive! id=159 with old=38 (p=0.074105)
False positive! id=3652 with old=3362 (p=0.074104)
False positive! id=5223 with old=5054 (p=0.074103)
False positive! id=4425 with old=511 (p=0.074088)
False positive! id=3325 with old=463 (p=0.073981)
False positive! id=4472 with old=4331 (p=0.073978)
False positive! id=1814 with old=1670 (p=0.073955)
False positive! id=4079 with old=428 (p=0.07393)
False positive! id=4081 with old=428 (p=0.073887)
False positive! id=3400 with old=3306 (p=0.073868)
False positive! id=2674 with old=2590 (p=0.073848)
False positive! id=4504 with old=4314 (p=0.073775)
False positive! id=2845 with old=2747 (p=0.07377)
False positive! id=2113 with old=1835 (p=0.073734)
False positive! id=4500 with old=4334 (p=0.073704)
False positive! id=250 with old=179 (p=0.073682)
False positive! id=2201 with old=1908 (p=0.073674)
False positive! id=4076 with old=428 (p=0.073673)
False positive! id=5353 with old=5176 (p=0.073658)
False positive! id=593 with old=521 (p=0.073638)
False positive! id=1767 with old=1616 (p=0.07361)
False positive! id=4505 with old=4314 (p=0.073579)
False positive! id=4507 with old=4314 (p=0.073562)
False positive! id=4426 with old=511 (p=0.07354)
False positive! id=3860 with old=463 (p=0.073519)
False positive! id=343 with old=200 (p=0.073484)
False positive! id=2711 with old=2572 (p=0.073473)
False positive! id=3886 with old=450 (p=0.073436)
False positive! id=3399 with old=3303 (p=0.07341)
False positive! id=2071 with old=1873 (p=0.073404)
False positive! id=592 with old=508 (p=0.073335)
False positive! id=752 with old=558 (p=0.073322)
False positive! id=3496 with old=3378 (p=0.073322)
False positive! id=2161 with old=1910 (p=0.073311)
False positive! id=3081 with old=406 (p=0.073295)
False positive! id=4078 with old=428 (p=0.073289)
False positive! id=3879 with old=450 (p=0.073266)
False positive! id=332 with old=190 (p=0.073244)
False positive! id=4083 with old=428 (p=0.073236)
False positive! id=3074 with old=455 (p=0.073225)
False positive! id=4598 with old=4329 (p=0.073207)
False positive! id=4080 with old=428 (p=0.073203)
False positive! id=4082 with old=428 (p=0.073183)
False positive! id=3522 with old=3378 (p=0.073158)
False positive! id=542 with old=411 (p=0.073144)
False positive! id=3841 with old=3720 (p=0.073144)
False positive! id=3967 with old=400 (p=0.073106)
False positive! id=4085 with old=428 (p=0.073104)
False positive! id=3651 with old=3362 (p=0.073077)
False positive! id=4087 with old=428 (p=0.073075)
False positive! id=4089 with old=428 (p=0.073068)
False positive! id=4091 with old=428 (p=0.073066)
False positive! id=4093 with old=428 (p=0.073066)
False positive! id=4095 with old=428 (p=0.073066)
False positive! id=2712 with old=2573 (p=0.073045)
False positive! id=3079 with old=406 (p=0.073017)
False positive! id=4231 with old=399 (p=0.072991)
False positive! id=3086 with old=415 (p=0.072987)
False positive! id=79 with old=33 (p=0.072933)
False positive! id=4084 with old=428 (p=0.072893)
False positive! id=590 with old=519 (p=0.072862)
False positive! id=2546 with old=418 (p=0.072857)
False positive! id=4508 with old=4314 (p=0.072842)
False positive! id=4086 with old=428 (p=0.072832)
False positive! id=4494 with old=4332 (p=0.07282)
False positive! id=4088 with old=428 (p=0.072819)
False positive! id=4090 with old=428 (p=0.072816)
False positive! id=4092 with old=428 (p=0.072815)
False positive! id=4094 with old=428 (p=0.072814)
False positive! id=4096 with old=428 (p=0.072814)
False positive! id=2991 with old=2853 (p=0.0728)
False positive! id=4492 with old=4332 (p=0.072712)
False positive! id=4493 with old=4332 (p=0.072711)
False positive! id=3925 with old=374 (p=0.072695)
False positive! id=4597 with old=4329 (p=0.072668)
False positive! id=726 with old=523 (p=0.072659)
False positive! id=5031 with old=4415 (p=0.0726)
False positive! id=3397 with old=3303 (p=0.072581)
False positive! id=3887 with old=450 (p=0.072548)
False positive! id=335 with old=176 (p=0.072541)
False positive! id=4599 with old=4329 (p=0.07252)
False positive! id=2984 with old=2852 (p=0.07248)
False positive! id=4757 with old=4192 (p=0.072477)
False positive! id=3149 with old=3050 (p=0.072356)
False positive! id=4756 with old=4192 (p=0.072344)
False positive! id=878 with old=516 (p=0.072343)
False positive! id=3038 with old=400 (p=0.072342)
False positive! id=1179 with old=1048 (p=0.07232)
False positive! id=4061 with old=428 (p=0.072244)
False positive! id=4334 with old=512 (p=0.072244)
False positive! id=182 with old=64 (p=0.072159)
False positive! id=2822 with old=399 (p=0.072062)
False positive! id=3864 with old=467 (p=0.071987)
False positive! id=2011 with old=411 (p=0.071959)
False positive! id=2725 with old=2597 (p=0.071927)
False positive! id=4260 with old=378 (p=0.07188)
False positive! id=1176 with old=1045 (p=0.071811)
False positive! id=2987 with old=2851 (p=0.071809)
False positive! id=4333 with old=503 (p=0.0718)
False positive! id=3184 with old=3043 (p=0.071798)
False positive! id=1605 with old=1512 (p=0.071754)
False positive! id=583 with old=520 (p=0.071709)
False positive! id=996 with old=558 (p=0.071706)
False positive! id=5040 with old=4418 (p=0.071701)
False positive! id=4335 with old=519 (p=0.071663)
False positive! id=4758 with old=4192 (p=0.071645)
False positive! id=3082 with old=401 (p=0.071628)
False positive! id=2194 with old=1912 (p=0.071612)
False positive! id=2756 with old=2613 (p=0.071604)
False positive! id=550 with old=404 (p=0.071571)
False positive! id=3166 with old=3019 (p=0.071553)
False positive! id=3787 with old=3612 (p=0.071547)
False positive! id=707 with old=569 (p=0.071518)
False positive! id=3642 with old=3337 (p=0.071518)
False positive! id=3741 with old=3495 (p=0.071468)
False positive! id=4060 with old=428 (p=0.071466)
False positive! id=1180 with old=1048 (p=0.071445)
False positive! id=5041 with old=4418 (p=0.071444)
False positive! id=4473 with old=4320 (p=0.071418)
False positive! id=1482 with old=854 (p=0.071369)
False positive! id=1483 with old=854 (p=0.0713)
False positive! id=4914 with old=4282 (p=0.071233)
False positive! id=885 with old=486 (p=0.071229)
False positive! id=2447 with old=2375 (p=0.071207)
False positive! id=1303 with old=893 (p=0.071156)
False positive! id=4305 with old=466 (p=0.071152)
False positive! id=741 with old=557 (p=0.071133)
False positive! id=2093 with old=1844 (p=0.07112)
False positive! id=2806 with old=418 (p=0.071113)
False positive! id=811 with old=596 (p=0.071048)
False positive! id=2441 with old=1928 (p=0.071042)
False positive! id=319 with old=202 (p=0.071017)
False positive! id=2821 with old=411 (p=0.070993)
False positive! id=364 with old=192 (p=0.070945)
False positive! id=5229 with old=5035 (p=0.070938)
False positive! id=742 with old=557 (p=0.070931)
False positive! id=876 with old=501 (p=0.070918)
False positive! id=1989 with old=1852 (p=0.070877)
False positive! id=998 with old=587 (p=0.070874)
False positive! id=743 with old=557 (p=0.070828)
False positive! id=1971 with old=424 (p=0.070813)
False positive! id=1973 with old=424 (p=0.070813)
False positive! id=1975 with old=424 (p=0.070813)
False positive! id=1969 with old=424 (p=0.07081)
False positive! id=1967 with old=424 (p=0.070797)
False positive! id=1931 with old=1822 (p=0.070794)
False positive! id=2142 with old=1897 (p=0.070707)
False positive! id=1965 with old=424 (p=0.070703)
False positive! id=2439 with old=1924 (p=0.070694)
False positive! id=3503 with old=3378 (p=0.070693)
False positive! id=3889 with old=450 (p=0.070683)
False positive! id=2819 with old=411 (p=0.070675)
False positive! id=1422 with old=871 (p=0.070658)
False positive! id=4855 with old=4268 (p=0.070622)
False positive! id=3966 with old=400 (p=0.070603)
False positive! id=2844 with old=2704 (p=0.070595)
False positive! id=4913 with old=4287 (p=0.070595)
False positive! id=914 with old=715 (p=0.070588)
False positive! id=1557 with old=1488 (p=0.070567)
False positive! id=5038 with old=4418 (p=0.070553)
False positive! id=1953 with old=424 (p=0.070517)
False positive! id=2086 with old=1881 (p=0.070503)
False positive! id=3999 with old=3894 (p=0.070501)
False positive! id=4495 with old=4347 (p=0.070484)
False positive! id=2200 with old=1920 (p=0.070468)
False positive! id=2203 with old=1894 (p=0.070446)
False positive! id=537 with old=398 (p=0.07041)
False positive! id=4259 with old=378 (p=0.070395)
False positive! id=879 with old=516 (p=0.070388)
False positive! id=1692 with old=1628 (p=0.070384)
False positive! id=1693 with old=1628 (p=0.070381)
False positive! id=156 with old=42 (p=0.070372)
False positive! id=5042 with old=4418 (p=0.070361)
False positive! id=3591 with old=3376 (p=0.07036)
False positive! id=1302 with old=893 (p=0.070359)
False positive! id=3312 with old=3225 (p=0.070346)
False positive! id=744 with old=557 (p=0.070336)
False positive! id=5066 with old=4442 (p=0.070327)
False positive! id=1643 with old=1446 (p=0.070318)
False positive! id=2548 with old=418 (p=0.070318)
False positive! id=3780 with old=3504 (p=0.070277)
False positive! id=1691 with old=1628 (p=0.070268)
False positive! id=2820 with old=411 (p=0.07024)
False positive! id=1096 with old=425 (p=0.070226)
False positive! id=2818 with old=411 (p=0.070225)
False positive! id=594 with old=464 (p=0.070198)
False positive! id=1604 with old=1524 (p=0.070176)
False positive! id=3913 with old=406 (p=0.070155)
False positive! id=4491 with old=4332 (p=0.070149)
False positive! id=3654 with old=3376 (p=0.070129)
False positive! id=4471 with old=4331 (p=0.070111)
False positive! id=2710 with old=2572 (p=0.070083)
False positive! id=3024 with old=413 (p=0.070082)
False positive! id=3859 with old=463 (p=0.070063)
False positive! id=4755 with old=4192 (p=0.070044)
False positive! id=4600 with old=4329 (p=0.070016)
False positive! id=582 with old=520 (p=0.070013)
False positive! id=877 with old=731 (p=0.070012)
Recall max (Precision=100%) = 0
Recall max accepted (Precision=100%) = 0
ignored = 47

**Comment by matlabbe** [comment]
What kind of computer you have? It seems that just SURF extraction take around 600/700 ms, thus triggering memory management even with an empty WM. The benchmark was done on a MacbookPro 2010 with i7 (Arrandale). As you can see on Table III of the [referred paper](https://introlab.3it.usherbrooke.ca/mediawiki-introlab/images/b/bc/TRO2013.pdf), recall performance will vary depending on the maximum Working Memory size that can be processed online. On that laptop with 700 ms time threshold, the maximum size of WM is 221 locations. On your side the maximum size of WM seems stuck around 20 locations and processing time is already over 1 sec.

**Comment by lynnsky** [comment]
My computer is Thinkpad T450 with i7-5500U，256G SSD.So I should improve time  threshold？

**Comment by lynnsky** [comment]
Is it related to use debug mode rather than release mode？

**Comment by matlabbe** [comment]
Try to build the code in Release mode instead of Debug, this generally increase a lot the performance, particularly on Windows.

**Comment by lynnsky** [comment]
Thanks for your advice.I build the code in Release mode.Then I got a results as following:
![_be b xv6bp1faq2 d l f](https://cloud.githubusercontent.com/assets/9796108/14166112/d76b4452-f742-11e5-9228-3c6c921b9355.png)
--- getPrecisionRecall ---
Loading GroundTruth 'E:\vswork\rtabmaprelease\build\tools\ConsoleApp\UdeS_1Hz.png' ...

GT_total_positives =

        2628

False positive! id=3927 with old=1194 (p=0.13997)
False positive accepted! id=3927 with old=1194 (p=0.13997)
False positive! id=579 with old=309 (p=0.12179)
False positive accepted! id=579 with old=309 (p=0.12179)
False positive! id=1010 with old=310 (p=0.098755)
False positive! id=3928 with old=1184 (p=0.09676)
False positive! id=1009 with old=310 (p=0.095884)
False positive! id=1011 with old=310 (p=0.094518)
False positive! id=65 with old=4 (p=0.092973)
False positive! id=1012 with old=310 (p=0.092869)
False positive! id=2622 with old=90 (p=0.09209)
False positive! id=1008 with old=310 (p=0.090816)
False positive! id=3499 with old=743 (p=0.090761)
False positive! id=64 with old=4 (p=0.08766)
False positive! id=2778 with old=2726 (p=0.086346)
False positive! id=3498 with old=743 (p=0.083566)
False positive! id=85 with old=33 (p=0.083521)
False positive! id=511 with old=399 (p=0.082917)
False positive! id=1007 with old=310 (p=0.081828)
False positive! id=197 with old=15 (p=0.080056)
False positive! id=3895 with old=1178 (p=0.079923)
False positive! id=72 with old=21 (p=0.079816)
False positive! id=4193 with old=1509 (p=0.078492)
False positive! id=157 with old=42 (p=0.077738)
False positive! id=63 with old=4 (p=0.076487)
False positive! id=5354 with old=5192 (p=0.075888)
False positive! id=196 with old=15 (p=0.075511)
False positive! id=181 with old=139 (p=0.074966)
False positive! id=73 with old=24 (p=0.07481)
False positive! id=2777 with old=2726 (p=0.07398)
False positive! id=2623 with old=91 (p=0.073908)
False positive! id=3932 with old=1220 (p=0.073788)
False positive! id=3896 with old=1178 (p=0.073484)
False positive! id=4929 with old=2339 (p=0.072982)
False positive! id=79 with old=33 (p=0.072933)
False positive! id=183 with old=138 (p=0.072771)
False positive! id=201 with old=15 (p=0.072714)
False positive! id=3852 with old=1102 (p=0.072387)
False positive! id=3897 with old=1178 (p=0.072042)
False positive! id=3851 with old=1102 (p=0.071948)
False positive! id=3985 with old=1253 (p=0.07177)
False positive! id=3850 with old=1102 (p=0.071707)
False positive! id=172 with old=21 (p=0.071564)
False positive! id=186 with old=72 (p=0.071511)
False positive! id=3849 with old=1102 (p=0.07139)
False positive! id=202 with old=15 (p=0.071375)
False positive! id=184 with old=85 (p=0.071159)
False positive! id=3481 with old=691 (p=0.071008)
False positive! id=3848 with old=1102 (p=0.070946)
False positive! id=3847 with old=1102 (p=0.070281)
False positive! id=3497 with old=809 (p=0.070265)
False positive! id=185 with old=138 (p=0.070222)
False positive! id=178 with old=68 (p=0.070111)
Recall max (Precision=100%) = 45.0913% (p=0.14045), accepted=1185
Recall max accepted (Precision=100%) = 45.0913% (p=0.14045), accepted=1185
ignored = 74

**Comment by lynnsky** [comment]
Can I ask a question?what can I do with this file ` rtabmapconsole.db`?

**Comment by matlabbe** [comment]
Your results are now more similar to the paper. If you were only interested on statistics of loop closure detection, you can delete it. The database contains the graph of the created map (e.g., loop closure links). You can browse images and features saved in it with `rtabmap-databaseViewer.exe`.

**Comment by lynnsky** [comment]
It's is cool.Thanks for your project.

**Comment by lynnsky** [comment]
It's cool.Thanks for your project.
