### ISSUE TITLE
Insights into Localization Mode

### ISSUE THREAD

**Issue by sumitsarkar1** [introlab/rtabmap#699]
I have build a 3D map using L515 and T265 in dual mode using RTabMap. However, I now require to use the 3D Map and a RGB Camera to run ONLY in the localization mode. Is it a good idea to localize using only a rgb camera given a map which was build by lidar and t265. I was just curious about how RTbaMap runs in only localization mode..like what does it match to initially when one turns on the sensor and what does it keep matching to after initially it has localized itself. Any theoritical insigh will be helpful.

**Comment by matlabbe** [comment]
You still need odometry even with using only RGB camera. With the standalone version there is no option to combine T265 odometry with an external RGB camera. This could be done with rtabmap_ros though, by feeding T265 odometry and RGB-only images to rtabmap node. With `Vis/EstimationType=1` (PnP), rtabmap will extract 2D features form the RGB image and find the camera position against the 3D features of the map.
