### ISSUE TITLE
Magic matrix during exporting to Bundler output

### ISSUE THREAD

**Issue by egoist-sx** [introlab/rtabmap#72]
I saw there is a magic matrix multiplied before export rotation as bundler format.

In [this](https://github.com/introlab/rtabmap/blob/d489cd48e969b38c8b004498d400a0b47a9bf637/guilib/src/MainWindow.cpp#L5246) line 5246. Why this matrix is needed?

**Comment by matlabbe** [comment]
The magic transform is to transform camera poses in OpenGL coordinate system (x right, y up, z backward), which is the one used by MeshLab when importing bundler project. RTAB-Map uses ROS coordinate system (x forward, y left, z up). See this example (from this [tutorial](https://github.com/introlab/rtabmap/wiki/Export-Raster-Layers-to-MeshLab)):

![rtabmap_coordinate_system](https://cloud.githubusercontent.com/assets/2319645/14331985/917087a0-fc15-11e5-9529-eb8dbe8ad49b.jpg)

**Comment by egoist-sx** [comment]
@matlabbe Thanks a lot!
