### ISSUE TITLE
Openvins Parameters 

### ISSUE THREAD

**Issue by Majed-Alsubaie** [introlab/rtabmap#748]
Hi..
How can i change Openvins parameters ?
I tried to: 
1-change
https://github.com/introlab/rtabmap/blob/f9257beeb822f31f56a9ebde2a6e389527b386a5/corelib/src/odometry/OdometryOpenVINS.cpp#L156
2-change
https://github.com/rpng/open_vins/blob/c6f7e947e82485873495123a1841bd57f8041a33/ov_msckf/src/core/VioManagerOptions.h#L64
3- add parameter to the launch file

but nothing working with me !

Thanks

**Comment by matlabbe** [comment]
With the current integration, you have to hard-code the value.

> but nothing working with me !
How did you test it is not working?

Try standalone OpenVINS package before trying the integration inside rtabmap.
