### ISSUE TITLE
[FATAL] (2021-07-09 16:58:42.406) Memory.cpp:4143::createSignature() && [rtabmap/rtabmap-1] process has died [pid 26951, exit code -6, cmd 

### ISSUE THREAD

**Issue by Haydar1990** [introlab/rtabmap#753]
Hallo , i am new on ROS & Rtabmap, i am trying to bild a 3D map using Gazebo and Rtabmap And i got this 

My Launch file:

<launch>
  <arg name="database_path" default="~/Documents/RTAB-Map/rtabmap.db"/>
  <arg name="localization" default="false"/>
  <arg name="args" default=""/>

  <arg name="wait_for_transform" default="0.2"/>
  
  
  

  
  <group ns="rtabmap">
    <node name="rtabmap" pkg="rtabmap_ros" type="rtabmap" output="screen" args="$(arg args)">
          <param name="database_path"  type="string" value="$(arg database_path)"/>
          <param name="frame_id"       type="string" value="base_footprint"/>
          <param name="odom_frame_id"       type="string" value="odom_comb"/>
          <param name="wait_for_transform_duration" type="double" value="$(arg wait_for_transform)"/>
          <param name="subscribe_depth"     type="bool"   value="true"/>
          <param name="subscribe_scan"      type="bool"   value="true"/>

          
          <remap from="scan"            to="/scan"/>
          <remap from="rgb/image"       to="/camera/color/image_raw"/>
          <remap from="depth/image"     to="/camera/depth/image_raw"/>
          <remap from="rgb/camera_info" to="/camera/color/camera_info"/>

          
          <remap from="grid_map" to="/map"/>

          
          <param name="RGBD/ProximityBySpace"        type="string" value="true"/>   
          <param name="RGBD/OptimizeFromGraphEnd"    type="string" value="false"/>  
          <param name="Kp/MaxDepth"                  type="string" value="4.0"/>
          <param name="Reg/Strategy"                 type="string" value="1"/>      
          <param name="Icp/CorrespondenceRatio"      type="string" value="0.3"/>
          <param name="Vis/MinInliers"               type="string" value="5"/>      
          <param name="Vis/InlierDistance"           type="string" value="0.1"/>    
          <param name="RGBD/AngularUpdate"           type="string" value="0.01"/>    
          <param name="RGBD/LinearUpdate"            type="string" value="0.01"/>    
          <param name="Rtabmap/TimeThr"              type="string" value="700"/>
          <param name="Mem/RehearsalSimilarity"      type="string" value="0.30"/>
          <param name="Optimizer/Slam2D"             type="string" value="true"/>
          <param name="Reg/Force3DoF"                type="string" value="true"/>
          
          <param if="$(arg localization)" name="Mem/IncrementalMemory" type="string" value="false"/>
          <param if="$(arg localization)" name="Mem/InitWMWithAllNodes" type="string" value="true"/>
    </node>
  </group>
</launch>

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.11
 * /rtabmap/rtabmap/Icp/CorrespondenceRatio: 0.3
 * /rtabmap/rtabmap/Kp/MaxDepth: 4.0
 * /rtabmap/rtabmap/Mem/RehearsalSimilarity: 0.30
 * /rtabmap/rtabmap/Optimizer/Slam2D: true
 * /rtabmap/rtabmap/RGBD/AngularUpdate: 0.01
 * /rtabmap/rtabmap/RGBD/LinearUpdate: 0.01
 * /rtabmap/rtabmap/RGBD/OptimizeFromGraphEnd: false
 * /rtabmap/rtabmap/RGBD/ProximityBySpace: true
 * /rtabmap/rtabmap/Reg/Force3DoF: true
 * /rtabmap/rtabmap/Reg/Strategy: 1
 * /rtabmap/rtabmap/Rtabmap/TimeThr: 700
 * /rtabmap/rtabmap/Vis/InlierDistance: 0.1
 * /rtabmap/rtabmap/Vis/MinInliers: 5
 * /rtabmap/rtabmap/database_path: ~/Documents/RTAB-...
 * /rtabmap/rtabmap/frame_id: base_footprint
 * /rtabmap/rtabmap/odom_frame_id: odom_comb
 * /rtabmap/rtabmap/subscribe_depth: True
 * /rtabmap/rtabmap/subscribe_scan: True
 * /rtabmap/rtabmap/wait_for_transform_duration: 0.2

NODES
  /rtabmap/
    rtabmap (rtabmap_ros/rtabmap)

ROS_MASTER_URI=http://localhost:11311

process[rtabmap/rtabmap-1]: started with pid [26951]
[ INFO] [1625842720.528433218]: Starting node...
[ INFO] [1625842720.577975466]: Initializing nodelet with 4 worker threads.
[ INFO] [1625842720.772281123]: /rtabmap/rtabmap(maps): map_filter_radius          = 0.000000
[ INFO] [1625842720.772358592]: /rtabmap/rtabmap(maps): map_filter_angle           = 30.000000
[ INFO] [1625842720.772396380]: /rtabmap/rtabmap(maps): map_cleanup                = true
[ INFO] [1625842720.772426384]: /rtabmap/rtabmap(maps): map_always_update          = false
[ INFO] [1625842720.772460399]: /rtabmap/rtabmap(maps): map_empty_ray_tracing      = true
[ INFO] [1625842720.772486999]: /rtabmap/rtabmap(maps): cloud_output_voxelized     = true
[ INFO] [1625842720.772512517]: /rtabmap/rtabmap(maps): cloud_subtract_filtering   = false
[ INFO] [1625842720.772538359]: /rtabmap/rtabmap(maps): cloud_subtract_filtering_min_neighbors = 2
[ INFO] [1625842720.773605798]: /rtabmap/rtabmap(maps): octomap_tree_depth         = 16
[ INFO] [1625842720.796755950]: rtabmap: frame_id      = base_footprint
[ INFO] [1625842720.796796974]: rtabmap: odom_frame_id = odom_comb
[ INFO] [1625842720.796813330]: rtabmap: map_frame_id  = map
[ INFO] [1625842720.796824061]: rtabmap: use_action_for_goal  = false
[ INFO] [1625842720.796838292]: rtabmap: tf_delay      = 0.050000
[ INFO] [1625842720.796850992]: rtabmap: tf_tolerance  = 0.100000
[ INFO] [1625842720.796860400]: rtabmap: odom_sensor_sync   = false
[ INFO] [1625842720.797178675]: rtabmap: gen_scan  = false
[ INFO] [1625842720.797199127]: rtabmap: gen_depth  = false
[ INFO] [1625842720.928227918, 134.837000000]: Setting RTAB-Map parameter "Icp/CorrespondenceRatio"="0.3"
[ INFO] [1625842720.983688549, 134.876000000]: Setting RTAB-Map parameter "Kp/MaxDepth"="4.0"
[ INFO] [1625842721.036366967, 134.903000000]: Setting RTAB-Map parameter "Mem/RehearsalSimilarity"="0.30"
[ INFO] [1625842721.067576534, 134.918000000]: Setting RTAB-Map parameter "RGBD/AngularUpdate"="0.01"
[ INFO] [1625842721.072770534, 134.921000000]: Setting RTAB-Map parameter "RGBD/LinearUpdate"="0.01"
[ INFO] [1625842721.084267915, 134.927000000]: Setting RTAB-Map parameter "RGBD/OptimizeFromGraphEnd"="false"
[ INFO] [1625842721.089445105, 134.930000000]: Setting RTAB-Map parameter "RGBD/ProximityBySpace"="true"
[ INFO] [1625842721.103402416, 134.938000000]: Setting RTAB-Map parameter "Reg/Force3DoF"="true"
[ INFO] [1625842721.104524641, 134.938000000]: Setting RTAB-Map parameter "Reg/Strategy"="1"
[ INFO] [1625842721.131418191, 134.951000000]: Setting RTAB-Map parameter "Rtabmap/TimeThr"="700"
[ INFO] [1625842721.211846134, 135.003000000]: Setting RTAB-Map parameter "Vis/InlierDistance"="0.1"
[ INFO] [1625842721.217042255, 135.008000000]: Setting RTAB-Map parameter "Vis/MinInliers"="5"
[ WARN] [1625842721.338281130, 135.071000000]: Rtabmap: Parameter name changed: "Optimizer/Slam2D" -> "Reg/Force3DoF". Please update your launch file accordingly. Value "true" is still set to the new parameter name.
[ WARN] [1625842721.399590357, 135.114000000]: Setting "Grid/FromDepth" parameter to false (default true) as "subscribe_scan", "subscribe_scan_cloud" or "gen_scan" is true. The occupancy grid map will be constructed from laser scans. To get occupancy grid map from cloud projection, set "Grid/FromDepth" to true. To suppress this warning, add <param name="Grid/FromDepth" type="string" value="false"/>
[ INFO] [1625842721.399706650, 135.114000000]: Setting "Grid/RangeMax" parameter to 0 (default 5.000000) as "subscribe_scan", "subscribe_scan_cloud" or "gen_scan" is true and Grid/FromDepth is false.
[ WARN] [1625842721.399778066, 135.114000000]: Setting "RGBD/ProximityPathMaxNeighbors" parameter to 10 (default 0) as "subscribe_scan" is true and "Reg/Strategy" uses ICP. Proximity detection by space will be also done by merging close scans. To disable, set "RGBD/ProximityPathMaxNeighbors" to 0. To suppress this warning, add <param name="RGBD/ProximityPathMaxNeighbors" type="string" value="10"/>
[ INFO] [1625842721.401754654, 135.116000000]: Update RTAB-Map parameter "Optimizer/Epsilon"="0.00001" from database
[ INFO] [1625842721.401872965, 135.116000000]: Update RTAB-Map parameter "Optimizer/GravitySigma"="0.0" from database
[ INFO] [1625842721.401890291, 135.116000000]: Update RTAB-Map parameter "Optimizer/Iterations"="100" from database
[ INFO] [1625842721.401909790, 135.116000000]: Update RTAB-Map parameter "Optimizer/Strategy"="0" from database
[ INFO] [1625842721.401970928, 135.116000000]: Update RTAB-Map parameter "Vis/BundleAdjustment"="0" from database
[ INFO] [1625842721.401993553, 135.116000000]: Update RTAB-Map parameter "Vis/PnPRefineIterations"="1" from database
[ INFO] [1625842721.402374129, 135.116000000]: RTAB-Map detection rate = 1.000000 Hz
[ INFO] [1625842721.402474743, 135.116000000]: rtabmap: Using database from "/home/rosmatch/Documents/RTAB-Map/rtabmap.db" (1672 MB).
[ INFO] [1625842722.011962778, 135.496000000]: rtabmap: Working Memory = 1889, Local map = 0.
[ INFO] [1625842722.012145023, 135.496000000]: rtabmap: Database version = "0.20.11".
[ INFO] [1625842722.012204189, 135.496000000]: rtabmap: SLAM mode (Mem/IncrementalMemory=true)
[ INFO] [1625842722.040600120, 135.513000000]: /rtabmap/rtabmap: subscribe_depth = true
[ INFO] [1625842722.040651436, 135.513000000]: /rtabmap/rtabmap: subscribe_rgb = true
[ INFO] [1625842722.040672185, 135.513000000]: /rtabmap/rtabmap: subscribe_stereo = false
[ INFO] [1625842722.040692127, 135.513000000]: /rtabmap/rtabmap: subscribe_rgbd = false (rgbd_cameras=1)
[ INFO] [1625842722.040713165, 135.513000000]: /rtabmap/rtabmap: subscribe_odom_info = false
[ INFO] [1625842722.040733508, 135.513000000]: /rtabmap/rtabmap: subscribe_user_data = false
[ INFO] [1625842722.040749739, 135.513000000]: /rtabmap/rtabmap: subscribe_scan = true
[ INFO] [1625842722.040766452, 135.513000000]: /rtabmap/rtabmap: subscribe_scan_cloud = false
[ INFO] [1625842722.040783470, 135.513000000]: /rtabmap/rtabmap: subscribe_scan_descriptor = false
[ INFO] [1625842722.040804188, 135.513000000]: /rtabmap/rtabmap: queue_size    = 10
[ INFO] [1625842722.040826551, 135.513000000]: /rtabmap/rtabmap: approx_sync   = true
[ INFO] [1625842722.040901312, 135.513000000]: Setup depth callback
[ INFO] [1625842722.064478061, 135.524000000]: 
/rtabmap/rtabmap subscribed to (approx sync):
   /camera/color/image_raw \
   /camera/depth/image_raw \
   /camera/color/camera_info \
   /scan
[ INFO] [1625842722.188510299, 135.611000000]: rtabmap 0.20.13 started...
[FATAL] (2021-07-09 16:58:42.406) Memory.cpp:4143::createSignature() Condition (data.depthOrRightRaw().empty() || ( ( data.depthOrRightRaw().type() == CV_16UC1 || data.depthOrRightRaw().type() == CV_32FC1 || data.depthOrRightRaw().type() == CV_8UC1) && ( (data.imageRaw().empty() && data.depthOrRightRaw().type() != CV_8UC1) || (data.depthOrRightRaw().rows <= data.imageRaw().rows && data.depthOrRightRaw().cols <= data.imageRaw().cols)))) not met! [image=(640/480, type=16, [accepted=0,16]) depth=(1280/720, type=2 [accepted=2(depth mm),5(depth m),0(stereo)]). For stereo, left and right images should be same size. For RGB-D, depth can be X times smaller than RGB (where X is an integer).]
terminate called after throwing an instance of 'UException'
  what():  [FATAL] (2021-07-09 16:58:42.406) Memory.cpp:4143::createSignature() Condition (data.depthOrRightRaw().empty() || ( ( data.depthOrRightRaw().type() == CV_16UC1 || data.depthOrRightRaw().type() == CV_32FC1 || data.depthOrRightRaw().type() == CV_8UC1) && ( (data.imageRaw().empty() && data.depthOrRightRaw().type() != CV_8UC1) || (data.depthOrRightRaw().rows <= data.imageRaw().rows && data.depthOrRightRaw().cols <= data.imageRaw().cols)))) not met! [image=(640/480, type=16, [accepted=0,16]) depth=(1280/720, type=2 [accepted=2(depth mm),5(depth m),0(stereo)]). For stereo, left and right images should be same size. For RGB-D, depth can be X times smaller than RGB (where X is an integer).]
[rtabmap/rtabmap-1] process has died [pid 26951, exit code -6, cmd /home/rosmatch/catkin_ws_Haidar/devel/lib/rtabmap_ros/rtabmap scan:=/scan rgb/image:=/camera/color/image_raw depth/image:=/camera/depth/image_raw rgb/camera_info:=/camera/color/camera_info grid_map:=/map __name:=rtabmap __log:=/home/rosmatch/.ros/log/c1faf2d0-e0c5-11eb-98b2-901b0e1e89c3/rtabmap-rtabmap-1.log].
log file: /home/rosmatch/.ros/log/c1faf2d0-e0c5-11eb-98b2-901b0e1e89c3/rtabmap-rtabmap-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

And My Topic List:

/amcl/parameter_descriptions
/amcl/parameter_updates
/amcl_pose
/b_scan
/b_scan_rep117
/camera/color/camera_info
/camera/color/image_raw
/camera/color/image_raw/compressed
/camera/color/image_raw/compressed/parameter_descriptions
/camera/color/image_raw/compressed/parameter_updates
/camera/color/image_raw/compressedDepth
/camera/color/image_raw/compressedDepth/parameter_descriptions
/camera/color/image_raw/compressedDepth/parameter_updates
/camera/color/image_raw/theora
/camera/color/image_raw/theora/parameter_descriptions
/camera/color/image_raw/theora/parameter_updates
/camera/depth/camera_info
/camera/depth/color/points
/camera/depth/image_raw
/camera/depth/image_raw/compressed
/camera/depth/image_raw/compressed/parameter_descriptions
/camera/depth/image_raw/compressed/parameter_updates
/camera/depth/image_raw/compressedDepth
/camera/depth/image_raw/compressedDepth/parameter_descriptions
/camera/depth/image_raw/compressedDepth/parameter_updates
/camera/depth/image_raw/theora
/camera/depth/image_raw/theora/parameter_descriptions
/camera/depth/image_raw/theora/parameter_updates
/camera/infra1/camera_info
/camera/infra1/image_raw
/camera/infra1/image_raw/compressed
/camera/infra1/image_raw/compressed/parameter_descriptions
/camera/infra1/image_raw/compressed/parameter_updates
/camera/infra1/image_raw/compressedDepth
/camera/infra1/image_raw/compressedDepth/parameter_descriptions
/camera/infra1/image_raw/compressedDepth/parameter_updates
/camera/infra1/image_raw/theora
/camera/infra1/image_raw/theora/parameter_descriptions
/camera/infra1/image_raw/theora/parameter_updates
/camera/infra2/camera_info
/camera/infra2/image_raw
/camera/infra2/image_raw/compressed
/camera/infra2/image_raw/compressed/parameter_descriptions
/camera/infra2/image_raw/compressed/parameter_updates
/camera/infra2/image_raw/compressedDepth
/camera/infra2/image_raw/compressedDepth/parameter_descriptions
/camera/infra2/image_raw/compressedDepth/parameter_updates
/camera/infra2/image_raw/theora
/camera/infra2/image_raw/theora/parameter_descriptions
/camera/infra2/image_raw/theora/parameter_updates
/clicked_point
/clock
/diagnostics
/f_scan
/f_scan_rep117
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/ground_truth
/imu_data
/initialpose
/joint_states
/map
/map_metadata
/map_updates
/mobile_base_controller/cmd_vel
/mobile_base_controller/odom
/mobile_base_controller/parameter_descriptions
/mobile_base_controller/parameter_updates
/move_base/cancel
/move_base/feedback
/move_base/goal
/move_base/result
/move_base/status
/move_base_node/DWAPlannerROS/cost_cloud
/move_base_node/DWAPlannerROS/global_plan
/move_base_node/DWAPlannerROS/local_plan
/move_base_node/DWAPlannerROS/parameter_descriptions
/move_base_node/DWAPlannerROS/parameter_updates
/move_base_node/DWAPlannerROS/trajectory_cloud
/move_base_node/NavfnROS/plan
/move_base_node/current_goal
/move_base_node/global_costmap/costmap
/move_base_node/global_costmap/costmap_updates
/move_base_node/global_costmap/footprint
/move_base_node/global_costmap/inflation/parameter_descriptions
/move_base_node/global_costmap/inflation/parameter_updates
/move_base_node/global_costmap/navigation_map/parameter_descriptions
/move_base_node/global_costmap/navigation_map/parameter_updates
/move_base_node/global_costmap/obstacles/clearing_endpoints
/move_base_node/global_costmap/obstacles/parameter_descriptions
/move_base_node/global_costmap/obstacles/parameter_updates
/move_base_node/global_costmap/obstacles/voxel_grid
/move_base_node/global_costmap/parameter_descriptions
/move_base_node/global_costmap/parameter_updates
/move_base_node/local_costmap/costmap
/move_base_node/local_costmap/costmap_updates
/move_base_node/local_costmap/footprint
/move_base_node/local_costmap/inflation/parameter_descriptions
/move_base_node/local_costmap/inflation/parameter_updates
/move_base_node/local_costmap/obstacles/clearing_endpoints
/move_base_node/local_costmap/obstacles/parameter_descriptions
/move_base_node/local_costmap/obstacles/parameter_updates
/move_base_node/local_costmap/obstacles/voxel_grid
/move_base_node/local_costmap/parameter_descriptions
/move_base_node/local_costmap/parameter_updates
/move_base_node/parameter_descriptions
/move_base_node/parameter_updates
/move_base_simple/goal
/particlecloud
/rosout
/rosout_agg
/rtabmap/cloud_ground
/rtabmap/cloud_map
/rtabmap/cloud_obstacles
/rtabmap/global_path
/rtabmap/global_path_nodes
/rtabmap/global_pose
/rtabmap/goal
/rtabmap/goal_node
/rtabmap/goal_out
/rtabmap/goal_reached
/rtabmap/gps/fix
/rtabmap/grid_prob_map
/rtabmap/imu
/rtabmap/info
/rtabmap/initialpose
/rtabmap/labels
/rtabmap/landmarks
/rtabmap/local_grid_empty
/rtabmap/local_grid_ground
/rtabmap/local_grid_obstacle
/rtabmap/local_path
/rtabmap/local_path_nodes
/rtabmap/localization_pose
/rtabmap/mapData
/rtabmap/mapGraph
/rtabmap/mapPath
/rtabmap/octomap_binary
/rtabmap/octomap_empty_space
/rtabmap/octomap_full
/rtabmap/octomap_global_frontier_space
/rtabmap/octomap_grid
/rtabmap/octomap_ground
/rtabmap/octomap_obstacles
/rtabmap/octomap_occupied_space
/rtabmap/proj_map
/rtabmap/scan_map
/rtabmap/user_data_async
/scan
/tf
/tf_static

Thank You in advance

**Comment by matlabbe** [comment]
Hi, rtabmap is expecting a RGB image always equal or larger than the depth image. In your case, the depth image is 2x larger than the RGB image. Depth= 1280x720 and RGB=640x480. Do you have a RGB topic at 1280x720 resolution? or a depth topic at 640x480 resolution that you could use instead?

**Comment by Haydar1990** [comment]
Thank you very much, I already have the file d435.xarco edited and it works.
