### ISSUE TITLE
Facing issue while compiling the RTABMAP for IOS iPad

### ISSUE THREAD

**Issue by CARRTUSF** [introlab/rtabmap#755]
This is really a great resource. I have been trying to recreate it but  facing trouble while compiling the IOS app for iPad device. 

ld: in /Users/-----/Downloads/rtabmap-master/app/ios/RTABMapApp/Libraries/lib/vtk.framework/vtk(vtkColorSeries.cxx.o), building for iOS, but linking in object file (/Downloads/rtabmap-master/app/ios/RTABMapApp/Libraries/lib/vtk.framework/vtk(vtkColorSeries.cxx.o)) built for iOS Simulator, file '/Downloads/rtabmap-master/app/ios/RTABMapApp/Libraries/lib/vtk.framework/vtk' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

it would be great if the libraries and frameworks are included prebuilt , as the sh file provided is giving too many errors while cross compiling.

**Comment by niejd2500** [comment]
@CARRTUSF  I have encountered the same problem. How did you solve it?
