### ISSUE TITLE
Galactic bloom release

### ISSUE THREAD

**Issue by Timple** [introlab/rtabmap#757]
Could it be possible to release this package for ROS galactic?

Unfortunately it's hard to use ROS2 foxy as the rosbag2 is unreliable there ([source](https://discourse.ros.org/t/fast-forward-merging-rosbag2-master-api-to-foxy/18927)).

Therefor the request to get a galactic (and possible rolling?) release. It works when compile from source, but it's a significant compilation effort every time.

**Comment by matlabbe** [comment]
See https://github.com/introlab/rtabmap-release/issues/1
Galactic and Rolling binaries would be available soon.
