### ISSUE TITLE
Cross-Compilation android help

### ISSUE THREAD

**Issue by diophantine86** [introlab/rtabmap#76]
i have used Cross-Complie toolchain to complied pcl ,g2o and opencv.but i donnot know how to complie all the code.where can i change the code to help android-cmake find the lib and include?
thx again~/

**Comment by matlabbe** [comment]
I install all dependencies in the same install directory. For example : `~/android_install`. So I add `-DCMAKE_INSTALL_PREFIX=~/android_install` to each cmake compilation. When you do that with rtabmap too, cmake should look for dependency in the directory before `/usr` or `/usr/local`.

**Comment by matlabbe** [comment]
Added info to #74
