### ISSUE TITLE
How to analyse .db file?

### ISSUE THREAD

**Issue by FinnMarty** [introlab/rtabmap#762]
Hi, I would like to analyse the .db file with pointcloud in windows via Meshlab. Is there any way to transform the formation of .db file? Thanks

**Comment by rlabs-oss** [comment]
Export 3D clouds via the menu

**Comment by FinnMarty** [comment]
> Export 3D clouds via the menu

Thanks for reply. You mean the menu in Rviz?

**Comment by parkerlreed** [comment]
In rtabmap you can open the database (db) and the export from the File menu.

**Comment by FinnMarty** [comment]
> In rtabmap you can open the database (db) and then export from the File menu.
> 
> ![image](https://user-images.githubusercontent.com/841440/129114667-4e1f0ab4-b653-4047-96d6-7d75b64c7c49.png)

Clear! Thanks for the guide with pic.
