### ISSUE TITLE
how to debug example rgbdmapping with rtabmap?

### ISSUE THREAD

**Issue by Willforcv** [introlab/rtabmap#788]
first, i build rtabmap with cmake_build_type=debug and install, the build the example rtabmapping, when debug with ide （qt creator or vscode）, i could not step into the rtabmap source code？

**Comment by matlabbe** [comment]
Debugging the main application can be difficult as many threads are used. You may try this example https://github.com/introlab/rtabmap/tree/master/examples/NoEventsExample, which doesn't use any threads. It could be easier to debug. I am not used to qtcreator or vscode for debugging, cannot really help there. 

Another way to debug is to launch RTAB-Map with logger level to Debug, you will then get a lot of debug stuff, and you can add new ones with `UDEBUG()` or `UWARN()` to better see when they happen.
