### ISSUE TITLE
iOS Build failed because ULogger  not found

### ISSUE THREAD

**Issue by WiiLin** [introlab/rtabmap#789]
![截圖 2021-11-27 上午12 04 46](https://user-images.githubusercontent.com/10156607/143607073-939e9055-0b45-47d6-ab5a-aafde32f7b6a.png)

**Comment by matlabbe** [comment]
Did you follow this? https://github.com/introlab/rtabmap/wiki/Installation#ios
or the `install.sh` has failed?

**Comment by diandrakathyusha** [comment]
Hi, I have the same exact issue. I have followed the instruction. And yes, I think my install.sh has failed. I am using MacOS Monterey on a Mac Mini 2014. Do you have any other alternative than the `$ ./install.sh` ?

**Comment by matlabbe** [comment]
Ohhh, I didn't try to build on any Intel Mac. This may be the issue as I just tried again on my Mac Mini M1 and the script worked.

**Comment by matlabbe** [comment]
I think it is a duplicate of https://github.com/introlab/rtabmap/issues/998, will close as it is fixed.
