### ISSUE TITLE
how can i use rtabmap without RGBD camera or anyother hardware?

### ISSUE THREAD

**Issue by jcyhcs** [introlab/rtabmap#797]
hi,professor:
i have success compile rtabmap on nvidia jetson nano platform, i want to test 3D reconstruction, but now i don't have a RGBD camera, so, is there any dataset for RGBD camera used by rtabmap, is there any tutorial? please HELP ME!

**Comment by matlabbe** [comment]
See databases from this post: https://github.com/introlab/rtabmap/wiki/Multi-Session-Mapping-with-RTAB-Map-Tango
