### ISSUE TITLE
segmentation fault when running rtabmap?

### ISSUE THREAD

**Issue by jcyhcs** [introlab/rtabmap#798]

**Comment by Shishir-Kumar-Singh** [comment]
> hi,professor: i compile rtabmap standalone success on nvidia jetson tx2, but when i try to run rtabmap, i got segmentation fault: ![image](https://user-images.githubusercontent.com/34532224/147321735-2ce46922-3913-4a0f-a38e-5b6dcbf4e9ac.png) please HELP ME!

@jcyhcs hi, the segmentation fault comes when the linked libraries have version mismatch. So at the time of compiling try to check the path of the VTK, OpenGL and Qt. I assume, you have manually compiled VTK with OpenGL2 and link library is the correct one.

**Comment by jcyhcs** [comment]
@Shishir-Kumar-Singh 
thanks professor! i remove all files about qt5,then i re-install qt5 and re-compile rtabmap, then it works fine. i  also flow tutorials, then i save an obj file, like this:
![image](https://user-images.githubusercontent.com/34532224/147456896-95b0605b-f6bb-4b08-978a-27ed3adbee6b.png)
emm.., i open it with meshlab, but how can i look inside it? for example cut it half , so i can look the inside, like the example 
![image](https://user-images.githubusercontent.com/34532224/147457065-488a3127-bab4-4e19-b206-a7b057cddb5e.png)
i don't know how ? please help!
