### ISSUE TITLE
High CPU Usage (100% all cores/threads)

### ISSUE THREAD

**Issue by matlabbe** [introlab/rtabmap#822]
Most of the cases, this is related to OpenMP, try setting environment variable OMP_WAIT_POLICY to passive.

On Unix:
```bash
export OMP_WAIT_POLICY=passive
```

**Comment by Marabir** [comment]
@matlabbe  Thanks Man for this answer!!! 
I was struggling for about a week with icp_odometry package, I had 
Odom: ratio=0.634921, std dev=0.008052m|0.002546rad, update time=0.003815s
but command line was freezing regularly. 

but /rtabmap/odometry topic frequency was about 6 Hz and performance was poor. Usually stuck and freeze. I noticed that CPU usage is about 1000% (we use i7 with 12 cores and 16 threads so performance should be all right) But when I made this export, the odom topic frequency has doubled to 12 Hz (same as lidar used) and everything run smoothly. Thank you thank you <3
