### ISSUE TITLE
Regarding initializing Localization

### ISSUE THREAD

**Issue by sumitsarkar1** [introlab/rtabmap#824]
I have a pre-build map and in Localization mode I want to start displaying the pose of a robot on a remote compute ONLY when RTabMap flashes yellow or green i.e. a local match or a loop closure match .Which class/variable captures this successful initialization of localization so that once that happens I start transmitting the live poses and NOT before that.

**Comment by matlabbe** [comment]
You could look at the `loopClosureId` (green) or `proximityDetectionId` (yellow) members of http://docs.ros.org/en/lunar/api/rtabmap_ros/html/msg/Info.html (/`rtabmap/info` topic), which witll be !=0 when it happens.

**Comment by sumitsarkar1** [comment]
and for the standalone RTabMap

**Comment by matlabbe** [comment]
If you catch RtabmapEvent event, the statistics contain 
https://github.com/introlab/rtabmap/blob/578c19cc38d11f6542ab1dc351cff7a9fa646fec/corelib/include/rtabmap/core/Statistics.h#L266-L269
