### ISSUE TITLE
rtabmap with depthai

### ISSUE THREAD

**Issue by nickjrz** [introlab/rtabmap#825]
I am currently trying to build rtabmap with depthai and it seems that it succeeds at finding it, see picture attached. But when I check `rtabmap --version` it shows as Depthai = false and driver for OAK-D is disabled on the camera drivers. I am also specifying path of installation for depthai-core on the cmake command, depthai core has been built with depthai shared too. Any insight on what this behavior could be?

![rtabmap_depthai-core_issue](https://user-images.githubusercontent.com/56938367/153056626-d0406f36-2b20-4f7a-808b-c5019d599a3e.png)
![rtabmap_depthai-core_issue2](https://user-images.githubusercontent.com/56938367/153056639-0538ba4b-1b75-4fc6-bb93-b1c387543c79.png)

**Comment by matlabbe** [comment]
This is version 0.20.16 launching, if you used latest master, it should be 0.20.19. You can do `which rtabmap` to know which one you are starting. It is maybe the binaries that are built without depthai. If you want to start the built one, don't forget `./` in `./rtabmap`.

**Comment by nickjrz** [comment]
I found the issue, it was trying to launch my ros installation instead of the binary built from source, even if doing ./rtabmap . I ended up removing my ros installation and it worked fine, thanks for the help.
