### ISSUE TITLE
compilation error of rtabmap_gui

### ISSUE THREAD

**Issue by nguyenduchoangha** [introlab/rtabmap#83]
ubuntu@tegra-ubuntu:~/slam/rtabmap/build$ cmake -DCMAKE_INSTALL_PREFIX=/home/ubuntu/ros_ws/devel ..
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- Found OpenMP
-- Found OpenCV: /usr/include/opencv;/usr/include
-- Found PCL: /usr/include/pcl-1.7;/usr/include/eigen3;/usr/include;/usr/include/ni;/usr/include/vtk-5.8
-- Found ZLIB: /usr/include
-- Found Freenect: /opt/ros/indigo/include/libfreenect
-- Found OpenNI2: /usr/include/openni2
-- Could NOT find CSPARSE (missing:  CSPARSE_INCLUDE_DIR CSPARSE_LIBRARY) 
-- Found Pthreads
-- --------------------------------------------
-- Info :
--   Version : 0.11.5
--   CMAKE_INSTALL_PREFIX = /home/ubuntu/ros_ws/devel
--   CMAKE_BUILD_TYPE =     Release
--   CMAKE_INSTALL_LIBDIR = lib/arm-linux-gnueabihf
--   BUILD_APP =            ON
--   BUILD_TOOLS =          ON
--   BUILD_EXAMPLES =       ON
--   BUILD_SHARED_LIBS =    ON
--   CMAKE_CXX_FLAGS =  -fmessage-length=0  -Wno-deprecated -fopenmp
--   With OpenCV 2 nonfree module (SIFT/SURF) = NO (not found, License: BSD)
--   With Freenect             = YES (License: Apache v2 and/or GPLv2)
--   With OpenNI2              = YES (License: Apache v2)
--   With Freenect2            = NO (libfreenect2 not found)
--   With dc1394               = NO (dc1394 not found)
--   With FlyCapture2/Triclops = NO (Point Grey SDK not found)
--   With TORO                 = YES (License: Creative Commons [Attribution-NonCommercial-ShareAlike])
--   With g2o                  = NO (g2o not found)
--   With GTSAM                = NO (GTSAM not found)
--   With VERTIGO              = YES (License: GPLv3)
--   With cvsba                = NO (cvsba not found)
--   With Qt4                  = YES (License: Open Source or Commercial)
-- --------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/slam/rtabmap/build
ubuntu@tegra-ubuntu:~/slam/rtabmap/build$ make
Scanning dependencies of target rtabmap_utilite
[  0%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UEventsManager.cpp.o
[  1%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UEventsHandler.cpp.o
[  1%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UEventsSender.cpp.o
[  2%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UFile.cpp.o
[  2%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UDirectory.cpp.o
[  3%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UConversion.cpp.o
[  3%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/ULogger.cpp.o
[  4%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UThread.cpp.o
[  4%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UTimer.cpp.o
[  5%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UProcessInfo.cpp.o
[  5%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UVariant.cpp.o
Linking CXX shared library ../../../bin/librtabmap_utilite.so
[  5%] Built target rtabmap_utilite
Scanning dependencies of target res_tool
[  6%] Building CXX object utilite/resource_generator/CMakeFiles/res_tool.dir/main.cpp.o
Linking CXX executable ../../../bin/rtabmap-res_tool
[  6%] Built target res_tool
[  6%] [Creating resources]
 Using namespace=rtabmap
 Using target directory=/home/ubuntu/slam/rtabmap/build/corelib/src
Input file "/home/ubuntu/slam/rtabmap/corelib/src/resources/DatabaseSchema.sql" size = 3800 bytes
Output file "/home/ubuntu/slam/rtabmap/build/corelib/src/DatabaseSchema_sql.h" size = 7815 bytes
Scanning dependencies of target rtabmap_core
[  7%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Rtabmap.cpp.o
[  7%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/RtabmapThread.cpp.o
[  8%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Statistics.cpp.o
[  8%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Memory.cpp.o
[  9%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/DBDriver.cpp.o
[  9%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/DBDriverSqlite3.cpp.o
[ 10%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/DBReader.cpp.o
[ 10%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Camera.cpp.o
[ 11%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/CameraThread.cpp.o
[ 11%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/CameraRGB.cpp.o
[ 12%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/CameraRGBD.cpp.o
[ 12%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/CameraStereo.cpp.o
[ 13%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/CameraModel.cpp.o
[ 13%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/EpipolarGeometry.cpp.o
[ 14%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/VisualWord.cpp.o
[ 15%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/VWDictionary.cpp.o
[ 15%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/BayesFilter.cpp.o
[ 16%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Parameters.cpp.o
[ 16%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Signature.cpp.o
[ 17%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Features2d.cpp.o
[ 17%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Transform.cpp.o
[ 18%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/GeodeticCoords.cpp.o
[ 18%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/util2d.cpp.o
[ 19%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/util3d.cpp.o
[ 19%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/util3d_filtering.cpp.o
[ 20%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/util3d_mapping.cpp.o
[ 20%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/util3d_transforms.cpp.o
[ 21%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/util3d_registration.cpp.o
[ 21%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/util3d_surface.cpp.o
[ 22%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/util3d_features.cpp.o
[ 22%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/util3d_correspondences.cpp.o
[ 23%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/util3d_motion_estimation.cpp.o
[ 23%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/SensorData.cpp.o
[ 24%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Graph.cpp.o
[ 25%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Compression.cpp.o
[ 25%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Link.cpp.o
[ 26%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Optimizer.cpp.o
[ 26%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/OptimizerTORO.cpp.o
[ 27%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/OptimizerG2O.cpp.o
[ 27%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/OptimizerGTSAM.cpp.o
[ 28%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/OptimizerCVSBA.cpp.o
[ 28%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Registration.cpp.o
[ 29%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/RegistrationIcp.cpp.o
[ 29%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/RegistrationVis.cpp.o
[ 30%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Odometry.cpp.o
[ 30%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/OdometryThread.cpp.o
[ 31%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/OdometryF2M.cpp.o
[ 31%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/OdometryMono.cpp.o
[ 32%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/OdometryF2F.cpp.o
[ 32%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/Stereo.cpp.o
[ 33%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/StereoDense.cpp.o
[ 33%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/StereoCameraModel.cpp.o
[ 34%] Building C object corelib/src/CMakeFiles/rtabmap_core.dir/rtflann/ext/lz4.c.o
[ 35%] Building C object corelib/src/CMakeFiles/rtabmap_core.dir/rtflann/ext/lz4hc.c.o
[ 35%] Building C object corelib/src/CMakeFiles/rtabmap_core.dir/sqlite3/sqlite3.c.o
[ 36%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/opencv/Orb.cpp.o
[ 36%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/opencv/solvepnp.cpp.o
[ 37%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/toro3d/posegraph3.cpp.o
[ 37%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/toro3d/treeoptimizer3_iteration.cpp.o
[ 38%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/toro3d/treeoptimizer3.cpp.o
[ 38%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/toro3d/posegraph2.cpp.o
[ 39%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/toro3d/treeoptimizer2.cpp.o
Linking CXX shared library ../../../bin/librtabmap_core.so
[ 39%] Built target rtabmap_core
[ 40%] Generating qrc_GuiLib.cxx
[ 40%] Generating __/include/rtabmap/gui/moc_MainWindow.cxx
[ 41%] Generating __/include/rtabmap/gui/moc_PreferencesDialog.cxx
[ 41%] Generating __/include/rtabmap/gui/moc_DatabaseViewer.cxx
[ 42%] Generating moc_AboutDialog.cxx
[ 42%] Generating __/include/rtabmap/gui/moc_ConsoleWidget.cxx
[ 43%] Generating __/include/rtabmap/gui/moc_ImageView.cxx
[ 43%] Generating __/include/rtabmap/gui/moc_PdfPlot.cxx
[ 44%] Generating __/include/rtabmap/gui/moc_StatsToolBox.cxx
[ 44%] Generating __/include/rtabmap/gui/moc_ProgressDialog.cxx
[ 45%] Generating __/include/rtabmap/utilite/moc_UPlot.cxx
[ 46%] Generating __/include/rtabmap/utilite/moc_UImageView.cxx
[ 46%] Generating __/include/rtabmap/gui/moc_CloudViewer.cxx
[ 47%] Generating __/include/rtabmap/gui/moc_OdometryViewer.cxx
[ 47%] Generating __/include/rtabmap/gui/moc_LoopClosureViewer.cxx
[ 48%] Generating __/include/rtabmap/gui/moc_DataRecorder.cxx
[ 48%] Generating __/include/rtabmap/gui/moc_CameraViewer.cxx
[ 49%] Generating __/include/rtabmap/gui/moc_CalibrationDialog.cxx
[ 49%] Generating moc_ExportDialog.cxx
[ 50%] Generating moc_PostProcessingDialog.cxx
[ 50%] Generating moc_ExportCloudsDialog.cxx
[ 51%] Generating moc_ExportScansDialog.cxx
[ 51%] Generating moc_MapVisibilityWidget.cxx
[ 52%] Generating __/include/rtabmap/gui/moc_GraphViewer.cxx
[ 52%] Generating moc_CreateSimpleCalibrationDialog.cxx
[ 53%] Generating moc_ParametersToolBox.cxx
[ 53%] Generating ui_mainWindow.h
[ 54%] Generating ui_preferencesDialog.h
[ 54%] Generating ui_aboutDialog.h
[ 55%] Generating ui_consoleWidget.h
[ 56%] Generating ui_DatabaseViewer.h
[ 56%] Generating ui_loopClosureViewer.h
[ 57%] Generating ui_exportDialog.h
[ 57%] Generating ui_postProcessingDialog.h
[ 58%] Generating ui_exportCloudsDialog.h
[ 58%] Generating ui_exportScansDialog.h
[ 59%] Generating ui_calibrationDialog.h
[ 59%] Generating ui_createSimpleCalibrationDialog.h
Scanning dependencies of target rtabmap_gui
[ 59%] Building CXX object guilib/src/CMakeFiles/rtabmap_gui.dir/MainWindow.cpp.o
In file included from /usr/include/pcl-1.7/pcl/visualization/pcl_visualizer.h:52:0,
                 from /usr/include/pcl-1.7/pcl/visualization/cloud_viewer.h:39,
                 from /home/ubuntu/slam/rtabmap/guilib/src/MainWindow.cpp:104:
/usr/include/pcl-1.7/pcl/visualization/area_picking_event.h: In member function 'bool pcl::visualization::AreaPickingEvent::getPointsIndices(std::vector<int>&) const':
/usr/include/pcl-1.7/pcl/visualization/area_picking_event.h:64:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (nb_points_ == -1)
                              ^
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [guilib/src/CMakeFiles/rtabmap_gui.dir/MainWindow.cpp.o] Error 4
make[1]: *** [guilib/src/CMakeFiles/rtabmap_gui.dir/all] Error 2
make: *** [all] Error 2

**Comment by matlabbe** [comment]
Hi,

You may run out of memory, try to launch the compilation again or increase your swap space. For recent compilers, some files like MainWindow.cpp may require 1.5 GB RAM or more to compile.

cheers

**Comment by nguyenduchoangha** [comment]
Thank you very much! It worked!
