### ISSUE TITLE
Warning of Data Buffer is Full

### ISSUE THREAD

**Issue by sumitsarkar1** [introlab/rtabmap#830]
During Localization I make the `Detection Rate` 2Hz and `Data Buffer Size` 10. But I keep getting this warning : `addData() Data buffer is full, the oldest data is removed to add the new one.` Do I need to worry about this. I am using L515 and the rgb resolution is 960x540 . I tried going to 640x480 or 640x360 (as supported by realsense viewer) but no luck. I require 2Hz for faster localization. Any additional settings I need to take care to keep a steady 2Hz detection rate please
When I tried running only localization with 2Hz on an embedded AMD Ryzen x86 board (L515+T265) the stream stopped after some time saying `Camera has reached end of stream` . Any suggestions plz

**Comment by matlabbe** [comment]
It is like localization is slower than 500 ms. You may check in Statistics/Timing from where the high computation time is coming, and then adjust parameters to use less processing power.
