### ISSUE TITLE
How to Get Started with RGB-D SLAM if not using Kinect

### ISSUE THREAD

**Issue by zkytony** [introlab/rtabmap#834]
Hi, I think rtabmap is an awesome library and I appreciate a lot that it is still maintained. 

I am able to clone and build rtabmap (`make install`) successfully. However, I am not sure what to do next. It seems that the most basic introductory tutorials are for hand-held cameras, not for robots.

I hope to use rtabmap for a robot running ROS that has multiple grayscale RGB-D cameras that publish separate depth maps. I try to find tutorials for how to do this, but I have not had success. I looked at:

- [The RTAB-Map homepage](http://introlab.github.io/rtabmap/): This is a home page with an introduction and links to other resources.   

- [The Github home page](https://github.com/introlab/rtabmap): This is a home page with a brief message and most important links.

- [The Tutorials Wiki](https://github.com/introlab/rtabmap/wiki/Tutorials): The first-few examples are for hand-held kinect and stereo mapping. I directly have access to ROS topic streams of the depth maps and grayscale color images from multiple sources. I am not sure how to adapt.

- [The rtabmap ROS package page](http://wiki.ros.org/rtabmap): It has an exciting demo.

- [The rtabmap_ros ROS package page and the Tutorials page](http://wiki.ros.org/rtabmap_ros): There is a lot of examples about how different things can be done. I could run the most basic example for ROS in section 3.2 after installing rtabmap_ros. I am not sure how to adapt. (I can look more into this.)

Could you point me to the correct reference? Basically, I have streams of depth maps, grayscale images all of the [sensor_msgs.Image](http://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/Image.html) format, and I have corresponding intrinsics in the [sensor_msgs.CameraInfo](http://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/CameraInfo.html) format, and I also have access to /tf. It seems to me that if the library works, it should be really straightforward to set it up so that a SLAM map (both 3D and the 2D occupancy grid) can be generated using RTAB-Map. 

Thanks in advance!

**Comment by zkytony** [comment]
Never mind. The first example in [Setup RTAB-Map on Your Robot!](http://wiki.ros.org/rtabmap_ros/Tutorials/SetupOnYourRobot) is very helpful. I can run the rtabmap main node now, and just need to figure out some issues I encounter about the visualizer.

**Comment by matlabbe** [comment]
Indeed, for ROS / robot examples, these two pages are a good start:
http://wiki.ros.org/rtabmap_ros
http://wiki.ros.org/rtabmap_ros/Tutorials

In particular these links:
http://wiki.ros.org/rtabmap_ros/Tutorials/SetupOnYourRobot
http://wiki.ros.org/rtabmap_ros/Tutorials/MappingAndNavigationOnTurtlebot

**Comment by zkytony** [comment]
Thanks @matlabbe. I figured it out by trying to read and understand both "Kinect + Odometry + 2D laser" and "Kinect + Odometry + Fake 2D laser from Kinect" from http://wiki.ros.org/rtabmap_ros/Tutorials/SetupOnYourRobot 
It wasn't clear that's what I should read at first because I am not using Kinect and I don't have a 2D laser.
