### ISSUE TITLE
Tango Library

### ISSUE THREAD

**Issue by lucadambros** [introlab/rtabmap#84]
Hi,
I downloaded all the library (boost, eigen, flann, ndk, pcl) and I put them in a new folder called "android_install".
After that I tried:

`$ export ANDROID_NDK="Path to android ndk"

$ export ANDROID_NATIVE_API_LEVEL=android-17

$ cd rtabmap/build

$ cmake -DCMAKE_TOOLCHAIN_FILE=../cmake_modules/android.toolchain.cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_TOOLS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/android_install ..

$ make

$ adb install -r app/android/bin/RTABMap-debug.apk`

but it didn't work.
What I have to do?

**Comment by matlabbe** [comment]
See issue #74:

> When you are able to **cross-compile** all dependencies...

In particular, see this [post](https://github.com/introlab/rtabmap/issues/74#issuecomment-221602369) for compilation of dependencies.

cheers
