### ISSUE TITLE
Multi-Session Mapping and Forced Localization with 3D Lidar

### ISSUE THREAD

**Issue by JoelAdams001** [introlab/rtabmap#840]
Hi Mathieu!
I have been successfully creating some nice large-scale maps using a 3D Ouster lidar and it's IMU. What I have been wanting to accomplish is mapping multiple sessions and with each session after the first, localizing using the previously saved database. So I removed the --delete_db_on_start argument and set Mem/IncrementalMemory=true. 

https://answers.ros.org/question/290312/how-to-localize-in-a-previously-created-map-using-zed-laser-and-odom-in-rtabmap_ros/

However, from the above link, I found you saying that the kidnapped robot problem can only be solved visually with a camera and not while using only a 3D lidar. One of my questions is why is that? Is it impossible to detect loop closure from a previous map using features from a 3D pointcloud? And if I do have to integrate a camera to use SLAM mode, would I be able to still map with the Ouster by setting both subscribe_scan_cloud and subscribe_rbgd to true? I really appreciate the amazing software and all the work you put into it! It has been extraordinarily useful for mapping.

**Comment by matlabbe** [comment]
There is no built-in global loop closure detection based on LiDAR-only implemented in RTAB-Map. There are approaches that can do it, though I never took the time to integrate them in rtabmap. There is an external extension in this project: https://github.com/MarvinStuede/cmr_lidarloop

Without a camera, if the lidar is restarted from where the scanning stopped, it could work already. If you want to restart always from the origin of the map, set `RGBD/StartAtOrigin=true`.

You can indeed add a camera and still map with ouster, then you will have a access to global loop closure detection to relocalize anywhere.

cheers,
Mathieu
