### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by Lunatik00** [introlab/rtabmap#843]
Hi, i am using this in a project and i need to cite it, i cant find the cite data like there is for ORB-SLAM2 for example.
@article{name,
  title=,
  author=,
  journal=,
  volume=,
  number=,
  pages=,
  doi =,
  year=
 }

**Comment by matlabbe** [comment]
```
@article{labbe2019rtab,
  title={RTAB-Map as an open-source lidar and visual simultaneous localization and mapping library for large-scale and long-term online operation},
  author={Labb{\'e}, Mathieu and Michaud, Fran{\c{c}}ois},
  journal={Journal of Field Robotics},
  volume={36},
  number={2},
  pages={416--446},
  year={2019},
  publisher={Wiley Online Library}
}

```
A trick to get references like that is to use Google Scholar -> Cite -> Bibtex
![Screenshot from 2022-04-11 00-03-01](https://user-images.githubusercontent.com/2319645/162663316-b17cbb16-5369-425e-9b07-329b2405823a.jpg)

**Comment by Lunatik00** [comment]
I didn't knew that one, thank you very much.
