### ISSUE TITLE
RTABMAP IOS uses ARKIT as VO frontend?

### ISSUE THREAD

**Issue by knsjoon** [introlab/rtabmap#862]
Hello, firstly, what a great work RTABMAP is! 
It is also very impressive how RTABMAP operates on IOS as well. 

I have a question though: does RTABMAP on IOS use ARKIT poses and landmarks as the frontend of the pipeline? 

Thank you in advance. Any insight would be very appreciated : )

**Comment by matlabbe** [comment]
The VIO approach from ARKit is used, no landmarks though.
