### ISSUE TITLE
How to display 3DMap in rviz

### ISSUE THREAD

**Issue by Sugiura-Tomoki** [introlab/rtabmap#870]
Hello.
I am a Japanese student.

I couldn't see the 3D Map in the rtabmap.
Therefore, I used rviz.
Then I was able to display the 3D Map in rviz.
![Screenshot from 2022-05-09 15-25-26](https://user-images.githubusercontent.com/68367876/169960666-fcddac10-97da-427d-9bfb-edc4031ba71b.png)

But there was a problem here.
After quitting rtabmap once, I can't display the 3dmap created by rtabmap in rviz.
When I opened "rtabmap-databaseViewer", the data was saved successfully, and I was able to save cloud.ply and image data as well.
Is it possible to open those data with rviz?

Please give me some advice.
I’m sorry for the poor English.

Thank you in advance!

**Comment by matlabbe** [comment]
> I couldn't see the 3D Map in the rtabmap.

which system are you using?

Otherwise, in rviz, to show again the map, launch rtabmap without --delete_db_on_start flag. Open rviz and add MapCloud display with /rtabmap/mapData topic. You can click "Download map" checkbox under MapCloud options.
