### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by muttequrashi** [introlab/rtabmap#874]
Hi can you provide the dataset for Multi-Session Visual SLAM for Illumination Invariant Localization in
Indoor Environments

**Comment by matlabbe** [comment]
Hi,

Yes, it was my plan after the paper has been accepted. I am currently travelling, I will do that when I will have some time (in 2 next weeks hopefully). For the scripts I used to generate the results in the paper, I need to update them. The old versions of those scripts are currently in the archive directory.

**Comment by muttequrashi** [comment]
Thanks. Looking forward to it.

**Comment by matlabbe** [comment]
I updated this page with the dataset: https://github.com/introlab/rtabmap/blob/master/archive/2022-IlluminationInvariant/README.md
