### ISSUE TITLE
3D Map viewing issues on Jetson Xavier NX

### ISSUE THREAD

**Issue by sumitsarkar1** [introlab/rtabmap#889]
1.) Standalone version of RTAB-Map looks this way. Even loaded .db files are not able to be viewed.
2.) Searched the web on nvidia forums and others...could not figure out much from the solutions....any lead to a solution where this problem is fixed or any suggestions will be really helpful.
3.) JetPack 4.6 . Falling back to 4.3 is not an option because AI modules of ZED camera sdk dont work with 4.3 
4.) Shall I build vtk6 from source with QT4 and NOT QT5 and try...will it help..please comment

EDIT : I tried [this](https://github.com/introlab/rtabmap/issues/427#issuecomment-516914817) ...I could not understand Step 6 "Remove all references to Qt5" ...I replaced Qt5::Widget with QT4::Widget...does it mean that or completely delete the term Qt5::Widget

EDIT 2 : for Step 6 Qt::Widget was removed for VTKTargets.cmake and rest VTKTargts-none.cmake Qt5 was replaced by Qt4...before everything I had installed Qt4 default (along with Qt5 which was already installed). 

Some how I could not build the recent version (Multi Map error  in Illumination invariant localization module !)  .I build a a 10th Dec 2021  commit. Long story short **RTabmap works on Jetpack 4.6 with Zed camera and Neural Depth Inference** ! [this](https://github.com/introlab/rtabmap/issues/427#issuecomment-516914817) is the solution to fix the3D map not laoding issue

![Screenshot from 2022-08-19 10-12-06](https://user-images.githubusercontent.com/4591743/185600022-0307f408-69eb-469b-bbd7-d57f1d533222.png)

**Comment by pramodwic1** [comment]
Hi @sumitsarkar1 

I too have been working on installing Rtabmap on Xavier NX (with intel realsense D455). Rtabmap and the 3D map works fine after installing most libraries from source as mentioned here (https://github.com/introlab/rtabmap/issues/427#issuecomment-1000921742).

However I noticed a significant lag while running rtabmap and mapping 3D point cloud, seems like the lag increases with time to the point where it may take 5 seconds for the 3D point cloud to update to new camera position. 

Could I know your experience with it?, is it working fine for your use case?

**Comment by sumitsarkar1** [comment]
I am using ZED camera with RTabMap...right now we are experimenting with small spaces...we are just running it for 2 or 3 minutes....let me run it for more time and come back to your querry....but as of now it runs smooth...
