### ISSUE TITLE
Using a mask with valid depths when detecting ORB keypoints

### ISSUE THREAD

**Issue by ex-ratt** [introlab/rtabmap#89]
In Memory::createSignature you prevent the creation of a mask for keypoint detection if using ORB features (https://github.com/introlab/rtabmap/blob/master/corelib/src/Memory.cpp#L3219). There is a bug with ORB where mask values below 254 are set to zero for the mask for all but the original pyramid layer, which prevents any features from being detected at scales other than the original one, see https://github.com/Itseez/opencv/issues/4574. This can be circumvented by setting the mask values to 255 instead of 1 for pixels that should not be masked in Feature2D::generateKeypoints (https://github.com/introlab/rtabmap/blob/master/corelib/src/Features2d.cpp#L517).

So: Replace the mask value 1 by 255 in Feature2D::generateKeypoints, remove the second condition from the if-clause in Memory::createSignature and it should be possible to use a proper mask with ORB features, leading to more valid keypoints.

Edit: The same is true for RegistrationVis::computeTransformationImpl (https://github.com/introlab/rtabmap/blob/master/corelib/src/RegistrationVis.cpp#L264) and any other place where this code is repeated...

**Comment by matlabbe** [comment]
Great! Thx for the precise explanation. The commit above should make ORB work with masks. 

cheers,
Mathieu
