### ISSUE TITLE
Multi Cam Marker Detection for branch melodic-devel

### ISSUE THREAD

**Issue by tugbakara** [introlab/rtabmap#911]
Hi @matlabbe , I searched multi cam marker detection in rtabmap and saw this [issue](https://github.com/introlab/rtabmap_ros/issues/810), and [here](https://github.com/introlab/rtabmap/commit/4d6bc78e3d8ab8aa66d256937e98bb4e09653031) you committed changes to master only, and while I was looking melodic-devel branch side [code](https://github.com/introlab/rtabmap/blob/melodic-devel/corelib/src/MarkerDetector.cpp) **to be sure** I didn't see any commit, when will they come or just changing codes into melodic-devel branch as master is it worth to try?

**Comment by matlabbe** [comment]
You can use `master` branch under melodic. The `melodic-devel` branch is updated only when new melodic binaries are released (`ros-melodic-rtabmap`). To get latest updates, always use `master` branch.

**Comment by tugbakara** [comment]
Is it same for rtabmap_ros package?

**Comment by matlabbe** [comment]
yes
