### ISSUE TITLE
Change descriptor type of an existing database

### ISSUE THREAD

**Issue by hellovuong** [introlab/rtabmap#915]
Hello,
Thank you for this work. I encountered this recent problem. Once I have created the database with ORB descriptor (size 32), now I want to update it to SIFT descriptor (size 128), is there any way to accomplish it? I had tried to use `reprocess` tool but It doesn't do the trick. Can you give some idea?
Thank you!

**Comment by matlabbe** [comment]
Hi,

We can use rtabmap-reprocess for this, but we should set explicitly `Mem/UseOdomFeatures false` so that features are re-extracted, otherwise the features already in the database are re-used directly:
```
rtabmap-reprocess --Kp/DetectorStrategy 1 --Vis/FeatureType 1 --Mem/UseOdomFeatures false rtabmap.db output.db
```

**Comment by hellovuong** [comment]
Thank you for the reply. It works even without `Mem/UseOdomFeatures false`, the problem is in my database, and somehow that one can not be reprocessed with the new descriptor, I tried with a new database and it works.

**Comment by mattiasmar** [comment]
By calling 
rtabmap-reprocess --Kp/DetectorStrategy 1 --Vis/FeatureType 1 rtabmap.db output.db
 will the original graph of the rtabmap.db be preserved and only the features be recalculated or will the graph be recomputed?

My understanding is that the graph will be recreated and the only things that get preserved from the original db are the sensory data and the parameters that were used to create the original dB. @matlabbe Can you confirm this?

**Comment by mattiasmar** [comment]
@hellovuong Did you achieve the goal that you stated? In the process do you know if a new graph was created or if the original graph was kept intact?

**Comment by hellovuong** [comment]
@mattiasmar, Yes It will change the mapGraph if you run rtabmap-reprocess

**Comment by mattiasmar** [comment]
Any idea on how to update the descriptors _without_  changing the mapGraph?

**Comment by hellovuong** [comment]
@mattiasmar I think it is not that easy to do it but here is the idea that I have in mind now: If you still have sensor data, you can write cpp program to read images from DB and then detect kps/compute descriptor for those images and overwrite the Feature table in DB and have to create the new visual word dictionary to update Word table. I am not sure about it. Hope it gives you a rough idea of how to do it

**Comment by matlabbe** [comment]
The odometry poses will be the same, but loop closures may be different, it is why the final optimized graph may be different after reprocessing it. To recover same loop closures while changing features, you could do (disabling loop closure detection and proximity detection, and enable republishing loop closures from the input database):
```
rtabmap-reprocess --RGBD/ProximityBySpace false --Rtabmap/LoopThr 1 --Mem/GenerateIds false -pub_loops [...] rtabmap.db output.db
```
