### ISSUE TITLE
Unsuitable Qt version

### ISSUE THREAD

**Issue by kaifeichen** [introlab/rtabmap#92]
CMAKE complains while I run cmake on Ubuntu 16.04:

> Found unsuitable Qt version "5.5.1" from /usr/bin/qmake

I installed Qt using "apt-get install qt5-default".
OS is Ubuntu 16.04.

I also tried installing Qt using the official installer, but got the same problem.
Any idea how to fix this? 
Thanks!

**Comment by matlabbe** [comment]
RTAB-Map should  build on 16.04 with Qt5. You can see the build log on Xenial + qt5 [here](http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__rtabmap__ubuntu_xenial_amd64__binary/13/consoleFull#console-section-15). On the top of the log, you can see which Qt5 libraries are installed. I don't see your error in the log.

cheers
