### ISSUE TITLE
Stereo USB Camera with standalone RTabMap

### ISSUE THREAD

**Issue by sumitsarkar1** [introlab/rtabmap#922]
For the standalone RTabMap setup if we select Source as Stereo and Driver as USB can two USB camera be used as a stereo set just like we do for ONLY T265 stereo configuration or this is possible through ROS platform only

**Comment by rlabs-oss** [comment]
Standalone will support dual usb cameras, one complication is ensuring both cameras are synchronized and see exactly the same frame at the same time - this normally isn't the case if using two cameras from the same brand via usb e.g webcams.

**Comment by sumitsarkar1** [comment]
will ROS platform be helpful for synching the cams and then feed the input to RTabMap?

**Comment by rlabs-oss** [comment]
For stereo the fundamental issue to obtain both frames at the same time remains regardless of ROS or standalone.
