### ISSUE TITLE
Vis/BundleAdjustment with GTSAM

### ISSUE THREAD

**Issue by hellovuong** [introlab/rtabmap#926]
Hello, 
I am wondering why Visual Optimization with bundle adjustment `Vis/BundleAdjustment` doesn't implement with GSTAM but only g2o / cvsba or Ceres? Is there any particular reason for it? Do you have a plan to implement it, I can help with it.

**Comment by matlabbe** [comment]
Why... Lack of time :)

If you want to implement it, go ahead, I'll be thankful to review it!
