### ISSUE TITLE
Cannot find Zed in Odometry section for Zed Open Capture

### ISSUE THREAD

**Issue by sumitsarkar1** [introlab/rtabmap#928]
![WhatsApp Image 2022-11-18 at 11 40 23 AM](https://user-images.githubusercontent.com/4591743/202634177-a5ba33b5-0d0b-4a25-a81f-5f1e7f521d2f.jpeg)

Did I miss something while installing . Please help.

**Comment by matlabbe** [comment]
When building rtabmap, make sure you see at the end of `cmake ..`:
```
  With ZED                  = YES
```

**Comment by sumitsarkar1** [comment]
Its NO.....but I was thinking if Zed OpenCapture can make the IMU available on RTabMap...I am on a ONLY CPU platform ...and ZED  SDK requires GPU

**Comment by matlabbe** [comment]
Yes, IMU is available on OpenCapture
https://github.com/introlab/rtabmap/blob/860c14e0ecbc1ca79eff783a60d087d742c9dedb/corelib/src/camera/CameraStereoZedOC.cpp#L465-L466
, but not the odometry (which would have been computed by ZED SDK). You should use RTAB-Map's VO instead.

**Comment by sumitsarkar1** [comment]
@matlabbe Yes...I am using RTAB-Map's VO on CPU only platforms

**Comment by sumitsarkar1** [comment]
@matlabbe Yes...I am using RTAB-Map's VO on CPU only platforms
