### ISSUE TITLE
Camera calibration for 2D images?

### ISSUE THREAD

**Issue by parkerlreed** [introlab/rtabmap#930]
I have an image source that gives me a video via RTSP stream. 

I export the frames with FFmpeg and use that as an image data set in rtabmap standalone. 

No matter what I try to tweak in the settings, rtabmap always complains that it wants camera calibration data for SLAM mode (which is what I want to do, stitch all of them together based on the imaging data)

Is there a preset camera calibration for plain 2D images? I have not been able to get a correct calibration created and subsequently a "scan" started. 

Example video

https://user-images.githubusercontent.com/841440/202913773-de0443cb-1c21-4f2e-8aab-9ae9591f0cb9.mp4

Thank you,
-Parker Reed

**Comment by matlabbe** [comment]
RTAB-Map metric mapping requires rgb-depth images or stereo images. It won't work with only 2D images. For RTAB-Map's appearance-based mode, it can use only uncalibrated 2D images, but it is only for testing visual loop closure detection (there is no mapping).

**Comment by parkerlreed** [comment]
Thanks!
