### ISSUE TITLE
databaseViewer Graph View and RVIZ map differences and importance order

### ISSUE THREAD

**Issue by tugbakara** [introlab/rtabmap#931]
Hi @matlabbe !
When I mapped the environment, map looks nice in RVIZ side, there is not any tilt in map but when I reopened database by using databaseViewer tool I saw really bad map in graph view but when I pressed the `edit optimized 2D map ` option I saw the same map as RVIZ's map. I extracted it and I added restricted areas and imported it again then I tried to reprocess it another map but in the graph view side and also in the  `edit optimized 2D map ` option map again tilted and cannot be usable. 
**Actually, If I observe right, when rtabmap-reprocess tool is used, rtabmap algorithm bases the graph view map instead imported map that's why it merges two different db with wrong maps that're coming from graph view. How can I fix that issue, or is there anything else I did wrong? Which importance that I have to be careful for map in graph view or RVIZ?**
here the screenshots of the maps:

one of the db's map in graph view:
![Screenshot from 2022-11-21 13-50-07](https://user-images.githubusercontent.com/75507324/203040499-e1d5c4d2-56f0-4970-831e-909f54efea27.png)

imported and restrcited area map in the same db:
![Screenshot from 2022-11-21 13-47-02](https://user-images.githubusercontent.com/75507324/203040788-0255857b-5ef2-4a37-9f68-23b31c4822b0.png)

merged db with rtabmap-reprocess tool in graph view:
![Screenshot from 2022-11-21 14-00-43](https://user-images.githubusercontent.com/75507324/203041425-05f890b1-3997-4b3e-b676-6e29a6068bdc.png)

merged db in `edit optimized 2D map ` option
![Screenshot from 2022-11-21 14-00-48](https://user-images.githubusercontent.com/75507324/203041676-5c652fbe-d207-430c-a710-fbcc2124309a.png)

Have a nice day! :)

**Comment by matlabbe** [comment]
It seems related to https://github.com/introlab/rtabmap/issues/929#issuecomment-1320947206
