### ISSUE TITLE
External map adding into database

### ISSUE THREAD

**Issue by tugbakara** [introlab/rtabmap#932]
Hi @matlabbe again!
I have a question about adding external map (totally constructed by me) into db without trying to created map by rtabmap, is it possible or does it have to have any data about map itself in db to add external map into db?

**Comment by matlabbe** [comment]
What kind of external map? I'll say no as the occupancy grip should be linked to the graph somehow, the only way to do this is by mapping with rtabmap directly.

**Comment by tugbakara** [comment]
Thanks @matlabbe , have a nice day sir! :)
