### ISSUE TITLE
Multi Camera Point Cloud

### ISSUE THREAD

**Issue by sumitsarkar1** [introlab/rtabmap#936]
Just curious...can we use two ZED Mini cameras (or any multiple Stereo/RGBD sensor) and produce a combined point cloud with RTAB-Map...I mean if the current stand alone version doesnt have that feature can it be made by using RTAB-Map as a library and building on top of it

**Comment by matlabbe** [comment]
The functionality is there in the library. Note that rtabmap_ros can already do that (ros will handle inter camera synchronization).

**Comment by sumitsarkar1** [comment]
@matlabbe thanx for the clarification...one last querry...can we use the RTAB-Map C++ RGBD Mapping example to build such an example i.e. display multiple pt clouds from multiple sensors on a common coord system...I am more concerned if we can create two point clouds (from two sensors) on a common 3D coordinate system than getting the sensors synched...ofcourse synched sensors are preferrable...pardon If my understaning is errnous somewhere.

**Comment by matlabbe** [comment]
Well, you seem referring to two independent cameras mapping in same world frame. It is like starting two rtabmap in parallel, but in your example, you would want to use one rtabmap with two robots. I have plans to do multi-robot mapping someday, this would be closer to what you want I think, but it would be more each robot mapping with their own rtabmap, then send data to a master server (having another rtabmap) that would combine maps from the other robots in real-time. To have maps from multiple robots in same coordinate frame, theirs maps would need to overlap (loop closure between robots).

What I referred about multi-cameras, is that a robot having two fixed cameras on it, we can use them at the same time to estimate the robot position and also map the environment.
