### ISSUE TITLE
[Ubuntu 22.04] How to compile examples/RGBDMapping/xxx without QT and VTK?

### ISSUE THREAD

**Issue by fjlxb** [introlab/rtabmap#938]
Hello, @matlabbe , I want RTAB-Map to run rgbd code, then save occupied grid and .db file, but without GUI. So I added `-DDISABLE_VTK=ON -DBUILD_visualization=OFF`, but it could not work. Here is the code: `cmake -DDISABLE_VTK=ON -DBUILD_visualization=OFF .. && make -j2 && ./bin/rtabmap-rgbd_mapping 11`, and it turns out:
```
[ WARN] (2022-12-07 14:05:23.573) Rtabmap.cpp:321::init() Using empty database. Mapping session will not be saved unless it is closed with an output database path.
[ WARN] (2022-12-07 14:05:23.576) Memory.cpp:794::parseParameters() visFeatureType is 2 
[ WARN] (2022-12-07 14:05:23.576) Memory.cpp:795::parseParameters() kpDetectorStrategy is 6 
[ WARN] (2022-12-07 14:05:23.576) Memory.cpp:796::parseParameters() Mem/UseOdomFeatures is enabled, but Vis/FeatureType and Kp/DetectorStrategy parameters are not the same! Disabling Mem/UseOdomFeatures...
Saving rtabmap_cloud.pcd...
Saving rtabmap_cloud.pcd... failed! The cloud is empty.
Saving rtabmap_trajectory.txt ...
Saving rtabmap_trajectory.txt... failed!

```

It is similar to #396 ,but it did not work.

How can I fixed this problem?

**Comment by matlabbe** [comment]
It is like the app just closed, see my comment about replacing `app.exec()` here https://github.com/introlab/rtabmap/issues/396#issuecomment-1345661197
