### ISSUE TITLE
question about downloading dataset NCO and Rawseeds 

### ISSUE THREAD

**Issue by lynnsky** [introlab/rtabmap#94]
NCO dataset size is 1626,but this link http://www.robots.ox.ac.uk/NewCollegeData/index.php?n=Main.ZippedPanoramaImages have 8100 images.How can I get right dataset NCO.
I get BO dataset through http://www.rawseeds.org/rs/capture_sessions/view/13 , I downloaded Bovisa_2008-10-04-FRONTAL.tar.torrent .But I can't get bo image through this file.
![7 u ks3 dw p32tr42vg m](https://cloud.githubusercontent.com/assets/9796108/16544353/b581ab28-4135-11e6-83e8-b7f87df2b16e.png)

**Comment by matlabbe** [comment]
For NCO, we used only 1 image of 5 to have approximately 1 Hz input rate (~8100 images at 5 Hz). For Bovisa, try to reach the owner if you have difficulties to download their dataset.

cheers

**Comment by lynnsky** [comment]
OK!Thanks for your help

**Comment by xzwang12345** [comment]
＠lynnsky Did you solve how to download Bovisa datasets ? Thanks
