### ISSUE TITLE
Maybe a bug in the codes

### ISSUE THREAD

**Issue by Yaozh66** [introlab/rtabmap#940]
Hello, thank you for your sharing this great work. When I read your codes in the Line 112 of util3d_mapping.hpp, just like this:
![2022-12-08 15-03-37屏幕截图](https://user-images.githubusercontent.com/44368323/206381031-496b9996-84a9-4064-935b-6ff5326cc980.png)
I think that when searching for the biggest surface, is it not writing like:
`
if(min[2]<maxGroundHeight && clusteredFlatSurfaces.at(i)->size() > points)
{
     ...
}
`
instead of `if(min[2]<maxGroundHeight && clusteredFlatSurfaces.size() > points)`
which is implemented now?
Because I think clusteredFlatSurfaces.size() is the number of surface clusters instead of the area of each cluster.

**Comment by matlabbe** [comment]
Good catch! Fixed in https://github.com/introlab/rtabmap/commit/a4761ad397ce195c254f65be10f7e8e2810facd0
