### ISSUE TITLE
Possible wrong reshaping of covariance matrix

### ISSUE THREAD

**Issue by MielVdW** [introlab/rtabmap#944]
The off diagonal elements of the covariance matrix are not properly transferred.
Current code:
https://github.com/introlab/rtabmap/blob/a4761ad397ce195c254f65be10f7e8e2810facd0/corelib/src/optimizer/OptimizerGTSAM.cpp#L711-L712
Proposed fix:
` mgtsam.block(0,3,3,3) = info.block(3,0,3,3); // off diagonal`
 `mgtsam.block(3,0,3,3) = info.block(0,3,3,3); // off diagonal`

**Comment by matlabbe** [comment]
It is indeed possibly wrong. Fixed in commit above. Thx to point out.
