### ISSUE TITLE
building rtab-map for ubuntu in windows subsystem for windows, running on macbook pro 2017 make -j4 fails

### ISSUE THREAD

**Issue by PeterDaGrape** [introlab/rtabmap#945]
So im messing around and have installed ubuntu wsl because the windows version of rtab-map isnt working either. When running make -j4 it gets to around 70% and fails.

The output after running the command after successfully cmaking is attached:

[Error log.txt](https://github.com/introlab/rtabmap/files/10230890/Error.log.txt)

In an attempt to fix this ive updated and upgraded my system, and tried rebuilding multiple times.

**Comment by PeterDaGrape** [comment]
Ive managed to get this working inside windows, however this issue still stands

**Comment by matlabbe** [comment]
This kind of error:
```
c++: fatal error: Killed signal terminated program cc1plus
```
is generally a compiler error (relaunch the build and it may work), or your computer ran out of RAM. Check your RAM when compiling. You can try with `make -j1` to use less RAM.
