### ISSUE TITLE
Maybe a bug in the code

### ISSUE THREAD

**Issue by Yaozh66** [introlab/rtabmap#947]
Hello,when I read your code in Line 504-505 in RegistrationVis.cpp like:
`cv::Mat K = fromSignature.sensorData().cameraModels().size()?fromSignature.sensorData().cameraModels()[0].K():fromSignature.sensorData().stereoCameraModels()[0].left().K();`
`cv::projectPoints(kptsFrom3D, rvec, tvec, K, cv::Mat(), cornersTo);`

I think when guessing optical flow, is it properer to  use intrinsic matrix of output signature which is written as:
`cv::Mat K = toSignature.sensorData().cameraModels().size()?toSignature.sensorData().cameraModels()[0].K():toSignature.sensorData().stereoCameraModels()[0].left().K();`?

**Comment by matlabbe** [comment]
Yes, indeed, it should be "to" camera model. Fixed in commit above. Thx for reporting!
