### ISSUE TITLE
Is there a difference between lenovo phab2pro and Asus zenfone ar?

### ISSUE THREAD

**Issue by jesulinsaxo** [introlab/rtabmap#949]
I have the possibility of buying a lenovo phab 2 pro in better condition than an Asus. It is evident that the Asus is a better mobile phone, but, for Tango is there much difference between them?

**Comment by matlabbe** [comment]
For Tango pose accuracy and depth quality, it is the same. The advantage with the Asus is that the rendering is smoother (>FPS) and you can map longer before it starts lagging. If you are going to map small rooms, the phab2pro is fine.

**Comment by jesulinsaxo** [comment]
Thanks a lot!. I finally got an Asus. I'm looking forward to trying it out. (sorry for my language, I'm Spanish)
