### ISSUE TITLE
ZED Camera odometry code 

### ISSUE THREAD

**Issue by sumitsarkar1** [introlab/rtabmap#961]
When I run Zed camera (ZED 2i) the mapping starts smoothly and stops for half a second or little more and again continues...this happens periodically (on GPU Laptop as well as Jetsons) . However [Spatial Mapping Example](https://github.com/stereolabs/zed-examples/tree/master/tutorials/tutorial%205%20-%20spatial%20mapping/cpp) of ZED runs smoothly on all platforms. When I opened the cpp file CameraStereoZed.cpp I found the part in the ZedIMUThread class. Is the uSleep responsible for the periodic stopping...can we do without it.
```
	virtual void mainLoop()
	{
		double delay = 1000.0/double(rate_);
		int sleepTime = delay - 1000.0f*frameRateTimer_.getElapsedTime();
		if(sleepTime > 0)
		{
			if(accurate_)
			{
				if(sleepTime > 1)
				{
					uSleep(sleepTime-1);
				}
				// Add precision at the cost of a small overhead
				delay/=1000.0;
				while(frameRateTimer_.getElapsedTime() < delay-0.000001)
				{
					//
				}
			}
			else
			{
				uSleep(sleepTime);
			}
		}
		frameRateTimer_.start();
```
Also , any mapping session with Zed camera starts with ZED lost ...I guess its ZED odometry loss because it triggers a new map. These warnings come everytime I used ZED SDK @matlabbe Please help ! 

```
[ZED][INFO] Logging level INFO
[ZED][INFO] [Init]  Depth mode: NEURAL
[ZED][INFO] [Init]  Camera successfully opened.
[ZED][INFO] [Init]  Sensors FW version: 777
[ZED][INFO] [Init]  Camera FW version: 1523
[ZED][INFO] [Init]  Video mode: HD720@60
[ WARN] (2023-01-24 15:29:12.955) CameraStereoZed.cpp:774::captureImage() ZED lost! (trackingConfidence=0)
[ WARN] (2023-01-24 15:29:13.053) RtabmapThread.cpp:519::addData() Odometry is reset (high variance (9999.000000 >=9999 detected, stamp=1674554353.052492s). Increment map id!
[ WARN] (2023-01-24 15:29:13.054) RtabmapThread.cpp:617::getData() Triggering new map 1674554353.052492<=1674554353.052492...
```

**Comment by matlabbe** [comment]
I fixed suppressed those warnings in this [commit](https://github.com/introlab/rtabmap/commit/128d3b0d0a7a256650288d291c08429d6488a8f5), but you can also just ignore them on initialization.

For the lag issue, I am not able to reproduce your problem with my ZED2 (tested during 2 minutes). It is not a ZED2i, so not sure if this could be the difference (I hope not). Tested on ZED SDK 3.8 on cuda 11.8.
