### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by zengletian1491** [introlab/rtabmap#969]
On Ubuntu 20.04，I installed Qt 5.14.2 and other dependencies, such as GTSAM, g2o. When I typed in：
cmake .. \
> -DWITH_CERES=ON \
> -DWITH_CVSBA=ON \
> -DWITH_PYTHON=ON \
> -DCMAKE_BUILD_TYPE=Release

error occurs as follows:
-- Could NOT find Qt5PrintSupport (missing: Qt5PrintSupport_DIR)
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5Core/Qt5CoreMacros.cmake:385 (message):
  Can not use "PrintSupport" module which has not yet been found.
Call Stack (most recent call first):
  guilib/src/CMakeLists.txt:216 (QT5_USE_MODULES)

I did not solve this problem. Could you give me a hand? Thank you very much!

**Comment by matlabbe** [comment]
Should be fixed by commit above. Thx for reporting!
