### ISSUE TITLE
rtabmapviz

### ISSUE THREAD

**Issue by takahiko-hasegawa-hdjp** [introlab/rtabmap#971]
Hi there,

Is there a way to remove the blue trajectory (node and links) on rtabmapviz when I select Download All Clouds?

I just want to display 3d point clouds with any pose or trajectory
?

**Comment by matlabbe** [comment]
To remove blue map's graph, go in Preferences->3D rendering->scroll down and uncheck Show Graphs under Map column
![2023-02-08_22-38](https://user-images.githubusercontent.com/2319645/217736747-8669bdd6-f7a1-47e6-9769-02676742e2f7.jpg)

To remove the white odometry trajectory, do right-click -> Trajectory -> Show Trajectory

**Comment by takahiko-hasegawa-hdjp** [comment]
fantastic!!! worked very well thanks!
