### ISSUE TITLE
IlluminationInvariant2022 dataset outdated

### ISSUE THREAD

**Issue by ZhouJankin** [introlab/rtabmap#977]
Hi, 
Can I get the image dataset of IlluminationInvariant subject? Cause the link is outdated.

**Comment by matlabbe** [comment]
Links re-enabled: https://github.com/introlab/rtabmap/tree/master/archive/2022-IlluminationInvariant

They expire after 3 months, I put the next date in my calendar to not forget to renew them. Thx for reporting.
