### ISSUE TITLE
How to know the coordinate of origin in the pgm?

### ISSUE THREAD

**Issue by fjlxb** [introlab/rtabmap#978]
Hello, 

question is shown in the title,

Thank you~

**Comment by matlabbe** [comment]
You can get the coordinate of the image corner (-x,-y) with:
```
roscore
rosrun rtabmap_ros rtabmap _database_path:=rtabmap.db
rosrun map_server map_saver map:=grid_map
rosservice call /publish_map 1 1 0
```
For convenience, also updated DbViewer in commit above to export YAML file with origin/resolution when doing File->Export 2d optimized map..

**Comment by fjlxb** [comment]
> You can get the coordinate of the image corner (-x,-y) with:您可以通過以下方式獲取圖像角點 (-x,-y) 的坐標：
> 
> ```
> roscore
> rosrun rtabmap_ros rtabmap _database_path:=rtabmap.db
> rosrun map_server map_saver map:=grid_map
> rosservice call /publish_map 1 1 0
> ```
> 
> For convenience, also updated DbViewer in commit above to export YAML file with origin/resolution when doing File->Export 2d optimized map..為了方便起見，還在上面的提交中更新了 DbViewer，以便在執行文件-> 導出 2d 優化地圖時導出帶有原點/分辨率的 YAML 文件。

Thank you~

The yaml file can be got from the newest code.

**Comment by fjlxb** [comment]
> You can get the coordinate of the image corner (-x,-y) with:
> 
> ```
> roscore
> rosrun rtabmap_ros rtabmap _database_path:=rtabmap.db
> rosrun map_server map_saver map:=grid_map
> rosservice call /publish_map 1 1 0
> ```
> 
> For convenience, also updated DbViewer in commit above to export YAML file with origin/resolution when doing File->Export 2d optimized map..

Thank you~

The yaml file can be got from the newest code.
