### ISSUE TITLE
Use rtabmap after ML monocular depth estimation

### ISSUE THREAD

**Issue by AlexeyMatskevich** [introlab/rtabmap#983]
Hello, I have images and a depth map generated using a neural network based on the corresponding images. Is it possible to generate a map from this data?
Perhaps, if it matters, I have inverse depth, i.e. the closer the object, the higher the number.
I think this approximate example covers what I want https://www.youtube.com/watch?v=QPy7ygm_McE but for [openvslam](https://github.com/surfii3z/openvslam)

**Comment by matlabbe** [comment]
Unless the depth scale is 1:1 of reality (and not varies between depth images), it won't work with rtabmap as it requires "true" depth data. You would need to use a Monocular SLAM (7DoF) approach that can optimize the scale of the map on loop closure to account the scale drift.
