### ISSUE TITLE
build on ios simulator

### ISSUE THREAD

**Issue by macTracyHuang** [introlab/rtabmap#994]
hello, I'm new to ios deployment and would like to know if I can build ios rtabmap app on simulator instead of a real device?
I tried and got error: could not find ULogger.h

thx

**Comment by Woojin-Crive** [comment]
How did you solve it?

I have a same issue..

**Comment by macTracyHuang** [comment]
> How did you solve it?
> 
> I have a same issue..

hi, you should change sysroot from iphoneoss to iphonesimulator in the install_deps.sh.
Also, as mentioned in the shell file,  VTK need # For iphonesimulator: add -DIOS_DEVICE_ARCHITECTURES=""

**Comment by matlabbe** [comment]
For the `I tried and got error: could not find ULogger.h` error, see solution in https://github.com/introlab/rtabmap/issues/998
