### ISSUE TITLE
Release 0.21.0: Missing DLLs

### ISSUE THREAD

**Issue by roppppp** [introlab/rtabmap#997]
in the [0.21.0 release](https://github.com/introlab/rtabmap/releases) for windows 3 .dlls or more are missing, I reinstalled previous version before I could start 0.21.0 , otherwise I would get the error that Kinect20.dll torch_cpu.dll and Qt6OpenGL.dll were not found
RTABMap-0.21.0-win64-cuda11.7.exe

so dont deinstall your previous version like I did :p

[](url)
![Untitled](https://user-images.githubusercontent.com/77292951/226424729-ad0373b6-3e08-4b1f-a487-faf05e1060de.jpg)

**Comment by matlabbe** [comment]
From what I can see, only `Kinect20.dll` was missing. I re-uploaded the binaries with it. Here a screenshot of the bin directory (cuda version, including missing kinetc20.dll):
![image](https://user-images.githubusercontent.com/2319645/226513847-8dbf570c-c551-4ed5-9e8d-2ceb204e4537.png)
